// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.engine;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import lombok.ToString;
import net.ladenthin.srcmorph.config.AiFieldGenerationConfig;
import net.ladenthin.srcmorph.config.AiModelDefinitionSupport;
import net.ladenthin.srcmorph.config.SrcMorphConfiguration;
import net.ladenthin.srcmorph.indexer.ProjectIndexer;
import net.ladenthin.srcmorph.prompt.AiPromptSupport;
import net.ladenthin.srcmorph.provider.AiGenerationProvider;
import net.ladenthin.srcmorph.provider.AiGenerationProviderFactory;
import net.ladenthin.srcmorph.support.Java8CompatibilityHelper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Phase 3 orchestration: aggregates every per-package {@code package.ai.md} into a single project-level
 * {@code project.ai.md} — the top of the three-level index.
 *
 * <p>Extracted from what was {@code AggregateProjectMojo.execute()} in the
 * {@code llamacpp-ai-index-maven-plugin} module. By default this is fully deterministic (a per-package
 * lead/link table of contents, no model call); when
 * {@link SrcMorphConfiguration#getFieldGenerations()} carries at least one entry, its first entry is used
 * as the <em>optional</em> AI overview generation (one extra call synthesising a short project overview
 * paragraph from the per-package leads) — see {@link ProjectIndexer}.</p>
 */
@ToString
public final class AggregateProjectEngine {

    private static final Logger LOGGER = LoggerFactory.getLogger(AggregateProjectEngine.class);

    /** Title used for the project index when {@link SrcMorphConfiguration#getProjectName()} is absent or blank. */
    private static final String DEFAULT_PROJECT_TITLE = "project";

    private final SrcMorphConfiguration config;
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Creates a new {@link AggregateProjectEngine} for the given run configuration.
     *
     * @param config the run configuration
     */
    public AggregateProjectEngine(final SrcMorphConfiguration config) {
        this.config = config;
    }

    /**
     * Aggregates the project index beneath the configured output directory.
     *
     * @return {@code 1} if the project index was written or refreshed, {@code 0} otherwise (no package
     *         index files yet, the output directory does not exist, or the existing file is up to date)
     * @throws SrcMorphException if the overview's prompt/model definitions are misconfigured
     * @throws IOException       if the output tree cannot be read or the project index cannot be written
     */
    public int execute() throws SrcMorphException, IOException {
        final Path outputPath =
                config.getOutputDirectory().toPath().toAbsolutePath().normalize();

        LOGGER.info("Starting AI project index aggregation");
        LOGGER.info("Output directory: {}", outputPath);
        LOGGER.info("Force           : {}", config.isForce());

        if (!outputPath.toFile().exists()) {
            LOGGER.info("AI output directory does not exist, skipping project index: {}", outputPath);
            return 0;
        }

        final String projectName = config.getProjectName();
        final String title =
                projectName == null || compatibilityHelper.isBlank(projectName) ? DEFAULT_PROJECT_TITLE : projectName;

        final int written;
        final List<AiFieldGenerationConfig> fieldGenerations = config.getFieldGenerations();
        if (fieldGenerations != null && !fieldGenerations.isEmpty()) {
            written = aggregateWithOverview(outputPath, title, fieldGenerations.get(0));
        } else {
            LOGGER.info("Project overview generation: disabled (no fieldGenerations configured)");
            final ProjectIndexer indexer =
                    new ProjectIndexer(title, config.getPluginVersion(), config.getAiVersion(), config.isForce());
            written = indexer.aggregate(outputPath);
        }
        LOGGER.info("Project index files written: {}", written);

        LOGGER.info("AI project index aggregation finished.");
        return written;
    }

    /**
     * Aggregates the project index with the optional AI overview paragraph enabled, generated by the
     * given field generation. A provider is created (and closed) only on this path, so the deterministic
     * default never instantiates a model.
     *
     * @param outputPath the resolved output directory holding the {@code .ai.md} tree
     * @param title      the resolved project title
     * @param overview   the overview field generation (prompt + model)
     * @return {@code 1} if the project index was written or refreshed, {@code 0} otherwise
     * @throws SrcMorphException if the provider or model definitions are misconfigured
     * @throws IOException       if the output tree cannot be read or written
     */
    private int aggregateWithOverview(final Path outputPath, final String title, final AiFieldGenerationConfig overview)
            throws SrcMorphException, IOException {
        final AiPromptSupport promptSupport = EngineSupport.buildPromptSupport(config.getPromptDefinitions());
        final AiModelDefinitionSupport modelDefinitionSupport =
                EngineSupport.buildAiModelDefinitionSupport(config.getAiDefinitions());
        LOGGER.info("Project overview generation: enabled (prompt '{}')", overview.getPromptKey());
        final AiGenerationProviderFactory providerFactory = new AiGenerationProviderFactory();
        try (AiGenerationProvider provider = providerFactory.create(
                config.getGenerationProvider(),
                EngineSupport.resolveLlamaCppJniConfig(config, modelDefinitionSupport),
                promptSupport)) {
            final ProjectIndexer indexer = new ProjectIndexer(
                    title,
                    config.getPluginVersion(),
                    config.getAiVersion(),
                    config.isForce(),
                    provider,
                    overview,
                    promptSupport,
                    modelDefinitionSupport);
            return indexer.aggregate(outputPath);
        }
    }
}
