// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.mojo;

import java.io.File;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinition;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptDefinition;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptSupport;
import net.ladenthin.maven.llamacpp.aiindex.provider.LlamaCppJniConfig;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Parameter;

/**
 * Base class for all AI index mojos. Centralises the parameters shared by every goal
 * ({@code generate}, {@code summarize-files}, {@code summarize-packages},
 * {@code aggregate-packages}) and provides the utility methods {@link #resolveSubtrees},
 * {@link #sizeOf}, {@link #buildLlamaCppJniConfig}, and {@link #buildPromptSupport}.
 *
 * <p>Concrete subclasses must implement {@link #getLlamaContextSize()} and
 * {@link #getLlamaThreads()} so that each goal can declare its own
 * {@code @Parameter}-annotated field with the appropriate default value.</p>
 *
 * <p>{@code toString} is generated by Lombok over the {@code @Parameter} fields so
 * Maven debug logs ({@code -X}) print a useful dump of the goal's resolved
 * configuration. {@code equals}/{@code hashCode} are intentionally NOT generated:
 * Maven instantiates mojos per execution and manages them by identity.
 */
// @Parameter fields are populated by the Maven plugin framework via reflection after
// construction. NullAway is configured via ExcludedFieldAnnotations to skip them; Checker
// Framework has no equivalent option for plugin-framework fields, so we suppress class-level.
@SuppressWarnings("initialization.fields.uninitialized")
@ToString(callSuper = true)
public abstract class AbstractAiIndexMojo extends AbstractMojo {

    /** Creates a new {@link AbstractAiIndexMojo}. */
    protected AbstractAiIndexMojo() {
        // no-op
    }

    /** The Maven project base directory, injected by Maven. */
    @Parameter(defaultValue = "${project.basedir}", readonly = true, required = true)
    protected File baseDirectory;

    /**
     * Directory into which all {@code .ai.md} files are written.
     * Defaults to {@code ${project.basedir}/src/site/ai}.
     */
    @Parameter(property = "aiIndex.outputDirectory", defaultValue = "${project.basedir}/src/site/ai")
    protected File outputDirectory;

    /**
     * Global skip switch: when {@code true}, <em>every</em> AI index goal (generate,
     * aggregate-packages, aggregate-project) skips and returns immediately. To toggle a single
     * phase instead, use that goal's own {@code skip<Phase>} flag (see {@link #isPhaseSkipped()}).
     */
    @Parameter(property = "aiIndex.skip", defaultValue = "false")
    protected boolean skip;

    /**
     * When {@code true}, regenerates AI fields even when they already have a value.
     * When {@code false}, only missing or changed entries are processed.
     */
    @Parameter(property = "aiIndex.force", defaultValue = "false")
    protected boolean force;

    /**
     * Source subdirectory paths (relative to {@code basedir}) to restrict processing.
     * When empty, all discovered source roots are used.
     */
    @Parameter(property = "aiIndex.subtrees")
    protected List<String> subtrees;

    /**
     * Name of the AI generation provider to use.
     * Supported values: {@code mock}, {@code llamacpp-jni}.
     *
     * @see net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProviderFactory
     */
    @Parameter(property = "aiIndex.generationProvider", defaultValue = "mock")
    protected String generationProvider;

    /** Prompt template definitions referenced by field generation configurations. */
    @Parameter
    protected List<AiPromptDefinition> promptDefinitions;

    /**
     * AI model definitions that pair a lookup key with a complete set of model parameters.
     * Field-generation entries and the provider configuration reference these definitions
     * by key rather than embedding the full parameter set inline.
     *
     * @see net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinition
     * @see net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport
     */
    @Parameter
    protected List<AiModelDefinition> aiDefinitions;

    /** Per-field AI generation configurations controlling which prompt and AI definition to use. */
    @Parameter
    protected List<AiFieldGenerationConfig> fieldGenerations;

    /**
     * Optional native library path passed to the llama.cpp JNI provider.
     * Leave unset to use the bundled native library.
     */
    @Parameter(property = "aiIndex.llama.libraryPath")
    protected String llamaLibraryPath;

    /** Path to the GGUF model file used by the llama.cpp JNI provider. */
    @Parameter(property = "aiIndex.llama.modelPath")
    protected String llamaModelPath;

    /** Maximum number of output tokens the model may generate per request. */
    @Parameter(property = "aiIndex.llama.maxOutputTokens", defaultValue = "128")
    protected int llamaMaxOutputTokens;

    /** Sampling temperature for the llama.cpp model (lower = more deterministic). */
    @Parameter(property = "aiIndex.llama.temperature", defaultValue = "0.15")
    protected float llamaTemperature;

    // -------------------------------------------------------------------------
    // Abstract methods — subclasses declare @Parameter fields with their defaults
    // -------------------------------------------------------------------------

    /**
     * Returns the llama.cpp context window size for this goal.
     * Each concrete mojo declares its own {@code @Parameter}-annotated field and
     * implements this method to return it.
     *
     * @return configured llama.cpp context window size
     */
    protected abstract int getLlamaContextSize();

    /**
     * Returns the number of CPU threads for llama.cpp inference for this goal.
     * Each concrete mojo declares its own {@code @Parameter}-annotated field and
     * implements this method to return it.
     *
     * @return configured number of CPU threads for llama.cpp inference
     */
    protected abstract int getLlamaThreads();

    /**
     * Returns whether this individual goal (phase) is disabled by its own phase-specific skip flag,
     * independent of the global {@link #skip}. Each concrete goal declares its own
     * {@code skip<Phase>} {@code @Parameter} and returns it here, so the three phases (generate,
     * aggregate-packages, aggregate-project) can be switched on and off independently.
     *
     * @return {@code true} if this phase's own skip flag is set
     */
    protected abstract boolean isPhaseSkipped();

    // -------------------------------------------------------------------------
    // Shared utility methods
    // -------------------------------------------------------------------------

    /**
     * Returns whether this goal should skip execution: either the global {@link #skip} (which skips
     * every phase) or this phase's own {@link #isPhaseSkipped()} flag. Centralised here so every goal
     * applies the same rule identically.
     *
     * @return {@code true} if the goal must not run
     */
    protected boolean shouldSkip() {
        return skip || isPhaseSkipped();
    }

    /**
     * Resolves the configured {@link #subtrees} strings against {@code basePath},
     * filtering out any paths that do not exist on disk.
     *
     * @param basePath absolute, normalised project base directory
     * @return list of resolved, existing subtree paths; empty if none configured
     */
    protected List<Path> resolveSubtrees(final Path basePath) {
        final List<Path> resolved = new ArrayList<>();

        if (subtrees == null || subtrees.isEmpty()) {
            return resolved;
        }

        for (String subtree : subtrees) {
            final Path path = basePath.resolve(subtree).normalize();
            if (path.toFile().exists()) {
                resolved.add(path);
            } else {
                getLog().warn("Skipping missing subtree: " + path);
            }
        }

        return resolved;
    }

    /**
     * Returns the size of {@code collection}, or {@code 0} when {@code collection} is {@code null}.
     *
     * @param collection any collection, or {@code null}
     * @return number of elements, or {@code 0}
     */
    protected int sizeOf(final Collection<?> collection) {
        return collection == null ? 0 : collection.size();
    }

    /**
     * Builds a {@link net.ladenthin.maven.llamacpp.aiindex.provider.LlamaCppJniConfig} for the AI generation provider.
     *
     * <p>When {@link #fieldGenerations} is non-empty, all model parameters
     * (model path, context size, max output tokens, temperature, threads) are taken from
     * the {@link net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinition} referenced by the first entry's
     * {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig#getAiDefinitionKey()}. This ensures the provider is
     * always configured from the same definition that drives field generation.</p>
     *
     * <p>When {@link #fieldGenerations} is {@code null} or empty, the individual
     * {@code llamaModelPath}, {@code llamaContextSize}, {@code llamaMaxOutputTokens},
     * {@code llamaTemperature}, and {@code llamaThreads} parameters are used as a fallback.</p>
     *
     * @return fully populated llama.cpp configuration
     * @throws IllegalArgumentException if the first field generation's
     *                                  {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig#getAiDefinitionKey()}
     *                                  does not match any registered definition
     * @throws MojoExecutionException   propagated from {@link #buildAiModelDefinitionSupport()}
     *                                  if any AI definition is missing a required field
     */
    protected LlamaCppJniConfig buildLlamaCppJniConfig() throws MojoExecutionException {
        if (fieldGenerations != null && !fieldGenerations.isEmpty()) {
            return buildLlamaCppJniConfig(fieldGenerations.get(0).getAiDefinitionKey());
        }
        return new LlamaCppJniConfig(
                llamaLibraryPath,
                llamaModelPath,
                getLlamaContextSize(),
                llamaMaxOutputTokens,
                llamaTemperature,
                getLlamaThreads(),
                AiGenerationConfig.DEFAULT_TOP_P,
                AiGenerationConfig.DEFAULT_TOP_K,
                AiGenerationConfig.DEFAULT_MIN_P,
                AiGenerationConfig.DEFAULT_TOP_N_SIGMA,
                AiGenerationConfig.DEFAULT_REPEAT_PENALTY,
                AiGenerationConfig.DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING,
                AiGenerationConfig.DEFAULT_CACHE_PROMPT,
                AiGenerationConfig.DEFAULT_SWA_FULL,
                AiGenerationConfig.DEFAULT_CACHE_REUSE,
                AiGenerationConfig.DEFAULT_REASONING_EFFORT,
                AiGenerationConfig.DEFAULT_REASONING_BUDGET_TOKENS,
                AiGenerationConfig.DEFAULT_DRY_MULTIPLIER,
                AiGenerationConfig.DEFAULT_DRY_BASE,
                AiGenerationConfig.DEFAULT_DRY_ALLOWED_LENGTH,
                AiGenerationConfig.DEFAULT_DRY_PENALTY_LAST_N,
                Collections.emptyList(),
                Collections.emptyList());
    }

    /**
     * Builds a {@link net.ladenthin.maven.llamacpp.aiindex.provider.LlamaCppJniConfig} from a specific
     * AI model definition, identified by its key. Used by the {@code generate} goal to load a separate
     * model per routing group (one provider per distinct {@code aiDefinitionKey}).
     *
     * @param aiDefinitionKey the {@link net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinition} key
     * @return fully populated llama.cpp configuration for that definition
     * @throws IllegalArgumentException if {@code aiDefinitionKey} matches no registered definition
     * @throws MojoExecutionException   propagated from {@link #buildAiModelDefinitionSupport()}
     */
    protected LlamaCppJniConfig buildLlamaCppJniConfig(final String aiDefinitionKey) throws MojoExecutionException {
        final AiGenerationConfig config = buildAiModelDefinitionSupport().getConfig(aiDefinitionKey);
        final List<String> stopStrings = config.getStopStrings();
        final List<String> drySequenceBreakers = config.getDrySequenceBreakers();
        return new LlamaCppJniConfig(
                llamaLibraryPath,
                config.getModelPath(),
                config.getContextSize(),
                config.getMaxOutputTokens(),
                config.getTemperature(),
                config.getThreads(),
                config.getTopP(),
                config.getTopK(),
                config.getMinP(),
                config.getTopNSigma(),
                config.getRepeatPenalty(),
                config.isChatTemplateEnableThinking(),
                config.isCachePrompt(),
                config.isSwaFull(),
                config.getCacheReuse(),
                config.getReasoningEffort(),
                config.getReasoningBudgetTokens(),
                config.getDryMultiplier(),
                config.getDryBase(),
                config.getDryAllowedLength(),
                config.getDryPenaltyLastN(),
                drySequenceBreakers != null ? drySequenceBreakers : Collections.emptyList(),
                stopStrings != null ? stopStrings : Collections.emptyList());
    }

    /**
     * Builds an {@link net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptSupport} from the configured {@link #promptDefinitions}.
     *
     * <p>If any {@code <promptDefinition>} entry in the POM is missing its {@code key}
     * or {@code template}, the underlying constructor throws
     * {@link NullPointerException} with a message naming the offending list index and
     * the bad entry. This method translates that into a
     * {@link MojoExecutionException} so Maven reports it as a user configuration
     * error (the "Invalid plugin {@code <configuration>}" framing) rather than as
     * a plugin bug.</p>
     *
     * @return prompt support instance backed by the configured definitions
     * @throws MojoExecutionException if any prompt definition is missing a required field
     */
    protected AiPromptSupport buildPromptSupport() throws MojoExecutionException {
        try {
            return new AiPromptSupport(promptDefinitions);
        } catch (NullPointerException e) {
            throw new MojoExecutionException("Invalid plugin configuration: " + e.getMessage(), e);
        }
    }

    /**
     * Builds an {@link net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport} from the configured {@link #aiDefinitions}.
     *
     * <p>If any {@code <aiDefinition>} entry in the POM is missing its {@code key},
     * the underlying constructor throws {@link NullPointerException} with a message
     * naming the offending list index and the bad entry. This method translates that
     * into a {@link MojoExecutionException} so Maven reports it as a user
     * configuration error rather than as a plugin bug.</p>
     *
     * @return model definition support instance backed by the configured definitions
     * @throws MojoExecutionException if any AI definition is missing a required field
     */
    protected AiModelDefinitionSupport buildAiModelDefinitionSupport() throws MojoExecutionException {
        try {
            return new AiModelDefinitionSupport(aiDefinitions);
        } catch (NullPointerException e) {
            throw new MojoExecutionException("Invalid plugin configuration: " + e.getMessage(), e);
        }
    }

    /**
     * Logs the standard set of execution parameters that are common to every goal.
     *
     * <p>Always logs: the start message, base directory, output directory, subtrees,
     * force flag, and provider name. When {@code resolvedExtensions} is non-{@code null}
     * it is also logged; goals that do not use file-extension filtering (e.g.
     * {@code aggregate-packages}) pass {@code null} to suppress that line.</p>
     *
     * @param startMessage       first log line that identifies which goal is starting
     * @param basePath           resolved, absolute project base directory
     * @param outputPath         resolved, absolute output directory
     * @param resolvedSubtrees   resolved subtree paths; may be empty but not {@code null}
     * @param resolvedExtensions file extensions in scope; pass an empty list when not applicable
     */
    protected void logExecutionParameters(
            final String startMessage,
            final Path basePath,
            final Path outputPath,
            final List<Path> resolvedSubtrees,
            final List<String> resolvedExtensions) {
        getLog().info(startMessage);
        getLog().info("Base directory  : " + basePath);
        getLog().info("Output directory: " + outputPath);
        getLog().info("Subtrees        : " + resolvedSubtrees);
        if (!resolvedExtensions.isEmpty()) {
            getLog().info("Extensions      : " + resolvedExtensions);
        }
        getLog().info("Force           : " + force);
        getLog().info("Provider        : " + generationProvider);
        getLog().info("LlamaCpp Temperature: " + llamaTemperature);
        getLog().info("LlamaCpp Max Output Tokens: " + llamaMaxOutputTokens);
    }
}
