// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.mojo;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.indexer.ProjectIndexer;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

/**
 * Maven goal {@code ai-index:aggregate-project}: aggregates every per-package
 * {@code package.ai.md} into a single project-level {@code project.ai.md} — the top of the
 * three-level index.
 *
 * <p>Unlike {@code generate} and {@code aggregate-packages}, this goal is fully deterministic: it
 * harvests the one-line lead already present in each package summary and writes a compact, navigable
 * table of contents that links to every package. It calls no AI model, so it needs no provider,
 * model, or prompt configuration — only {@link #outputDirectory}, {@link #force}, and {@link #skip}.
 * It therefore extends {@link AbstractMojo} directly rather than the provider-oriented
 * {@code AbstractAiIndexMojo}, exposing only the parameters it actually uses.</p>
 *
 * <p>{@code toString} is generated by Lombok over the {@code @Parameter} fields so Maven debug logs
 * ({@code -X}) print a useful dump of the goal's resolved configuration. {@code equals}/{@code hashCode}
 * are intentionally NOT generated: Maven instantiates mojos per execution and manages them by identity.</p>
 */
// @Parameter fields are populated by the Maven plugin framework via reflection after
// construction. NullAway is configured via ExcludedFieldAnnotations to skip them; Checker
// Framework has no equivalent option for plugin-framework fields, so we suppress class-level.
@SuppressWarnings("initialization.fields.uninitialized")
@Mojo(name = "aggregate-project", threadSafe = true)
@ToString
public class AggregateProjectMojo extends AbstractMojo {

    /** Creates a new {@link AggregateProjectMojo}. */
    public AggregateProjectMojo() {
        // no-op
    }

    /**
     * Title used for the project index when the Maven {@code ${project.name}} is absent or blank.
     */
    private static final String DEFAULT_PROJECT_TITLE = "project";

    /**
     * Directory that holds the {@code .ai.md} tree and into which {@code project.ai.md} is written.
     * Defaults to {@code ${project.basedir}/src/site/ai}.
     */
    @Parameter(property = "aiIndex.outputDirectory", defaultValue = "${project.basedir}/src/site/ai")
    private File outputDirectory;

    /** When {@code true}, the goal skips all processing and returns immediately. */
    @Parameter(property = "aiIndex.skip", defaultValue = "false")
    private boolean skip;

    /** When {@code true}, rewrites {@code project.ai.md} even when it is unchanged. */
    @Parameter(property = "aiIndex.force", defaultValue = "false")
    private boolean force;

    /** Plugin version recorded in the project index header. */
    @Parameter(defaultValue = "${project.version}", readonly = true)
    private String pluginVersion;

    /** AI summarisation logic version recorded in the project index header. */
    @Parameter(property = "aiIndex.aiVersion", defaultValue = "0.0.0")
    private String aiVersion;

    /** Maven project name recorded as the project index title. */
    @Parameter(defaultValue = "${project.name}", readonly = true)
    private String projectName;

    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    @Override
    public void execute() throws MojoExecutionException {
        if (skip) {
            getLog().info("AI project index aggregation skipped.");
            return;
        }

        final Path outputPath = outputDirectory.toPath().toAbsolutePath().normalize();

        getLog().info("Starting AI project index aggregation");
        getLog().info("Output directory: " + outputPath);
        getLog().info("Force           : " + force);

        if (!outputPath.toFile().exists()) {
            getLog().info("AI output directory does not exist, skipping project index: " + outputPath);
            return;
        }

        final String title =
                projectName == null || compatibilityHelper.isBlank(projectName) ? DEFAULT_PROJECT_TITLE : projectName;

        try {
            final ProjectIndexer indexer = new ProjectIndexer(getLog(), title, pluginVersion, aiVersion, force);
            final int written = indexer.aggregate(outputPath);
            getLog().info("Project index files written: " + written);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to aggregate project AI index file under " + outputPath, e);
        }

        getLog().info("AI project index aggregation finished.");
    }
}
