// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.prompt;

import lombok.ToString;

/**
 * Maven plugin configuration POJO that pairs a lookup key with a prompt template string.
 *
 * <p>Fields are populated by the Maven plugin framework via reflection from the
 * configuration XML; the no-arg constructor cannot guarantee non-null initialization.
 *
 * <p>{@code toString} is generated by Lombok over both fields for build-log diagnostics.
 * {@code equals}/{@code hashCode} are intentionally NOT generated: instances are
 * managed by identity inside the plugin (registered in a key-indexed lookup) and the
 * mutable JavaBean shape makes value semantics unsafe.
 */
@SuppressWarnings({"NullAway.Init", "initialization.fields.uninitialized"})
@ToString
public class AiPromptDefinition {

    /** Creates a new {@link AiPromptDefinition}. */
    public AiPromptDefinition() {
        // no-op
    }

    private String key;
    private String template;

    /**
     * Returns the prompt template lookup key.
     *
     * @return prompt template lookup key
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the prompt template lookup key.
     *
     * @param key lookup key
     */
    public void setKey(final String key) {
        this.key = key;
    }

    /**
     * Returns the prompt template string.
     *
     * @return prompt template string
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the prompt template string.
     *
     * @param template prompt template string
     */
    public void setTemplate(final String template) {
        this.template = template;
    }
}
