// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocument;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocumentCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderSupport;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdLeadExtractor;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptSupport;
import net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider;
import net.ladenthin.maven.llamacpp.aiindex.support.AiChecksumSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiTimeSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.jspecify.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Builds the single project-level AI index — the top of the three-level index.
 *
 * <p>Walks the output tree, finds every {@link AiMdHeaderCodec#PACKAGE_AI_MD_FILENAME}, and writes
 * one {@link AiMdHeaderCodec#PROJECT_AI_MD_FILENAME} into the output root. The body lists each package
 * on a single line — its one-sentence <em>lead</em> (harvested from its already-generated body by
 * {@link AiMdLeadExtractor}) — while the header {@code F} list carries the matching clickable links to
 * each {@code package.ai.md}, mirroring the package level so navigation is uniformly in the header. The
 * result is a compact, always-loadable table of contents an agent reads first to decide which package
 * to open, instead of scanning thousands of file summaries.</p>
 *
 * <p>By default this step is fully <strong>deterministic</strong>: it harvests existing leads and never
 * calls the AI model, so it adds negligible cost and scales to projects with hundreds of packages.</p>
 *
 * <p><strong>Optional AI overview.</strong> When an overview field generation (prompt + model) is
 * supplied, one — and only one — extra AI call writes a short project overview paragraph under a
 * {@code #### Overview} heading, synthesised from the per-package leads alone (not the full package
 * bodies), so the entry document opens with a project narrative. It is opt-in: with no overview field
 * generation the behaviour is exactly the deterministic one above.</p>
 *
 * <p><strong>Incrementality.</strong> The header {@code c} checksum is the CRC32 of the deterministic
 * body (the per-package listing) <em>plus</em> the overview generation signature
 * ({@code promptKey:aiDefinitionKey}, empty when the overview is off). The AI overview text itself is
 * deliberately <em>not</em> part of the checksum, so an unchanged project is never re-inferred (the
 * paragraph stays stable across a multi-day run), yet the file regenerates when a package's lead/link/set
 * changes <em>or</em> the overview configuration changes (so enabling the overview, or switching its
 * model, triggers a rebuild) — or when {@code force} is set. This mirrors the incremental contract of
 * {@link SourceFileIndexer} and {@link PackageIndexer}.</p>
 *
 * <p>{@code toString} is generated by Lombok over the configuration and collaborator fields.</p>
 */
@ToString
public class ProjectIndexer {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProjectIndexer.class);

    /** Markdown heading introducing the per-package listing in the project index body. */
    private static final String PACKAGES_HEADING = "#### Packages";

    /** Markdown heading introducing the optional AI-generated project overview paragraph. */
    private static final String OVERVIEW_HEADING = "#### Overview";

    /** Separator placed between a package's link and its lead in a listing line. */
    private static final String LEAD_SEPARATOR = " — ";

    /** Display name used for the output-root package (whose relativised path is empty). */
    private static final String ROOT_DISPLAY = ".";

    /**
     * Context-type label passed to {@link AiFieldGenerationSupport} so that trim-warning log messages
     * read "Trimmed AI input for project field '…'".
     */
    private static final String CONTEXT_TYPE_PROJECT = "project";

    /**
     * Separator joining the overview prompt key and AI definition key into the generation signature
     * folded into the {@code c} checksum, so a change of overview prompt or model rebuilds the index.
     */
    private static final String OVERVIEW_SIGNATURE_SEPARATOR = ":";

    /** Prefix of the first line of the overview source, naming the project for the model. */
    private static final String OVERVIEW_SOURCE_TITLE_PREFIX = "Project: ";

    /** Heading of the per-package lead listing in the overview source fed to the model. */
    private static final String OVERVIEW_SOURCE_LEADS_HEADING = "Package leads (one per package):";

    /** Separator between a package path and its lead in the overview source listing. */
    private static final String OVERVIEW_SOURCE_LEAD_SEPARATOR = ": ";

    private final String projectTitle;
    private final String pluginVersion;
    private final String aiVersion;
    private final boolean force;

    /** Overview field generation (prompt + model); {@code null} disables the AI overview. */
    private final @Nullable AiFieldGenerationConfig overviewFieldGeneration;

    /** AI generation loop used for the overview; {@code null} when the overview is disabled. */
    private final @Nullable AiFieldGenerationSupport fieldGenerationSupport;

    private final AiTimeSupport timeSupport = new AiTimeSupport();
    private final AiChecksumSupport checksumSupport = new AiChecksumSupport();
    private final AiMdHeaderSupport headerSupport = new AiMdHeaderSupport();
    private final AiMdDocumentCodec documentCodec = new AiMdDocumentCodec();
    private final AiMdLeadExtractor leadExtractor = new AiMdLeadExtractor();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Creates a deterministic {@link ProjectIndexer} with no AI overview.
     *
     * @param projectTitle  title recorded in the project index header (typically the Maven project name)
     * @param pluginVersion plugin version recorded in the header
     * @param aiVersion     AI summarisation logic version recorded in the header
     * @param force         when {@code true}, rewrite the project index even when it is unchanged
     */
    public ProjectIndexer(
            final String projectTitle, final String pluginVersion, final String aiVersion, final boolean force) {
        this(projectTitle, pluginVersion, aiVersion, force, null, null, null, null);
    }

    /**
     * Creates a {@link ProjectIndexer} that optionally generates an AI project overview.
     *
     * <p>The overview is enabled only when {@code generationProvider}, {@code overviewFieldGeneration},
     * {@code promptSupport}, and {@code modelDefinitionSupport} are all non-{@code null}; otherwise the
     * indexer behaves exactly like the deterministic constructor above.</p>
     *
     * @param projectTitle            title recorded in the project index header
     * @param pluginVersion           plugin version recorded in the header
     * @param aiVersion               AI summarisation logic version recorded in the header
     * @param force                   when {@code true}, rewrite the project index even when unchanged
     * @param generationProvider      AI provider for the overview; {@code null} disables it
     * @param overviewFieldGeneration overview prompt + model; {@code null} disables it
     * @param promptSupport           prompt lookup; {@code null} disables the overview
     * @param modelDefinitionSupport  AI model definition lookup; {@code null} disables the overview
     */
    public ProjectIndexer(
            final String projectTitle,
            final String pluginVersion,
            final String aiVersion,
            final boolean force,
            final @Nullable AiGenerationProvider generationProvider,
            final @Nullable AiFieldGenerationConfig overviewFieldGeneration,
            final @Nullable AiPromptSupport promptSupport,
            final @Nullable AiModelDefinitionSupport modelDefinitionSupport) {
        this.projectTitle = projectTitle;
        this.pluginVersion = pluginVersion;
        this.aiVersion = aiVersion;
        this.force = force;
        // Defensive copy: the field generation is a mutable Maven JavaBean owned by the caller.
        this.overviewFieldGeneration = copyFieldGeneration(overviewFieldGeneration);
        if (generationProvider != null
                && overviewFieldGeneration != null
                && promptSupport != null
                && modelDefinitionSupport != null) {
            this.fieldGenerationSupport = new AiFieldGenerationSupport(
                    generationProvider, new AiPromptPreparationSupport(promptSupport), modelDefinitionSupport);
        } else {
            this.fieldGenerationSupport = null;
        }
    }

    /**
     * Returns a defensive copy of {@code source}, or {@code null} when {@code source} is {@code null}.
     * The overview field generation is a mutable Maven {@link AiFieldGenerationConfig} JavaBean owned
     * by the caller; copying it prevents external mutation after construction.
     *
     * @param source the caller-supplied field generation, or {@code null}
     * @return an independent copy, or {@code null}
     */
    private static @Nullable AiFieldGenerationConfig copyFieldGeneration(
            final @Nullable AiFieldGenerationConfig source) {
        if (source == null) {
            return null;
        }
        final AiFieldGenerationConfig copy = new AiFieldGenerationConfig();
        copy.setPromptKey(source.getPromptKey());
        copy.setAiDefinitionKey(source.getAiDefinitionKey());
        // The project-overview generation uses a single field generation; per-file routing fields
        // (condition/priority/skip/fallback) do not apply, so only prompt + model are copied.
        return copy;
    }

    /**
     * Aggregates every package index beneath {@code rootDirectory} into a single project index file.
     *
     * @param rootDirectory output root directory to walk for {@code package.ai.md} files
     * @return {@code 1} if the project index file was written or refreshed, {@code 0} if there were
     *         no package index files or the existing file was already up to date
     * @throws IOException if the output tree cannot be read or the project index cannot be written
     */
    public int aggregate(final Path rootDirectory) throws IOException {
        final List<Path> packageFiles;
        try (Stream<Path> stream = Files.walk(rootDirectory)) {
            packageFiles = compatibilityHelper.toList(
                    stream.filter(path -> Files.isRegularFile(path) && isPackageAiMdFile(path)));
        }

        if (packageFiles.isEmpty()) {
            LOGGER.info("No package index files found under {}; skipping project index.", rootDirectory);
            return 0;
        }

        final List<PackageEntry> entries = new ArrayList<>(packageFiles.size());
        String latestDate = AiTimeSupport.EPOCH_DATE;
        for (final Path packageFile : packageFiles) {
            final AiMdDocument document = documentCodec.read(packageFile);
            final String displayPath = displayPath(rootDirectory, packageFile);
            final String link = linkPath(rootDirectory, packageFile);
            final String lead = leadExtractor.extractLead(document.body());
            entries.add(new PackageEntry(displayPath, link, lead));
            latestDate = laterDate(latestDate, document.header().d());
        }
        entries.sort(Comparator.comparing(PackageEntry::link));

        final List<String> packageLinks = new ArrayList<>(entries.size());
        for (final PackageEntry entry : entries) {
            packageLinks.add(markdownLink(entry.displayPath(), entry.link()));
        }

        final String leadLine = buildLeadLine();
        final String packagesSection = buildPackagesSection(entries);
        final String deterministicBody = leadLine + "\n\n" + packagesSection;

        // The overview generation signature (empty when off) is folded into the checksum so the
        // index rebuilds when the overview prompt/model changes — but the AI output is not, so an
        // unchanged project is never re-inferred. The same (overview != null && support != null) guard
        // gates both the signature and the generation below, so the two stay consistent.
        final AiFieldGenerationConfig overview = this.overviewFieldGeneration;
        final AiFieldGenerationSupport support = this.fieldGenerationSupport;
        final String signature;
        if (overview != null && support != null) {
            signature = overview.getPromptKey() + OVERVIEW_SIGNATURE_SEPARATOR + overview.getAiDefinitionKey();
        } else {
            signature = "";
        }
        final String checksum = checksumSupport.calculateCrc32Hex(deterministicBody + signature);
        final String generatedAt = timeSupport.formatInstant(java.time.Instant.now());

        final AiMdHeader baseHeader = new AiMdHeader(
                projectTitle,
                AiMdHeaderCodec.HEADER_VERSION_1_0,
                checksum,
                latestDate,
                generatedAt,
                pluginVersion,
                aiVersion,
                AiMdHeaderCodec.NODE_TYPE_PROJECT,
                packageLinks);

        final Path projectFile = rootDirectory.resolve(AiMdHeaderCodec.PROJECT_AI_MD_FILENAME);

        if (!headerSupport.shouldWrite(force, projectFile, baseHeader)) {
            LOGGER.info("Unchanged project index file: {}", projectFile);
            return 0;
        }

        final String body;
        if (overview != null && support != null) {
            final String overviewText = generateOverview(support, overview, projectFile, entries, baseHeader);
            body = compatibilityHelper.isBlank(overviewText)
                    ? deterministicBody
                    : leadLine + "\n\n" + OVERVIEW_HEADING + "\n" + overviewText.trim() + "\n\n" + packagesSection;
        } else {
            body = deterministicBody;
        }

        documentCodec.write(projectFile, new AiMdDocument(baseHeader, body));
        LOGGER.info("Wrote project index file: {} ({} packages)", projectFile, entries.size());
        return 1;
    }

    /**
     * Returns {@code true} when {@code path}'s file name is the package index file name.
     *
     * @param path candidate path encountered during the output-tree walk
     * @return {@code true} if {@code path} is a {@code package.ai.md} file
     */
    private boolean isPackageAiMdFile(final Path path) {
        final Path fileName = path.getFileName();
        return fileName != null && AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME.equals(fileName.toString());
    }

    /**
     * Returns the deterministic blockquote lead line that opens the project index body. Kept stable
     * (never AI-generated) so any tooling that harvests the project lead reads a predictable sentence.
     *
     * @return the blockquote lead line (no trailing newline)
     */
    private String buildLeadLine() {
        return AiMdLeadExtractor.BLOCKQUOTE_MARKER + " Project index of " + projectTitle
                + ": one line per package; leads here, clickable links in the header F list.";
    }

    /**
     * Renders the deterministic per-package listing section: the {@value #PACKAGES_HEADING} heading
     * followed by one line per package ({@code - <display> — <lead>}; the lead and its separator are
     * omitted when the package has no lead). The clickable links live in the header {@code F} list, not
     * the body, so the body stays compact at hundreds of packages.
     *
     * @param entries package entries, already sorted by link
     * @return the rendered packages section (ends with a newline)
     */
    private String buildPackagesSection(final List<PackageEntry> entries) {
        final StringBuilder builder = new StringBuilder();
        builder.append(PACKAGES_HEADING).append('\n');
        for (final PackageEntry entry : entries) {
            builder.append("- ").append(entry.displayPath());
            if (!compatibilityHelper.isBlank(entry.lead())) {
                builder.append(LEAD_SEPARATOR).append(entry.lead());
            }
            builder.append('\n');
        }
        return builder.toString();
    }

    /**
     * Generates the AI overview paragraph from the per-package leads via {@link AiFieldGenerationSupport}
     * (which handles trimming, retries, and empty-output warnings). The model receives only the project
     * title and the one-line package leads, never the full package bodies, keeping the input compact.
     *
     * @param support     the AI generation loop (non-null)
     * @param overview    the overview field generation (non-null)
     * @param projectFile the project index file path, used as the request context file
     * @param entries     the harvested package entries
     * @param baseHeader  the project index header passed through to the generation request
     * @return the generated overview text (possibly blank if the model produced nothing)
     * @throws IOException if the AI provider throws during generation
     */
    private String generateOverview(
            final AiFieldGenerationSupport support,
            final AiFieldGenerationConfig overview,
            final Path projectFile,
            final List<PackageEntry> entries,
            final AiMdHeader baseHeader)
            throws IOException {
        final String overviewSource = buildOverviewSource(entries);
        final AiGenerationResult result = support.processFieldGenerations(
                Collections.singletonList(overview), projectFile, CONTEXT_TYPE_PROJECT, overviewSource, baseHeader);
        return result.body();
    }

    /**
     * Builds the source text fed to the overview model: the project title followed by the one-line lead
     * of every package. Packages without a lead contribute their path alone.
     *
     * @param entries the harvested package entries, already sorted
     * @return the overview source text
     */
    private String buildOverviewSource(final List<PackageEntry> entries) {
        final StringBuilder builder = new StringBuilder();
        builder.append(OVERVIEW_SOURCE_TITLE_PREFIX)
                .append(projectTitle)
                .append('\n')
                .append('\n');
        builder.append(OVERVIEW_SOURCE_LEADS_HEADING).append('\n');
        for (final PackageEntry entry : entries) {
            builder.append("- ").append(entry.displayPath());
            if (!compatibilityHelper.isBlank(entry.lead())) {
                builder.append(OVERVIEW_SOURCE_LEAD_SEPARATOR).append(entry.lead());
            }
            builder.append('\n');
        }
        return builder.toString();
    }

    /**
     * Formats a markdown link {@code [label](target)} for the header {@code F} child-link list.
     *
     * @param label  link label (the package display path)
     * @param target link target (the relative path to the package's {@code package.ai.md})
     * @return the markdown link string
     */
    private String markdownLink(final String label, final String target) {
        return "[" + label + "](" + target + ")";
    }

    /**
     * Returns the display name for the package owning {@code packageFile}: its directory relativised
     * against {@code rootDirectory} with forward slashes, or {@value #ROOT_DISPLAY} for the
     * output-root package whose relativised path is empty.
     *
     * @param rootDirectory output root directory
     * @param packageFile   a {@code package.ai.md} file
     * @return the display path for the package
     */
    private String displayPath(final Path rootDirectory, final Path packageFile) {
        final Path packageDir = packageFile.getParent();
        if (packageDir == null) {
            return ROOT_DISPLAY;
        }
        final String relative = rootDirectory.relativize(packageDir).toString().replace('\\', '/');
        return relative.isEmpty() ? ROOT_DISPLAY : relative;
    }

    /**
     * Returns the relative link from the project index (written in {@code rootDirectory}) to
     * {@code packageFile}, using forward slashes.
     *
     * @param rootDirectory output root directory
     * @param packageFile   a {@code package.ai.md} file
     * @return the relative link string
     */
    private String linkPath(final Path rootDirectory, final Path packageFile) {
        return rootDirectory.relativize(packageFile).toString().replace('\\', '/');
    }

    /**
     * Returns the lexicographically later of two ISO-8601 date strings, i.e. the more-recent
     * creation date.
     *
     * @param current   the currently known latest date
     * @param candidate a date from a package node to compare against {@code current}
     * @return {@code candidate} if it is strictly later than {@code current}, otherwise {@code current}
     */
    private String laterDate(final String current, final String candidate) {
        return candidate.compareTo(current) > 0 ? candidate : current;
    }

    /** Immutable carrier for one package's display path, relative link, and harvested lead. */
    private static final class PackageEntry {
        private final String displayPath;
        private final String link;
        private final String lead;

        PackageEntry(final String displayPath, final String link, final String lead) {
            this.displayPath = displayPath;
            this.link = link;
            this.lead = lead;
        }

        String displayPath() {
            return displayPath;
        }

        String link() {
            return link;
        }

        String lead() {
            return lead;
        }
    }
}
