// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationRequest;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPreparedPrompt;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport;
import net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider;
import net.ladenthin.maven.llamacpp.aiindex.support.AiGenerationTimeEstimator;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.logging.Log;

/**
 * Shared field-generation logic used by both {@link SourceFileIndexer} and
 * {@link PackageIndexer}.
 *
 * <p>Iterates over a list of {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig} entries, prepares the
 * prompt for each, delegates generation to the configured {@link net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider},
 * and accumulates the generated text as the document body.
 * A trim warning is emitted via the supplied {@link Log} whenever the source text had
 * to be truncated to fit within the configured maximum input character budget.</p>
 *
 * <p>{@code toString} is generated by Lombok over the collaborator fields and the
 * maxInputChars cache. The Maven {@link Log} is excluded because its default
 * {@code toString} prints implementation details (logger configuration, output stream
 * state) that are noisy and not useful for build-log diagnostics.
 */
@ToString
public class AiFieldGenerationSupport {

    /**
     * Log message fragment inserted between the context type and the remainder of the
     * trim-warning message, ensuring a consistent sentence structure regardless of whether
     * the context is a file or a package.
     *
     * @see #processFieldGenerations
     */
    private static final String TRIM_WARN_FIELD_LABEL = " field '";

    /**
     * Log message prefix for warnings emitted when the AI provider returns an empty body
     * for a given field, ensuring a consistent sentence structure regardless of context type.
     * An empty response typically indicates that the model produced an EOS token immediately,
     * which can occur at low sampling temperatures for certain input patterns.
     *
     * @see #processFieldGenerations
     */
    private static final String EMPTY_OUTPUT_WARN_PREFIX = "AI provider returned empty body for ";

    /**
     * Separator used to construct the cache key for the computed {@code maxInputChars}
     * per {@code (aiDefinitionKey, promptKey)} pair.
     *
     * @see #computeMaxInputCharsKey
     */
    private static final String CACHE_KEY_SEPARATOR = ":";

    /** Bytes per kibibyte, used to render the source size in the per-file processing log. */
    private static final int KIBIBYTES_DIVISOR = 1024;

    /** Size label used in the processing log line for sources smaller than one kibibyte. */
    private static final String SIZE_BELOW_ONE_KIB_LABEL = "<1";

    /** Prefix of the per-file processing/ETA log line. */
    private static final String PROCESSING_LOG_PREFIX = "Processing ";

    /** Infix introducing the estimated source size in the processing log line. */
    private static final String PROCESSING_LOG_SIZE_INFIX = " (";

    /** Unit/infix for the source size and token estimate in the processing log line. */
    private static final String PROCESSING_LOG_TOKENS_INFIX = " KB source, ~";

    /** Infix introducing the estimated duration in the processing log line. ASCII-only for CI logs. */
    private static final String PROCESSING_LOG_ETA_INFIX = " tokens) - estimated ";

    /**
     * Suffix on the processing log line stressing that the duration is a rough,
     * hardware-specific estimate (see {@link AiGenerationTimeEstimator}). ASCII-only for CI logs.
     */
    private static final String PROCESSING_LOG_DISCLAIMER =
            " (rough; calibrated on reference CPU + gpt-oss-20b - actual depends on your hardware)";

    /** Prefix of the per-file actual-duration log line emitted after generation completes. */
    private static final String GENERATED_LOG_PREFIX = "Generated ";

    /** Infix between the file path and the measured wall-clock duration in the actual-duration line. */
    private static final String GENERATED_LOG_IN_INFIX = "' in ";

    /**
     * Infix introducing the estimate for side-by-side comparison in the actual-duration line, so a real
     * run shows measured-vs-estimated per file (lets you compare models/quants in live runs without a
     * separate benchmark). ASCII-only for CI logs.
     */
    private static final String GENERATED_LOG_ACTUAL_INFIX = " (actual; estimated ";

    /** Suffix closing the actual-duration log line. */
    private static final String GENERATED_LOG_SUFFIX = ")";

    /** Nanoseconds per second, used to convert the measured generation duration to whole seconds. */
    private static final long NANOS_PER_SECOND = 1_000_000_000L;

    // Maven plugin Log — its default toString prints implementation details
    // (logger configuration, output stream state); excluded from the rendered output.
    @ToString.Exclude
    private final Log log;

    private final AiGenerationProvider generationProvider;
    private final AiPromptPreparationSupport promptPreparationSupport;
    private final AiModelDefinitionSupport modelDefinitionSupport;
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();
    private final AiGenerationTimeEstimator timeEstimator = new AiGenerationTimeEstimator();

    /**
     * Per-{@code (aiDefinitionKey, promptKey)} cache of the computed {@code maxInputChars}
     * value. Populated on first use so that the calculation and its detailed log output
     * are emitted exactly once per unique pair rather than once per processed file.
     */
    private final Map<String, Integer> maxInputCharsCache = new HashMap<>();

    /**
     * Creates a new {@code AiFieldGenerationSupport}.
     *
     * @param log                      Maven logger for trim warnings and diagnostics
     * @param generationProvider       AI backend used to generate text for each field
     * @param promptPreparationSupport helper that resolves and prepares prompt templates
     * @param modelDefinitionSupport   lookup for {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig} by key
     */
    public AiFieldGenerationSupport(
            final Log log,
            final AiGenerationProvider generationProvider,
            final AiPromptPreparationSupport promptPreparationSupport,
            final AiModelDefinitionSupport modelDefinitionSupport) {
        this.log = log;
        this.generationProvider = generationProvider;
        this.promptPreparationSupport = promptPreparationSupport;
        this.modelDefinitionSupport = modelDefinitionSupport;
    }

    /**
     * Processes each entry in {@code fieldGenerations}, generates the requested AI text,
     * and accumulates the results into an {@link net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult}.
     *
     * <p>For each non-null {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig}:</p>
     * <ol>
     *   <li>The prompt is prepared via {@link net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport#preparePrompt}.</li>
     *   <li>A trim warning is logged if the source was truncated and
     *       {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig#isWarnOnTrim()} is {@code true}.</li>
     *   <li>The AI provider generates a value for the trimmed source.</li>
     *   <li>If the provider returns a blank body, a single warning is emitted (fail-fast).
     *       Blank output no longer occurs in normal operation with a non-greedy temperature
     *       and an adequate output budget; the previous escalating-temperature retry loop was
     *       removed after it was shown to waste full generations re-inferring to the same empty
     *       result (see {@code docs/ai-index-benchmark/gpt-oss-tuning.md}, E2).</li>
     *   <li>The generated value is stored as the document body.</li>
     * </ol>
     *
     * @param fieldGenerations per-field generation configuration list; {@code null} entries
     *                         are silently skipped
     * @param contextFile      path to the source or package file being processed; used in
     *                         prompt requests and log messages
     * @param contextType      human-readable label for the context (e.g. {@code "file"} or
     *                         {@code "package"}); embedded in trim-warning log messages
     * @param sourceText       full source text passed as input to the prompt preparation step
     * @param baseHeader       current header; passed through to each
     *                         {@link net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationRequest}
     * @return an {@link net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult} with the generated body; defaults to empty string
     * @throws IOException              if the AI provider throws during generation
     * @throws IllegalArgumentException if a field's {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig#getAiDefinitionKey()}
     *                                  does not match any registered {@link net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinition}
     */
    public AiGenerationResult processFieldGenerations(
            final List<AiFieldGenerationConfig> fieldGenerations,
            final Path contextFile,
            final String contextType,
            final String sourceText,
            final AiMdHeader baseHeader)
            throws IOException {
        String body = "";

        for (AiFieldGenerationConfig fieldGeneration : fieldGenerations) {
            if (fieldGeneration == null) {
                continue;
            }

            final AiGenerationConfig generationConfig =
                    modelDefinitionSupport.getConfig(fieldGeneration.getAiDefinitionKey());

            final int effectiveMaxInputChars = resolveMaxInputChars(fieldGeneration, generationConfig, contextFile);

            final AiGenerationRequest request =
                    new AiGenerationRequest(fieldGeneration.getPromptKey(), contextFile, sourceText, baseHeader);

            final AiPreparedPrompt preparedPrompt =
                    promptPreparationSupport.preparePrompt(request, effectiveMaxInputChars);

            if (preparedPrompt.trimmed() && generationConfig.isWarnOnTrim()) {
                log.warn("Trimmed AI input for " + contextType + TRIM_WARN_FIELD_LABEL + "body': " + contextFile
                        + " (source chars " + preparedPrompt.originalSourceLength()
                        + " -> " + preparedPrompt.trimmedSourceLength()
                        + ", available source chars " + preparedPrompt.availableSourceChars()
                        + ", max input chars " + effectiveMaxInputChars + ")");
            }

            final AiGenerationRequest generationRequest = new AiGenerationRequest(
                    fieldGeneration.getPromptKey(), contextFile, preparedPrompt.sourceText(), baseHeader);

            final int processedSourceChars = preparedPrompt.sourceText().length();
            final String sourceSizeKb = sourceText.length() < KIBIBYTES_DIVISOR
                    ? SIZE_BELOW_ONE_KIB_LABEL
                    : Integer.toString(sourceText.length() / KIBIBYTES_DIVISOR);
            final long estimatedSeconds = timeEstimator.estimateSeconds(processedSourceChars);
            log.info(PROCESSING_LOG_PREFIX + contextType + " '" + contextFile + "'"
                    + PROCESSING_LOG_SIZE_INFIX + sourceSizeKb
                    + PROCESSING_LOG_TOKENS_INFIX + timeEstimator.estimatePromptTokens(processedSourceChars)
                    + PROCESSING_LOG_ETA_INFIX
                    + timeEstimator.formatDuration(estimatedSeconds)
                    + PROCESSING_LOG_DISCLAIMER);

            log.info("Generating field '" + fieldGeneration.getPromptKey() + "' with temperature="
                    + generationConfig.getTemperature() + ", maxInputChars="
                    + effectiveMaxInputChars);
            final long generationStartNanos = System.nanoTime();
            body = generationProvider.generate(generationRequest);
            final long actualSeconds = (System.nanoTime() - generationStartNanos) / NANOS_PER_SECOND;

            // Log the MEASURED wall-clock duration next to the estimate so real runs are directly
            // comparable across models/quants without a separate benchmark harness.
            log.info(GENERATED_LOG_PREFIX + contextType + " '" + contextFile + GENERATED_LOG_IN_INFIX
                    + timeEstimator.formatDuration(actualSeconds) + GENERATED_LOG_ACTUAL_INFIX
                    + timeEstimator.formatDuration(estimatedSeconds) + GENERATED_LOG_SUFFIX);

            if (compatibilityHelper.isBlank(body)) {
                log.warn(EMPTY_OUTPUT_WARN_PREFIX + contextType + TRIM_WARN_FIELD_LABEL + fieldGeneration.getPromptKey()
                        + "': " + contextFile);
            }
        }

        return new AiGenerationResult(body);
    }

    /**
     * Returns the effective {@code maxInputChars} for the given field generation entry.
     *
     * <p>When the {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig#getCharsPerToken()} value is greater than zero,
     * the maximum is computed once per unique {@code (aiDefinitionKey, promptKey)} pair,
     * logged in detail, cached, and reused for all subsequent files. When
     * {@code charsPerToken} is zero, the static {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig#getMaxInputChars()}
     * fallback is returned instead.</p>
     *
     * @param fieldGeneration  the field configuration identifying the definition and prompt keys
     * @param generationConfig the resolved generation config carrying {@code charsPerToken} etc.
     * @param contextFile      a representative file path used to render the base prompt length
     * @return effective maximum input characters for this field generation step
     */
    private int resolveMaxInputChars(
            final AiFieldGenerationConfig fieldGeneration,
            final AiGenerationConfig generationConfig,
            final Path contextFile) {
        if (generationConfig.getCharsPerToken() <= 0) {
            return generationConfig.getMaxInputChars();
        }

        final String cacheKey =
                computeMaxInputCharsKey(fieldGeneration.getAiDefinitionKey(), fieldGeneration.getPromptKey());
        final Integer cached = maxInputCharsCache.get(cacheKey);
        if (cached != null) {
            return cached;
        }

        final int basePromptLength =
                promptPreparationSupport.getBasePromptLength(fieldGeneration.getPromptKey(), contextFile);
        final int computed = calculateAndLogMaxInputChars(generationConfig, basePromptLength);
        maxInputCharsCache.put(cacheKey, computed);
        return computed;
    }

    /**
     * Computes and logs the detailed {@code maxInputChars} calculation for a given
     * generation config and base prompt length.
     *
     * <p>The formula is:</p>
     * <pre>
     *   totalChars     = contextSize × charsPerToken
     *   overheadTotal  = promptChars + eofChars + (maxOutputTokens × charsPerToken) + safetyChars
     *   availableChars = totalChars - overheadTotal
     *   finalChars     = floor(availableChars / 100) × 100   (rounded down conservatively)
     * </pre>
     *
     * <p>All intermediate values are emitted at INFO level so that the calculation is
     * transparent and reproducible from the build log alone.</p>
     *
     * @param config          the resolved generation config supplying {@code contextSize},
     *                        {@code maxOutputTokens}, and {@code charsPerToken}
     * @param basePromptLength character length of the prompt template rendered with empty source
     * @return final (rounded) maximum input character count
     */
    private int calculateAndLogMaxInputChars(final AiGenerationConfig config, final int basePromptLength) {
        final int contextSize = config.getContextSize();
        final int charsPerToken = config.getCharsPerToken();
        final int maxOutputTokens = config.getMaxOutputTokens();

        final int totalChars = contextSize * charsPerToken;
        final int promptChars = basePromptLength;
        final int eofChars = AiPromptPreparationSupport.EOF_MARKER_LENGTH;
        final int outputChars = maxOutputTokens * charsPerToken;
        final int safetyChars = AiGenerationConfig.DEFAULT_SAFETY_MARGIN_CHARS;
        final int overheadTotal = promptChars + eofChars + outputChars + safetyChars;
        final int availableChars = totalChars - overheadTotal;
        // Single source of truth for the threshold shared with the planning path (SourceFileIndexer.classify).
        final int finalChars = AiInputWindowCalculator.maxInputChars(config, basePromptLength);

        log.info("Maximum input characters for source code before trimming. Calculated as: (context_size x "
                + charsPerToken + ") - overhead");
        log.info("  Context: " + contextSize + " tokens");
        log.info("  Chars per token: ~" + charsPerToken);
        log.info("  [Total available]: " + contextSize + " x " + charsPerToken + " = " + totalChars + " chars");
        log.info("  Overhead (conservative estimate):");
        log.info("  - Prompt template: ~" + promptChars + " chars");
        log.info("  - EOF marker: ~" + eofChars + " chars");
        log.info("  - Max output (" + maxOutputTokens + " tokens x " + charsPerToken + "): ~" + outputChars + " chars");
        log.info("  - Safety margin: ~" + safetyChars + " chars");
        log.info("  - [Subtotal overhead]: ~" + overheadTotal + " chars");
        log.info("  Available for source: [Total available] - [Subtotal overhead]");
        log.info("  Available for source: " + totalChars + " - " + overheadTotal + " = " + availableChars + " chars");
        log.info("  Set to: " + finalChars + " (rounded, conservative)");

        return finalChars;
    }

    /**
     * Builds the cache key for the computed {@code maxInputChars} per
     * {@code (aiDefinitionKey, promptKey)} pair.
     *
     * @param aiDefinitionKey the AI model definition key
     * @param promptKey       the prompt template key
     * @return a unique composite cache key
     */
    private String computeMaxInputCharsKey(final String aiDefinitionKey, final String promptKey) {
        return aiDefinitionKey + CACHE_KEY_SEPARATOR + promptKey;
    }
}
