// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiCalibration;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFactExtractor;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.config.AiOversizeStrategy;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationRequest;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPreparedPrompt;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport;
import net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider;
import net.ladenthin.maven.llamacpp.aiindex.support.AiDeterministicSummary;
import net.ladenthin.maven.llamacpp.aiindex.support.AiGenerationTimeEstimator;
import net.ladenthin.maven.llamacpp.aiindex.support.AiSourceChunker;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.logging.Log;

/**
 * Shared field-generation logic used by both {@link SourceFileIndexer} and
 * {@link PackageIndexer}.
 *
 * <p>Iterates over a list of {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig} entries, prepares the
 * prompt for each, delegates generation to the configured {@link net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider},
 * and accumulates the generated text as the document body.
 * A trim warning is emitted via the supplied {@link Log} whenever the source text had
 * to be truncated to fit within the configured maximum input character budget.</p>
 *
 * <p>{@code toString} is generated by Lombok over the collaborator fields and the
 * maxInputChars cache. The Maven {@link Log} is excluded because its default
 * {@code toString} prints implementation details (logger configuration, output stream
 * state) that are noisy and not useful for build-log diagnostics.
 */
@ToString
public class AiFieldGenerationSupport {

    /**
     * Log message fragment inserted between the context type and the remainder of the
     * trim-warning message, ensuring a consistent sentence structure regardless of whether
     * the context is a file or a package.
     *
     * @see #processFieldGenerations
     */
    private static final String TRIM_WARN_FIELD_LABEL = " field '";

    /**
     * Log message prefix for warnings emitted when the AI provider returns an empty body
     * for a given field, ensuring a consistent sentence structure regardless of context type.
     * An empty response typically indicates that the model produced an EOS token immediately,
     * which can occur at low sampling temperatures for certain input patterns.
     *
     * @see #processFieldGenerations
     */
    private static final String EMPTY_OUTPUT_WARN_PREFIX = "AI provider returned empty body for ";

    /**
     * Separator used to construct the cache key for the computed {@code maxInputChars}
     * per {@code (aiDefinitionKey, promptKey)} pair.
     *
     * @see #computeMaxInputCharsKey
     */
    private static final String CACHE_KEY_SEPARATOR = ":";

    /** Bytes per kibibyte, used to render the source size in the per-file processing log. */
    private static final int KIBIBYTES_DIVISOR = 1024;

    /** Size label used in the processing log line for sources smaller than one kibibyte. */
    private static final String SIZE_BELOW_ONE_KIB_LABEL = "<1";

    /** Prefix of the per-file processing/ETA log line. */
    private static final String PROCESSING_LOG_PREFIX = "Processing ";

    /** Infix introducing the estimated source size in the processing log line. */
    private static final String PROCESSING_LOG_SIZE_INFIX = " (";

    /** Unit/infix for the source size and token estimate in the processing log line. */
    private static final String PROCESSING_LOG_TOKENS_INFIX = " KB source, ~";

    /** Infix introducing the estimated duration in the processing log line. ASCII-only for CI logs. */
    private static final String PROCESSING_LOG_ETA_INFIX = " tokens) - estimated ";

    /**
     * Suffix on the processing log line stressing that the duration is a rough,
     * hardware-specific estimate (see {@link AiGenerationTimeEstimator}). ASCII-only for CI logs.
     */
    private static final String PROCESSING_LOG_DISCLAIMER =
            " (rough; calibrated on reference CPU + gpt-oss-20b - actual depends on your hardware)";

    /** Prefix of the per-file actual-duration log line emitted after generation completes. */
    private static final String GENERATED_LOG_PREFIX = "Generated ";

    /** Infix between the file path and the measured wall-clock duration in the actual-duration line. */
    private static final String GENERATED_LOG_IN_INFIX = "' in ";

    /**
     * Infix introducing the estimate for side-by-side comparison in the actual-duration line, so a real
     * run shows measured-vs-estimated per file (lets you compare models/quants in live runs without a
     * separate benchmark). ASCII-only for CI logs.
     */
    private static final String GENERATED_LOG_ACTUAL_INFIX = " (actual; estimated ";

    /** Suffix closing the actual-duration log line. */
    private static final String GENERATED_LOG_SUFFIX = ")";

    /** Nanoseconds per second, used to convert the measured generation duration to whole seconds. */
    private static final long NANOS_PER_SECOND = 1_000_000_000L;

    /** Leading/trailing lines shown in a {@link AiOversizeStrategy#DETERMINISTIC} body. */
    private static final int DETERMINISTIC_SAMPLE_LINES = 20;

    /** Upper bound on the character overlap between map-reduce chunks. */
    private static final int MAP_REDUCE_OVERLAP_CHARS = 2000;

    /** Fraction (1/n) of the chunk size used as overlap when smaller than {@link #MAP_REDUCE_OVERLAP_CHARS}. */
    private static final int MAP_REDUCE_OVERLAP_DIVISOR = 20;

    /** Minimum per-chunk source budget, so a tiny window never yields zero-length chunks. */
    private static final int MIN_CHUNK_CHARS = 1000;

    /**
     * Safety headroom (percent) subtracted from the map-reduce window before sizing chunks and reduce
     * batches. {@code charsPerToken} is only an <em>estimate</em>; token-dense content (e.g. SQL with
     * many digits/punctuation, ~2.8 chars/token) tokenizes to more tokens than a char budget computed
     * from a higher {@code charsPerToken} assumes, which would otherwise let a chunk overflow the model's
     * context window at run time (the native layer then rejects the request). Shrinking the map-reduce
     * window by this margin keeps chunks safely inside the window even when real density is up to this
     * percent below the configured {@code charsPerToken}.
     */
    private static final int MAP_REDUCE_TOKEN_HEADROOM_PERCENT = 20;

    /**
     * Maximum number of partial summaries combined into a single reduce call. Bounds the reduce prompt
     * size and guarantees the hierarchical reduce makes progress (fan-in {@code >= 2}) so it terminates.
     */
    private static final int MAX_REDUCE_FANIN = 16;

    /** Label prefix for one partial summary inside a reduce prompt. */
    private static final String REDUCE_PART_LABEL = "Part ";

    /** Approximate per-partial label + separator overhead when packing a reduce batch to the window. */
    private static final int REDUCE_LABEL_OVERHEAD_CHARS = 16;

    /** Percent divisor used when applying {@link #MAP_REDUCE_TOKEN_HEADROOM_PERCENT}. */
    private static final int PERCENT = 100;

    /**
     * Maximum number of times a single generation is retried with a smaller window after the provider
     * rejects the prompt for exceeding the model's context. The char-based window is an estimate; on
     * token-dense content that estimate can undershoot even outside map-reduce (e.g. a dense file that
     * just "fits", or a {@code sample} head), so this is the last-resort safety net for the single-shot
     * path — it degrades gracefully (trims a little more) instead of failing the whole build.
     */
    private static final int MAX_OVERFLOW_RETRIES = 3;

    /** Window multiplier (percent) applied on each context-overflow retry, shrinking the prompt. */
    private static final int OVERFLOW_RETRY_BACKOFF_PERCENT = 75;

    /**
     * Substring identifying a context-overflow error in the provider's exception message chain
     * (llama.cpp: "request (N tokens) exceeds the available context size (M tokens)…"). Matched on the
     * message rather than a binding-specific exception type to keep the indexer decoupled from the JNI
     * binding.
     */
    private static final String CONTEXT_OVERFLOW_MARKER = "exceeds the available context size";

    // Maven plugin Log — its default toString prints implementation details
    // (logger configuration, output stream state); excluded from the rendered output.
    @ToString.Exclude
    private final Log log;

    private final AiGenerationProvider generationProvider;
    private final AiPromptPreparationSupport promptPreparationSupport;
    private final AiModelDefinitionSupport modelDefinitionSupport;
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();
    private final AiGenerationTimeEstimator timeEstimator = new AiGenerationTimeEstimator();

    /**
     * Per-{@code (aiDefinitionKey, promptKey)} cache of the computed {@code maxInputChars}
     * value. Populated on first use so that the calculation and its detailed log output
     * are emitted exactly once per unique pair rather than once per processed file.
     */
    private final Map<String, Integer> maxInputCharsCache = new HashMap<>();

    /**
     * Creates a new {@code AiFieldGenerationSupport}.
     *
     * @param log                      Maven logger for trim warnings and diagnostics
     * @param generationProvider       AI backend used to generate text for each field
     * @param promptPreparationSupport helper that resolves and prepares prompt templates
     * @param modelDefinitionSupport   lookup for {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig} by key
     */
    public AiFieldGenerationSupport(
            final Log log,
            final AiGenerationProvider generationProvider,
            final AiPromptPreparationSupport promptPreparationSupport,
            final AiModelDefinitionSupport modelDefinitionSupport) {
        this.log = log;
        this.generationProvider = generationProvider;
        this.promptPreparationSupport = promptPreparationSupport;
        this.modelDefinitionSupport = modelDefinitionSupport;
    }

    /**
     * Processes each entry in {@code fieldGenerations}, generates the requested AI text,
     * and accumulates the results into an {@link net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult}.
     *
     * <p>For each non-null {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig}:</p>
     * <ol>
     *   <li>The prompt is prepared via {@link net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport#preparePrompt}.</li>
     *   <li>A trim warning is logged if the source was truncated and
     *       {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig#isWarnOnTrim()} is {@code true}.</li>
     *   <li>The AI provider generates a value for the trimmed source.</li>
     *   <li>If the provider returns a blank body, a single warning is emitted (fail-fast).
     *       Blank output no longer occurs in normal operation with a non-greedy temperature
     *       and an adequate output budget; the previous escalating-temperature retry loop was
     *       removed after it was shown to waste full generations re-inferring to the same empty
     *       result (see {@code docs/ai-index-benchmark/gpt-oss-tuning.md}, E2).</li>
     *   <li>The generated value is stored as the document body.</li>
     * </ol>
     *
     * @param fieldGenerations per-field generation configuration list; {@code null} entries
     *                         are silently skipped
     * @param contextFile      path to the source or package file being processed; used in
     *                         prompt requests and log messages
     * @param contextType      human-readable label for the context (e.g. {@code "file"} or
     *                         {@code "package"}); embedded in trim-warning log messages
     * @param sourceText       full source text passed as input to the prompt preparation step
     * @param baseHeader       current header; passed through to each
     *                         {@link net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationRequest}
     * @return an {@link net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult} with the generated body; defaults to empty string
     * @throws IOException              if the AI provider throws during generation
     * @throws IllegalArgumentException if a field's {@link net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig#getAiDefinitionKey()}
     *                                  does not match any registered {@link net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinition}
     */
    public AiGenerationResult processFieldGenerations(
            final List<AiFieldGenerationConfig> fieldGenerations,
            final Path contextFile,
            final String contextType,
            final String sourceText,
            final AiMdHeader baseHeader)
            throws IOException {
        String body = "";

        for (AiFieldGenerationConfig fieldGeneration : fieldGenerations) {
            if (fieldGeneration == null) {
                continue;
            }

            final AiGenerationConfig generationConfig =
                    modelDefinitionSupport.getConfig(fieldGeneration.getAiDefinitionKey());

            final int effectiveMaxInputChars = resolveMaxInputChars(fieldGeneration, generationConfig, contextFile);

            final AiGenerationRequest request =
                    new AiGenerationRequest(fieldGeneration.getPromptKey(), contextFile, sourceText, baseHeader);

            final AiPreparedPrompt preparedPrompt =
                    promptPreparationSupport.preparePrompt(request, effectiveMaxInputChars);

            // Deterministic, whole-file "facts" (exact regex counts) are prepended to the body of EVERY
            // file that configures <facts> - not just oversize ones - so downstream agents get exact
            // structural counts in the summary. Computed once here over the FULL source ("" when unset).
            final String factsPrefix = AiFactExtractor.factsBlock(fieldGeneration.getFacts(), sourceText);

            // An oversized file (the source did not fit the window) is handled per the rule's onOversize
            // strategy. DETERMINISTIC/MAP_REDUCE replace the single generation entirely; FAIL/SAMPLE fall
            // through to the single-shot path below (the source was already trimmed to the window head).
            if (preparedPrompt.trimmed()) {
                final AiOversizeStrategy oversize = fieldGeneration.getOversizeStrategy();
                if (oversize == AiOversizeStrategy.DETERMINISTIC) {
                    body = factsPrefix
                            + AiDeterministicSummary.body(
                                    sourceText, contextName(contextFile), DETERMINISTIC_SAMPLE_LINES);
                    log.info("Oversize " + contextType + " '" + contextFile + "' -> deterministic body (no model), "
                            + sourceText.length() + " chars");
                    continue;
                }
                if (oversize == AiOversizeStrategy.MAP_REDUCE) {
                    body = factsPrefix
                            + mapReduceSummarize(
                                    fieldGeneration, contextFile, sourceText, baseHeader, effectiveMaxInputChars);
                    continue;
                }
            }

            if (preparedPrompt.trimmed() && generationConfig.isWarnOnTrim()) {
                log.warn("Trimmed AI input for " + contextType + TRIM_WARN_FIELD_LABEL + "body': " + contextFile
                        + " (source chars " + preparedPrompt.originalSourceLength()
                        + " -> " + preparedPrompt.trimmedSourceLength()
                        + ", available source chars " + preparedPrompt.availableSourceChars()
                        + ", max input chars " + effectiveMaxInputChars + ")");
            }

            final int processedSourceChars = preparedPrompt.sourceText().length();
            final String sourceSizeKb = sourceText.length() < KIBIBYTES_DIVISOR
                    ? SIZE_BELOW_ONE_KIB_LABEL
                    : Integer.toString(sourceText.length() / KIBIBYTES_DIVISOR);
            // Use the model's measured <calibration> when present, so the live per-file ETA matches the
            // (already calibrated) plan ETA instead of the built-in reference-CPU model.
            final long estimatedSeconds = estimateSeconds(processedSourceChars, generationConfig);
            log.info(PROCESSING_LOG_PREFIX + contextType + " '" + contextFile + "'"
                    + PROCESSING_LOG_SIZE_INFIX + sourceSizeKb
                    + PROCESSING_LOG_TOKENS_INFIX + timeEstimator.estimatePromptTokens(processedSourceChars)
                    + PROCESSING_LOG_ETA_INFIX
                    + timeEstimator.formatDuration(estimatedSeconds)
                    + PROCESSING_LOG_DISCLAIMER);

            log.info("Generating field '" + fieldGeneration.getPromptKey() + "' with temperature="
                    + generationConfig.getTemperature() + ", maxInputChars="
                    + effectiveMaxInputChars);
            final long generationStartNanos = System.nanoTime();
            final String generated = generateWithOverflowRetry(
                    fieldGeneration.getPromptKey(), contextFile, sourceText, baseHeader, effectiveMaxInputChars);
            final long actualSeconds = (System.nanoTime() - generationStartNanos) / NANOS_PER_SECOND;
            body = factsPrefix + generated;

            // Log the MEASURED wall-clock duration next to the estimate so real runs are directly
            // comparable across models/quants without a separate benchmark harness.
            log.info(GENERATED_LOG_PREFIX + contextType + " '" + contextFile + GENERATED_LOG_IN_INFIX
                    + timeEstimator.formatDuration(actualSeconds) + GENERATED_LOG_ACTUAL_INFIX
                    + timeEstimator.formatDuration(estimatedSeconds) + GENERATED_LOG_SUFFIX);

            if (compatibilityHelper.isBlank(generated)) {
                log.warn(EMPTY_OUTPUT_WARN_PREFIX + contextType + TRIM_WARN_FIELD_LABEL + fieldGeneration.getPromptKey()
                        + "': " + contextFile);
            }
        }

        return new AiGenerationResult(body);
    }

    /**
     * Summarizes an oversized source via map-reduce: split it into window-sized chunks at line boundaries
     * (with overlap), summarize each chunk with the rule's prompt (the <em>map</em>), then combine the
     * partial summaries via a {@link #reducePartials hierarchical reduce}. The {@code maxChunks} cap (when
     * set) bounds the run time by sampling representative chunks across the file; {@code maxChunks <= 0}
     * processes every chunk (the whole file).
     *
     * <p>The chunk window is shrunk by {@link #MAP_REDUCE_TOKEN_HEADROOM_PERCENT} so a token-dense chunk
     * cannot overflow the model's context (see that constant's Javadoc).</p>
     *
     * @param fieldGeneration        the routing rule (prompt key + {@code maxChunks})
     * @param contextFile            the source file path
     * @param sourceText             the full source text
     * @param baseHeader             the header passed through to each request
     * @param effectiveMaxInputChars the per-call window budget
     * @return the combined summary body
     * @throws IOException if the provider throws during generation
     */
    private String mapReduceSummarize(
            final AiFieldGenerationConfig fieldGeneration,
            final Path contextFile,
            final String sourceText,
            final AiMdHeader baseHeader,
            final int effectiveMaxInputChars)
            throws IOException {
        final int basePromptLength =
                promptPreparationSupport.getBasePromptLength(fieldGeneration.getPromptKey(), contextFile);
        // Reserve token-safety headroom: real chars/token can be below the configured charsPerToken for
        // dense content, so size chunks (and every map/reduce prompt) against a shrunken window.
        final int safeWindow =
                effectiveMaxInputChars - (effectiveMaxInputChars * MAP_REDUCE_TOKEN_HEADROOM_PERCENT / PERCENT);
        final int sourceBudget = Math.max(MIN_CHUNK_CHARS, safeWindow - basePromptLength);
        final int overlap = Math.min(MAP_REDUCE_OVERLAP_CHARS, sourceBudget / MAP_REDUCE_OVERLAP_DIVISOR);
        final List<String> chunks =
                AiSourceChunker.chunk(sourceText, sourceBudget, overlap, fieldGeneration.getMaxChunks());
        log.info("Oversize file '" + contextFile + "' -> mapReduce: " + sourceText.length() + " chars in "
                + chunks.size() + " chunk(s)");
        final List<String> partials = new ArrayList<>(chunks.size());
        int index = 0;
        for (final String chunk : chunks) {
            index++;
            partials.add(summarizeChunk(fieldGeneration.getPromptKey(), contextFile, chunk, baseHeader, safeWindow)
                    .trim());
            log.info("  mapReduce chunk " + index + "/" + chunks.size() + " summarized (" + chunk.length() + " chars)");
        }
        return reducePartials(
                fieldGeneration.getPromptKey(), contextFile, baseHeader, partials, sourceBudget, safeWindow);
    }

    /**
     * Combines per-chunk partial summaries into one body via a <strong>hierarchical</strong> reduce:
     * partials are packed into batches that fit the window (each batch at most {@link #MAX_REDUCE_FANIN}
     * partials), every batch is summarized, and the process repeats on the batch summaries until a single
     * summary remains. This avoids the single-reduce trap where hundreds of partials overflow one call
     * and the file's tail is silently trimmed away, so {@code maxChunks <= 0} (whole-file) coverage
     * actually reaches the final summary.
     *
     * @param promptKey   the prompt template key (shared by map and reduce)
     * @param contextFile the source file path
     * @param baseHeader  the header passed through to each request
     * @param partials    the per-chunk partial summaries (already trimmed); may be empty
     * @param sourceBudget the source-character budget used to pack a reduce batch
     * @param safeWindow  the per-call window budget passed to each reduce generation
     * @return the single combined summary, or an empty string when there are no partials
     * @throws IOException if the provider throws during generation
     */
    private String reducePartials(
            final String promptKey,
            final Path contextFile,
            final AiMdHeader baseHeader,
            final List<String> partials,
            final int sourceBudget,
            final int safeWindow)
            throws IOException {
        if (partials.isEmpty()) {
            return "";
        }
        List<String> level = partials;
        int round = 0;
        while (level.size() > 1) {
            round++;
            final List<String> next = new ArrayList<>(level.size());
            int i = 0;
            while (i < level.size()) {
                final StringBuilder batch = new StringBuilder();
                int inBatch = 0;
                while (inBatch < MAX_REDUCE_FANIN
                        && i < level.size()
                        && (inBatch == 0
                                || batch.length() + level.get(i).length() + REDUCE_LABEL_OVERHEAD_CHARS
                                        <= sourceBudget)) {
                    batch.append(REDUCE_PART_LABEL)
                            .append(inBatch + 1)
                            .append(":\n")
                            .append(level.get(i))
                            .append("\n\n");
                    inBatch++;
                    i++;
                }
                next.add(summarizeChunk(promptKey, contextFile, batch.toString(), baseHeader, safeWindow)
                        .trim());
            }
            log.info("  mapReduce reduce round " + round + ": " + level.size() + " -> " + next.size() + " partial(s)");
            if (next.size() >= level.size()) {
                // Pathological: partials too large to combine two-at-a-time. Collapse to one trimmed reduce
                // so the method always terminates rather than looping without shrinking.
                final StringBuilder all = new StringBuilder();
                int n = 0;
                for (final String partial : level) {
                    all.append(REDUCE_PART_LABEL)
                            .append(++n)
                            .append(":\n")
                            .append(partial)
                            .append("\n\n");
                }
                return summarizeChunk(promptKey, contextFile, all.toString(), baseHeader, safeWindow)
                        .trim();
            }
            level = next;
        }
        return level.get(0);
    }

    /**
     * Prepares the prompt for one chunk (trimming to the window) and returns the provider's summary.
     *
     * @param promptKey              the prompt template key
     * @param contextFile            the source file path
     * @param chunk                  the chunk (or concatenated partials) to summarize
     * @param baseHeader             the header passed through to the request
     * @param effectiveMaxInputChars the per-call window budget
     * @return the provider's summary for the chunk
     * @throws IOException if the provider throws during generation
     */
    private String summarizeChunk(
            final String promptKey,
            final Path contextFile,
            final String chunk,
            final AiMdHeader baseHeader,
            final int effectiveMaxInputChars)
            throws IOException {
        return generateWithOverflowRetry(promptKey, contextFile, chunk, baseHeader, effectiveMaxInputChars);
    }

    /**
     * Trims {@code source} to {@code window} and generates, retrying with a progressively smaller window
     * (up to {@link #MAX_OVERFLOW_RETRIES}) when the provider rejects the prompt for exceeding the model's
     * context. This is the char-estimate safety net: a token-dense prompt can exceed the context even
     * after the char-based trim, so rather than fail the build we re-trim and retry. Any non-overflow
     * exception propagates immediately.
     *
     * @param promptKey   the prompt template key
     * @param contextFile the source file path
     * @param source      the source text to trim and summarize
     * @param baseHeader  the header passed through to the request
     * @param window      the initial per-call window budget (characters)
     * @return the provider's generated text
     * @throws IOException if the provider throws an {@link IOException} during generation
     */
    private String generateWithOverflowRetry(
            final String promptKey,
            final Path contextFile,
            final String source,
            final AiMdHeader baseHeader,
            final int window)
            throws IOException {
        int budget = window;
        for (int attempt = 0; ; attempt++) {
            final AiPreparedPrompt prepared = promptPreparationSupport.preparePrompt(
                    new AiGenerationRequest(promptKey, contextFile, source, baseHeader), budget);
            try {
                return generationProvider.generate(
                        new AiGenerationRequest(promptKey, contextFile, prepared.sourceText(), baseHeader));
            } catch (final RuntimeException e) {
                final int reduced = Math.max(MIN_CHUNK_CHARS, budget * OVERFLOW_RETRY_BACKOFF_PERCENT / PERCENT);
                // Rethrow (giving up) once the retries are exhausted, when the window is already at the
                // floor (shrinking further would not help), or on a non-overflow error. The cheap
                // comparisons are checked before the cause-chain walk of isContextOverflow(e).
                if (attempt >= MAX_OVERFLOW_RETRIES || reduced >= budget || !isContextOverflow(e)) {
                    throw e;
                }
                log.warn("AI provider rejected the prompt (context overflow) for " + contextFile
                        + "; retrying with a smaller window (" + budget + " -> " + reduced + " chars)");
                budget = reduced;
            }
        }
    }

    /**
     * Returns whether {@code error} (or any cause in its chain) is a model context-overflow, matched on
     * the provider's message ({@link #CONTEXT_OVERFLOW_MARKER}).
     *
     * @param error the thrown error
     * @return {@code true} when the error indicates the prompt exceeded the context window
     */
    private static boolean isContextOverflow(final Throwable error) {
        for (Throwable cause = error; cause != null; cause = cause.getCause()) {
            final String message = cause.getMessage();
            if (message != null && message.contains(CONTEXT_OVERFLOW_MARKER)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Estimates one generation's seconds for the given char count, using the model's {@code <calibration>}
     * (measured per-machine throughput) when present, otherwise the estimator's built-in model. Mirrors
     * {@code SourceFileIndexer}'s plan-time estimate so the live per-file ETA agrees with the plan.
     *
     * @param sourceChars the processed source character count
     * @param config      the model's generation config (may carry a calibration)
     * @return the estimated seconds
     */
    private long estimateSeconds(final int sourceChars, final AiGenerationConfig config) {
        final AiCalibration calibration = config.getCalibration();
        if (calibration == null) {
            return timeEstimator.estimateSeconds(sourceChars);
        }
        return timeEstimator.estimateSecondsCalibrated(
                sourceChars,
                calibration.getPrefillTokensPerSecond(),
                calibration.getDecodeTokensPerSecond(),
                calibration.getCharsPerToken());
    }

    /**
     * Returns a short display name for a context file (its file name, or the full path as a fallback).
     *
     * @param contextFile the file path
     * @return the display name
     */
    private static String contextName(final Path contextFile) {
        final Path fileName = contextFile.getFileName();
        return fileName != null ? fileName.toString() : contextFile.toString();
    }

    /**
     * Returns the effective {@code maxInputChars} for the given field generation entry.
     *
     * <p>When the {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig#getCharsPerToken()} value is greater than zero,
     * the maximum is computed once per unique {@code (aiDefinitionKey, promptKey)} pair,
     * logged in detail, cached, and reused for all subsequent files. When
     * {@code charsPerToken} is zero, the static {@link net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig#getMaxInputChars()}
     * fallback is returned instead.</p>
     *
     * @param fieldGeneration  the field configuration identifying the definition and prompt keys
     * @param generationConfig the resolved generation config carrying {@code charsPerToken} etc.
     * @param contextFile      a representative file path used to render the base prompt length
     * @return effective maximum input characters for this field generation step
     */
    private int resolveMaxInputChars(
            final AiFieldGenerationConfig fieldGeneration,
            final AiGenerationConfig generationConfig,
            final Path contextFile) {
        if (generationConfig.getCharsPerToken() <= 0) {
            return generationConfig.getMaxInputChars();
        }

        final String cacheKey =
                computeMaxInputCharsKey(fieldGeneration.getAiDefinitionKey(), fieldGeneration.getPromptKey());
        final Integer cached = maxInputCharsCache.get(cacheKey);
        if (cached != null) {
            return cached;
        }

        final int basePromptLength =
                promptPreparationSupport.getBasePromptLength(fieldGeneration.getPromptKey(), contextFile);
        final int computed = calculateAndLogMaxInputChars(generationConfig, basePromptLength);
        maxInputCharsCache.put(cacheKey, computed);
        return computed;
    }

    /**
     * Computes and logs the detailed {@code maxInputChars} calculation for a given
     * generation config and base prompt length.
     *
     * <p>The formula is:</p>
     * <pre>
     *   totalChars     = contextSize × charsPerToken
     *   overheadTotal  = promptChars + eofChars + (maxOutputTokens × charsPerToken) + safetyChars
     *   availableChars = totalChars - overheadTotal
     *   finalChars     = floor(availableChars / 100) × 100   (rounded down conservatively)
     * </pre>
     *
     * <p>All intermediate values are emitted at INFO level so that the calculation is
     * transparent and reproducible from the build log alone.</p>
     *
     * @param config          the resolved generation config supplying {@code contextSize},
     *                        {@code maxOutputTokens}, and {@code charsPerToken}
     * @param basePromptLength character length of the prompt template rendered with empty source
     * @return final (rounded) maximum input character count
     */
    private int calculateAndLogMaxInputChars(final AiGenerationConfig config, final int basePromptLength) {
        final int contextSize = config.getContextSize();
        final int charsPerToken = config.getCharsPerToken();
        final int maxOutputTokens = config.getMaxOutputTokens();

        final int totalChars = contextSize * charsPerToken;
        final int promptChars = basePromptLength;
        final int eofChars = AiPromptPreparationSupport.EOF_MARKER_LENGTH;
        final int outputChars = maxOutputTokens * charsPerToken;
        final int safetyChars = AiGenerationConfig.DEFAULT_SAFETY_MARGIN_CHARS;
        final int overheadTotal = promptChars + eofChars + outputChars + safetyChars;
        final int availableChars = totalChars - overheadTotal;
        // Single source of truth for the threshold shared with the planning path (SourceFileIndexer.classify).
        final int finalChars = AiInputWindowCalculator.maxInputChars(config, basePromptLength);

        log.info("Maximum input characters for source code before trimming. Calculated as: (context_size x "
                + charsPerToken + ") - overhead");
        log.info("  Context: " + contextSize + " tokens");
        log.info("  Chars per token: ~" + charsPerToken);
        log.info("  [Total available]: " + contextSize + " x " + charsPerToken + " = " + totalChars + " chars");
        log.info("  Overhead (conservative estimate):");
        log.info("  - Prompt template: ~" + promptChars + " chars");
        log.info("  - EOF marker: ~" + eofChars + " chars");
        log.info("  - Max output (" + maxOutputTokens + " tokens x " + charsPerToken + "): ~" + outputChars + " chars");
        log.info("  - Safety margin: ~" + safetyChars + " chars");
        log.info("  - [Subtotal overhead]: ~" + overheadTotal + " chars");
        log.info("  Available for source: [Total available] - [Subtotal overhead]");
        log.info("  Available for source: " + totalChars + " - " + overheadTotal + " = " + availableChars + " chars");
        log.info("  Set to: " + finalChars + " (rounded, conservative)");

        return finalChars;
    }

    /**
     * Builds the cache key for the computed {@code maxInputChars} per
     * {@code (aiDefinitionKey, promptKey)} pair.
     *
     * @param aiDefinitionKey the AI model definition key
     * @param promptKey       the prompt template key
     * @return a unique composite cache key
     */
    private String computeMaxInputCharsKey(final String aiDefinitionKey, final String promptKey) {
        return aiDefinitionKey + CACHE_KEY_SEPARATOR + promptKey;
    }
}
