// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdChildEntryLineFormatter;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocument;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocumentCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptSupport;
import net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider;
import net.ladenthin.maven.llamacpp.aiindex.support.AiChecksumSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiPathSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiTimeSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.logging.Log;
import org.jspecify.annotations.Nullable;

/**
 * Aggregates {@code package.ai.md} index files: walks the output tree, lists each
 * package's contents, and fills in AI-generated summary and keyword fields.
 *
 * <p>{@code toString} is generated by Lombok over the configuration and collaborator
 * fields. The Maven {@link Log} is excluded because its default {@code toString} prints
 * implementation details (logger configuration, output stream state) that are noisy
 * and not useful for build-log diagnostics.
 */
@ToString
public class PackageIndexer {

    /**
     * Section heading inserted above the contents listing in both the package source text
     * and the default package body.
     */
    private static final String CONTENTS_HEADING = "#### Contents";

    /**
     * Markdown heading prefix used to label each child summary embedded in the package
     * source text fed to the AI model, e.g. {@code "### Foo.java"}. Identifies which
     * per-file (or sub-package) summary follows so the model can attribute it correctly.
     * Independent from {@link AiMdHeaderCodec#HEADER_TITLE_PREFIX} despite the same literal:
     * this one structures the AI <em>input</em>, not a persisted {@code .ai.md} header.
     */
    private static final String CHILD_SUMMARY_HEADING_PREFIX = "### ";

    /**
     * Suffix appended to a sub-package entry name so it is visually distinguishable from a
     * regular file entry in content listings and child-summary labels (e.g. {@code "sub/"}).
     */
    private static final String CHILD_DIRECTORY_SUFFIX = "/";

    /**
     * Placeholder note emitted under a child-summary heading when the corresponding
     * {@code .ai.md} body is blank or could not be read, so the model still learns the
     * child exists without being given a fabricated summary.
     */
    private static final String CHILD_SUMMARY_MISSING_NOTE = "(no summary available)";

    /**
     * Earliest possible date value used as the starting point when scanning child nodes
     * to find the latest index creation date.
     */
    private static final String EPOCH_DATE = "1970-01-01T00:00:00Z";

    /**
     * Context-type label passed to {@link AiFieldGenerationSupport} so that trim-warning
     * log messages read "Trimmed AI input for package field '…'".
     */
    private static final String CONTEXT_TYPE_PACKAGE = "package";

    /**
     * Comparator that orders {@link Path} instances by their file name component only,
     * producing a consistent, platform-independent sort order when listing directory entries.
     */
    private static final Comparator<Path> BY_FILE_NAME = Comparator.comparing(p -> {
        final Path fileName = p.getFileName();
        // Files.list never returns the filesystem root, so getFileName() is non-null here.
        if (fileName == null) {
            throw new IllegalStateException("Path has no file-name component: " + p);
        }
        return fileName.toString();
    });

    // Maven plugin Log — its default toString prints implementation details
    // (logger configuration, output stream state); excluded from the rendered output.
    @ToString.Exclude
    private final Log log;

    private final Path outputRoot;
    private final String pluginVersion;
    private final String aiVersion;
    private final List<Path> sourceSubtrees;
    private final List<Path> aiSubtrees;
    private final boolean force;

    private final @Nullable List<AiFieldGenerationConfig> fieldGenerations;

    private final AiPathSupport pathSupport = new AiPathSupport();
    private final AiTimeSupport timeSupport = new AiTimeSupport();
    private final AiChecksumSupport checksumSupport = new AiChecksumSupport();
    private final AiMdHeaderSupport headerSupport = new AiMdHeaderSupport();
    private final AiMdChildEntryLineFormatter childEntryLineFormatter = new AiMdChildEntryLineFormatter();
    private final AiMdDocumentCodec documentCodec = new AiMdDocumentCodec();
    private final AiMdHeaderCodec headerCodec = new AiMdHeaderCodec();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    private final AiFieldGenerationSupport fieldGenerationSupport;

    /**
     * Creates a new {@link PackageIndexer}.
     *
     * @param log                    Maven plugin logger
     * @param baseDirectory          project base directory
     * @param outputRoot             root directory in which {@code .ai.md} files reside
     * @param pluginVersion          plugin version recorded in headers
     * @param aiVersion              AI summarisation logic version recorded in headers
     * @param sourceSubtrees         source subtrees in scope; may be empty
     * @param force                  when {@code true}, regenerate even when fields are populated
     * @param generationProvider     AI provider used to generate fields
     * @param fieldGenerations       field generation configurations; may be {@code null}
     * @param promptSupport          prompt lookup
     * @param modelDefinitionSupport AI model definition lookup
     */
    public PackageIndexer(
            final Log log,
            final Path baseDirectory,
            final Path outputRoot,
            final String pluginVersion,
            final String aiVersion,
            final Collection<Path> sourceSubtrees,
            final boolean force,
            final AiGenerationProvider generationProvider,
            final @Nullable Collection<AiFieldGenerationConfig> fieldGenerations,
            final AiPromptSupport promptSupport,
            final AiModelDefinitionSupport modelDefinitionSupport) {
        this.log = log;
        this.outputRoot = outputRoot;
        this.pluginVersion = pluginVersion;
        this.aiVersion = aiVersion;
        this.sourceSubtrees = new ArrayList<>(sourceSubtrees);
        // Inlined here (instead of calling toAiSubtrees) so the Checker Framework
        // does not flag a method invocation on an @UnderInitialization receiver.
        final List<Path> ai = new ArrayList<>(this.sourceSubtrees.size());
        for (Path sourceSubtree : this.sourceSubtrees) {
            final Path relative = pathSupport.relativizeFromSrc(baseDirectory, sourceSubtree);
            ai.add(outputRoot.resolve(relative).normalize());
        }
        this.aiSubtrees = ai;
        this.force = force;
        this.fieldGenerations = fieldGenerations != null ? new ArrayList<>(fieldGenerations) : null;
        this.fieldGenerationSupport = new AiFieldGenerationSupport(
                log, generationProvider, new AiPromptPreparationSupport(promptSupport), modelDefinitionSupport);
    }

    /**
     * Aggregates all package directories beneath {@code rootDirectory}.
     *
     * @param rootDirectory output root directory to walk
     * @return number of package index files written or refreshed
     * @throws IOException if the output tree cannot be read or written
     */
    public int aggregate(final Path rootDirectory) throws IOException {
        return aggregateRecursive(rootDirectory);
    }

    private int aggregateRecursive(final Path directory) throws IOException {
        int count = 0;

        final List<Path> subDirectories;
        try (Stream<Path> stream = Files.list(directory)) {
            subDirectories =
                    compatibilityHelper.toList(stream.filter(Files::isDirectory).sorted());
        }

        for (Path subDirectory : subDirectories) {
            count += aggregateRecursive(subDirectory);
        }

        if (!matchesAggregationScope(directory)) {
            return count;
        }

        if (shouldCreatePackageFile(directory)) {
            writePackageFile(directory);
            count++;
        }

        return count;
    }

    private boolean matchesAggregationScope(final Path directory) {
        if (aiSubtrees.isEmpty()) {
            return true;
        }

        for (Path aiSubtree : aiSubtrees) {
            if (directory.startsWith(aiSubtree)) {
                return true;
            }
            if (aiSubtree.startsWith(directory)) {
                return true;
            }
        }

        return false;
    }

    private boolean shouldCreatePackageFile(final Path directory) throws IOException {
        try (Stream<Path> stream = Files.list(directory)) {
            return stream.anyMatch(path -> {
                final Path fileName = path.getFileName();
                // Files.list never returns the filesystem root, so getFileName() is non-null here.
                if (fileName == null) {
                    return false;
                }
                final String name = fileName.toString();
                if (Files.isDirectory(path)) {
                    return hasPackageAiMdFile(path);
                }
                return isAiMdContentFile(name);
            });
        }
    }

    /**
     * Returns {@code true} when {@code directory} contains a
     * {@link net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec#PACKAGE_AI_MD_FILENAME} file.
     *
     * @param directory the directory to examine
     * @return {@code true} if the package AI index file exists inside {@code directory}
     */
    private boolean hasPackageAiMdFile(final Path directory) {
        return Files.exists(directory.resolve(AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME));
    }

    private void writePackageFile(final Path directory) throws IOException {
        if (fieldGenerations == null || fieldGenerations.isEmpty()) {
            throw new IllegalArgumentException("No field generations configured for package indexing of " + directory);
        }

        final List<String> contents = collectContents(directory);
        final List<String> childLinks = collectChildLinks(directory);
        final Path packageFile = directory.resolve(AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME);

        final String nodeName = outputRoot.relativize(directory).toString().replace('\\', '/');
        final String title = nodeName.isEmpty() ? "ai" : nodeName;
        final String packageChecksum = calculatePackageChecksum(directory);
        final String packageDate = calculatePackageDate(directory);
        final String generatedAt = timeSupport.formatInstant(java.time.Instant.now());

        final AiMdHeader baseHeader = new AiMdHeader(
                title,
                AiMdHeaderCodec.HEADER_VERSION_1_0,
                packageChecksum,
                packageDate,
                generatedAt,
                pluginVersion,
                aiVersion,
                AiMdHeaderCodec.NODE_TYPE_PACKAGE,
                childLinks);

        if (!headerSupport.shouldWrite(force, packageFile, baseHeader)) {
            log.info("Unchanged package AI index file: " + packageFile);
            return;
        }

        final String sourceText = buildPackageSourceText(baseHeader, directory, contents);

        final AiGenerationResult result = fieldGenerationSupport.processFieldGenerations(
                fieldGenerations, packageFile, CONTEXT_TYPE_PACKAGE, sourceText, baseHeader);

        // result.body() is non-null by AiGenerationResult's constructor contract;
        // an empty/blank body falls back to the deterministic default.
        final String body =
                compatibilityHelper.isBlank(result.body()) ? buildDefaultPackageBody(contents) : result.body();

        final AiMdDocument document = new AiMdDocument(baseHeader, body);
        documentCodec.write(packageFile, document);

        log.info("Wrote package AI index file: " + packageFile);
    }

    private List<String> collectContents(final Path directory) throws IOException {
        final List<String> entries = new ArrayList<>();

        try (Stream<Path> stream = Files.list(directory)) {
            for (Path path : compatibilityHelper.toList(stream.sorted(BY_FILE_NAME))) {
                final Path fileNamePath = path.getFileName();
                if (fileNamePath == null) {
                    continue;
                }
                final String name = fileNamePath.toString();

                if (Files.isDirectory(path)) {
                    if (hasPackageAiMdFile(path)) {
                        entries.add(name + CHILD_DIRECTORY_SUFFIX);
                    }
                    continue;
                }

                if (isAiMdContentFile(name)) {
                    entries.add(name);
                }
            }
        }

        return entries;
    }

    /**
     * Collects the deterministic child links for {@code directory}'s header {@code F} list: one
     * markdown link per child {@code .ai.md} (the source name pointing at its index file) and per
     * sub-package (the directory name pointing at its {@code package.ai.md}), in ascending name order.
     * These links live in the header so the package&rarr;file navigation stays machine-parseable and
     * the AI body stays free-form.
     *
     * @param directory the package directory whose children are linked
     * @return ordered list of markdown child links; empty when the package has no children
     * @throws IOException if the directory cannot be listed
     */
    private List<String> collectChildLinks(final Path directory) throws IOException {
        final List<String> links = new ArrayList<>();

        try (Stream<Path> stream = Files.list(directory)) {
            for (Path path : compatibilityHelper.toList(stream.sorted(BY_FILE_NAME))) {
                final Path fileNamePath = path.getFileName();
                if (fileNamePath == null) {
                    continue;
                }
                final String name = fileNamePath.toString();

                if (Files.isDirectory(path)) {
                    if (hasPackageAiMdFile(path)) {
                        final String label = name + CHILD_DIRECTORY_SUFFIX;
                        links.add(markdownLink(label, label + AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME));
                    }
                    continue;
                }

                if (isAiMdContentFile(name)) {
                    links.add(markdownLink(toChildDisplayName(name), name));
                }
            }
        }

        return links;
    }

    /**
     * Formats a markdown link {@code [label](target)}.
     *
     * @param label  link label
     * @param target link target (relative path)
     * @return the markdown link string
     */
    private String markdownLink(final String label, final String target) {
        return "[" + label + "](" + target + ")";
    }

    /**
     * Builds the source text passed to the AI model for a package summary.
     *
     * <p>The text starts with the package's own deterministic header block, then embeds the
     * <em>already-generated</em> AI body of every child {@code .ai.md} (per-file summaries and
     * sub-package summaries), each under a {@link #CHILD_SUMMARY_HEADING_PREFIX} heading that
     * names the child. This is what the {@code package-body} prompt expects: it synthesises a
     * package summary from the child summaries, not from a bare name listing. Only the child
     * bodies are inlined; the single-letter child headers (metadata) are deliberately omitted
     * to save context and avoid distracting the model.</p>
     *
     * <p>When no child contributes a usable body (all blank or unreadable), the method falls
     * back to the plain {@link #CONTENTS_HEADING} name listing so the model still receives the
     * package contents.</p>
     *
     * <p>No explicit length cap is applied here: the combined text is subject to the existing
     * trim logic in {@link net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport#preparePrompt}, which truncates at a line
     * boundary to the computed {@code maxInputChars} budget and triggers the {@code warnOnTrim}
     * warning — so large packages degrade gracefully without a bespoke truncation scheme.</p>
     *
     * @param header    the package's own header (its title and metadata)
     * @param directory the package directory whose child {@code .ai.md} bodies are embedded
     * @param contents  pre-collected child entry names, used only for the no-body fallback
     * @return the rendered source text for the AI prompt
     * @throws IOException if a child {@code .ai.md} file cannot be read
     */
    private String buildPackageSourceText(
            final AiMdHeader header, final Path directory, final Collection<String> contents) throws IOException {
        final StringBuilder builder = new StringBuilder();
        appendPackageHeaderLines(builder, header);

        final StringBuilder summaries = new StringBuilder();
        final int bodyCount = appendChildSummaries(summaries, directory);

        if (bodyCount > 0) {
            builder.append(summaries);
        } else {
            // No child bodies were available — fall back to the plain name listing so the
            // model still receives the package contents rather than an empty source.
            appendContentsSection(builder, contents, true);
        }

        return builder.toString();
    }

    /**
     * Appends the package's own deterministic header block (title plus single-letter fields) to
     * {@code builder} by delegating to {@link AiMdHeaderCodec#write(AiMdHeader)} — the single source
     * of truth for the {@code .ai.md} header layout, and the same call {@link AiMdDocumentCodec} uses
     * to serialise a persisted header.
     *
     * @param builder target string builder
     * @param header  the package header to render
     */
    private void appendPackageHeaderLines(final StringBuilder builder, final AiMdHeader header) {
        builder.append(headerCodec.write(header));
    }

    /**
     * Appends one labelled child-summary block per child {@code .ai.md} under {@code directory}
     * to {@code builder}, in deterministic ascending name order. Each block is a
     * {@link #CHILD_SUMMARY_HEADING_PREFIX} heading naming the child followed by that child's
     * already-generated AI body (or {@link #CHILD_SUMMARY_MISSING_NOTE} when the body is blank).
     * Sub-package children reuse their aggregated {@code package.ai.md} body; the trailing
     * {@link #CHILD_DIRECTORY_SUFFIX} marks them as directories.
     *
     * @param builder   target string builder
     * @param directory the package directory whose children are scanned
     * @return the number of children that contributed a non-blank body
     * @throws IOException if a child {@code .ai.md} file cannot be read
     */
    private int appendChildSummaries(final StringBuilder builder, final Path directory) throws IOException {
        int bodyCount = 0;

        try (Stream<Path> stream = Files.list(directory)) {
            for (Path path : compatibilityHelper.toList(stream.sorted(BY_FILE_NAME))) {
                final Path fileNamePath = path.getFileName();
                if (fileNamePath == null) {
                    continue;
                }
                final String name = fileNamePath.toString();

                if (Files.isDirectory(path)) {
                    if (hasPackageAiMdFile(path)) {
                        final String body = readChildBody(path.resolve(AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME));
                        if (appendChildSummary(builder, name + CHILD_DIRECTORY_SUFFIX, body)) {
                            bodyCount++;
                        }
                    }
                    continue;
                }

                if (isAiMdContentFile(name)) {
                    final String body = readChildBody(path);
                    if (appendChildSummary(builder, toChildDisplayName(name), body)) {
                        bodyCount++;
                    }
                }
            }
        }

        return bodyCount;
    }

    /**
     * Appends a single child-summary block (heading plus body or missing-note) to {@code builder}.
     *
     * @param builder target string builder
     * @param label   child display label (file or sub-package name)
     * @param body    the child's AI body; may be blank
     * @return {@code true} if a non-blank body was appended, {@code false} for the missing-note case
     */
    private boolean appendChildSummary(final StringBuilder builder, final String label, final String body) {
        builder.append('\n').append(CHILD_SUMMARY_HEADING_PREFIX).append(label).append('\n');

        if (compatibilityHelper.isBlank(body)) {
            builder.append(CHILD_SUMMARY_MISSING_NOTE).append('\n');
            return false;
        }

        builder.append(body);
        if (!body.endsWith("\n")) {
            builder.append('\n');
        }
        return true;
    }

    /**
     * Reads and returns the AI body of a child {@code .ai.md} file, discarding its header.
     *
     * @param aiMdFile path to the child {@code .ai.md} file
     * @return the document body (possibly blank); never {@code null}
     * @throws IOException if the file cannot be read
     */
    private String readChildBody(final Path aiMdFile) throws IOException {
        return documentCodec.read(aiMdFile).body();
    }

    /**
     * Strips the {@link AiMdHeaderCodec#AI_MD_EXTENSION} suffix from a child file name so the
     * embedded heading reads as the original source name (e.g. {@code "Foo.java.ai.md"} →
     * {@code "Foo.java"}). Names without the extension are returned unchanged.
     *
     * @param fileName the child {@code .ai.md} file name
     * @return the display name with the {@code .ai.md} extension removed
     */
    private String toChildDisplayName(final String fileName) {
        if (fileName.endsWith(AiMdHeaderCodec.AI_MD_EXTENSION)) {
            return fileName.substring(0, fileName.length() - AiMdHeaderCodec.AI_MD_EXTENSION.length());
        }
        return fileName;
    }

    private String buildDefaultPackageBody(final Collection<String> contents) {
        final StringBuilder builder = new StringBuilder();
        appendContentsSection(builder, contents, false);
        return builder.toString();
    }

    /**
     * Appends the {@link #CONTENTS_HEADING} and the content entry list to {@code builder}.
     * Does nothing when {@code contents} is empty.
     *
     * @param builder        target string builder
     * @param contents       collection of content entry names
     * @param prependNewline when {@code true}, a blank line is prepended before the heading
     */
    private void appendContentsSection(
            final StringBuilder builder, final Collection<String> contents, final boolean prependNewline) {
        if (contents.isEmpty()) {
            return;
        }
        if (prependNewline) {
            builder.append('\n');
        }
        builder.append(CONTENTS_HEADING).append('\n');
        for (String entry : contents) {
            builder.append("- ").append(entry).append('\n');
        }
    }

    private String calculatePackageChecksum(final Path directory) throws IOException {
        final StringBuilder builder = new StringBuilder();

        try (Stream<Path> stream = Files.list(directory)) {
            for (Path path : compatibilityHelper.toList(stream.sorted(BY_FILE_NAME))) {
                final Path fileNamePath = path.getFileName();
                if (fileNamePath == null) {
                    continue;
                }
                final String name = fileNamePath.toString();

                if (Files.isDirectory(path)) {
                    if (hasPackageAiMdFile(path)) {
                        builder.append(childEntryLineFormatter.format(name, readChildPackageHeader(path)));
                    }
                    continue;
                }

                if (isAiMdContentFile(name)) {
                    builder.append(childEntryLineFormatter.format(
                            name, documentCodec.read(path).header()));
                }
            }
        }

        return checksumSupport.calculateCrc32Hex(builder.toString());
    }

    private String calculatePackageDate(final Path directory) throws IOException {
        String latest = EPOCH_DATE;

        try (Stream<Path> stream = Files.list(directory)) {
            for (Path path : compatibilityHelper.toList(stream.sorted(BY_FILE_NAME))) {
                final Path fileNamePath = path.getFileName();
                if (fileNamePath == null) {
                    continue;
                }
                final String name = fileNamePath.toString();

                if (Files.isDirectory(path)) {
                    if (hasPackageAiMdFile(path)) {
                        latest = laterDate(latest, readChildPackageHeader(path).d());
                    }
                    continue;
                }

                if (isAiMdContentFile(name)) {
                    latest = laterDate(latest, documentCodec.read(path).header().d());
                }
            }
        }

        return latest;
    }

    /**
     * Reads and returns the {@link net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader} from the
     * {@link net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec#PACKAGE_AI_MD_FILENAME} file inside {@code directory}.
     * The caller must ensure {@link #hasPackageAiMdFile(Path)} is {@code true} first.
     *
     * @param directory a directory that contains a {@code package.ai.md} file
     * @return the header of that package AI index file
     * @throws java.io.IOException if the file cannot be read
     */
    private AiMdHeader readChildPackageHeader(final Path directory) throws java.io.IOException {
        return documentCodec
                .read(directory.resolve(AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME))
                .header();
    }

    /**
     * Returns the lexicographically later of two ISO-8601 date strings,
     * i.e. the more-recent creation date.
     *
     * @param current   the currently known latest date
     * @param candidate a date from a child node to compare against {@code current}
     * @return {@code candidate} if it is strictly later than {@code current}, otherwise
     *         {@code current}
     */
    private String laterDate(final String current, final String candidate) {
        return candidate.compareTo(current) > 0 ? candidate : current;
    }

    /**
     * Returns {@code true} when {@code name} refers to a child AI index file that should
     * be included in content listings and checksum calculations. Excludes the
     * {@link net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec#PACKAGE_AI_MD_FILENAME} file itself, the
     * project-level {@link net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec#PROJECT_AI_MD_FILENAME}
     * (which the aggregator writes into the output root and must not fold back into its own
     * checksum or summary on a re-run), and any
     * {@link net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec#GENERATED_BY_PREFIX} marker files.
     *
     * @param name file name of the path under examination
     * @return {@code true} if the file is a regular content AI index entry
     */
    private boolean isAiMdContentFile(final String name) {
        return !AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME.equals(name)
                && !AiMdHeaderCodec.PROJECT_AI_MD_FILENAME.equals(name)
                && !name.startsWith(AiMdHeaderCodec.GENERATED_BY_PREFIX)
                && name.endsWith(AiMdHeaderCodec.AI_MD_EXTENSION);
    }
}
