// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocument;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocumentCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderSupport;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdLeadExtractor;
import net.ladenthin.maven.llamacpp.aiindex.support.AiChecksumSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiTimeSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.logging.Log;

/**
 * Builds the single project-level AI index — the top of the three-level index.
 *
 * <p>Walks the output tree, finds every {@link AiMdHeaderCodec#PACKAGE_AI_MD_FILENAME}, and writes
 * one {@link AiMdHeaderCodec#PROJECT_AI_MD_FILENAME} into the output root. The body lists each package
 * on a single line — its one-sentence <em>lead</em> (harvested from its already-generated body by
 * {@link AiMdLeadExtractor}) — while the header {@code F} list carries the matching clickable links to
 * each {@code package.ai.md}, mirroring the package level so navigation is uniformly in the header. The
 * result is a compact, always-loadable table of contents an agent reads first to decide which package
 * to open, instead of scanning thousands of file summaries.</p>
 *
 * <p>This step is fully <strong>deterministic</strong>: it harvests existing leads and never calls
 * the AI model, so it adds negligible cost and scales to projects with hundreds of packages. The
 * body is content-addressed — its {@code c} checksum is the CRC32 of the rendered body — so the file
 * is only rewritten when a package's lead, link, or set changes (or {@code force} is set), mirroring
 * the incremental contract of {@link SourceFileIndexer} and {@link PackageIndexer}.</p>
 *
 * <p>{@code toString} is generated by Lombok over the configuration and collaborator fields. The
 * Maven {@link Log} is excluded because its default {@code toString} prints implementation details
 * (logger configuration, output stream state) that are noisy and not useful for build-log
 * diagnostics.</p>
 */
@ToString
public class ProjectIndexer {

    /** Markdown heading introducing the per-package listing in the project index body. */
    private static final String PACKAGES_HEADING = "#### Packages";

    /** Separator placed between a package's link and its lead in a listing line. */
    private static final String LEAD_SEPARATOR = " — ";

    /** Display name used for the output-root package (whose relativised path is empty). */
    private static final String ROOT_DISPLAY = ".";

    /**
     * Earliest possible date value used as the starting point when scanning packages to find the
     * latest index creation date recorded in the project header's {@code d} field.
     */
    private static final String EPOCH_DATE = "1970-01-01T00:00:00Z";

    // Maven plugin Log — its default toString prints implementation details
    // (logger configuration, output stream state); excluded from the rendered output.
    @ToString.Exclude
    private final Log log;

    private final String projectTitle;
    private final String pluginVersion;
    private final String aiVersion;
    private final boolean force;

    private final AiTimeSupport timeSupport = new AiTimeSupport();
    private final AiChecksumSupport checksumSupport = new AiChecksumSupport();
    private final AiMdHeaderSupport headerSupport = new AiMdHeaderSupport();
    private final AiMdDocumentCodec documentCodec = new AiMdDocumentCodec();
    private final AiMdLeadExtractor leadExtractor = new AiMdLeadExtractor();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Creates a new {@link ProjectIndexer}.
     *
     * @param log           Maven plugin logger
     * @param projectTitle  title recorded in the project index header (typically the Maven project name)
     * @param pluginVersion plugin version recorded in the header
     * @param aiVersion     AI summarisation logic version recorded in the header
     * @param force         when {@code true}, rewrite the project index even when it is unchanged
     */
    public ProjectIndexer(
            final Log log,
            final String projectTitle,
            final String pluginVersion,
            final String aiVersion,
            final boolean force) {
        this.log = log;
        this.projectTitle = projectTitle;
        this.pluginVersion = pluginVersion;
        this.aiVersion = aiVersion;
        this.force = force;
    }

    /**
     * Aggregates every package index beneath {@code rootDirectory} into a single project index file.
     *
     * @param rootDirectory output root directory to walk for {@code package.ai.md} files
     * @return {@code 1} if the project index file was written or refreshed, {@code 0} if there were
     *         no package index files or the existing file was already up to date
     * @throws IOException if the output tree cannot be read or the project index cannot be written
     */
    public int aggregate(final Path rootDirectory) throws IOException {
        final List<Path> packageFiles;
        try (Stream<Path> stream = Files.walk(rootDirectory)) {
            packageFiles = compatibilityHelper.toList(
                    stream.filter(path -> Files.isRegularFile(path) && isPackageAiMdFile(path)));
        }

        if (packageFiles.isEmpty()) {
            log.info("No package index files found under " + rootDirectory + "; skipping project index.");
            return 0;
        }

        final List<PackageEntry> entries = new ArrayList<>(packageFiles.size());
        String latestDate = EPOCH_DATE;
        for (final Path packageFile : packageFiles) {
            final AiMdDocument document = documentCodec.read(packageFile);
            final String displayPath = displayPath(rootDirectory, packageFile);
            final String link = linkPath(rootDirectory, packageFile);
            final String lead = leadExtractor.extractLead(document.body());
            entries.add(new PackageEntry(displayPath, link, lead));
            latestDate = laterDate(latestDate, document.header().d());
        }
        entries.sort(Comparator.comparing(PackageEntry::link));

        final List<String> packageLinks = new ArrayList<>(entries.size());
        for (final PackageEntry entry : entries) {
            packageLinks.add(markdownLink(entry.displayPath(), entry.link()));
        }

        final String body = buildBody(entries);
        final String checksum = checksumSupport.calculateCrc32Hex(body);
        final String generatedAt = timeSupport.formatInstant(java.time.Instant.now());

        final AiMdHeader baseHeader = new AiMdHeader(
                projectTitle,
                AiMdHeaderCodec.HEADER_VERSION_1_0,
                checksum,
                latestDate,
                generatedAt,
                pluginVersion,
                aiVersion,
                AiMdHeaderCodec.NODE_TYPE_PROJECT,
                packageLinks);

        final Path projectFile = rootDirectory.resolve(AiMdHeaderCodec.PROJECT_AI_MD_FILENAME);

        if (!headerSupport.shouldWrite(force, projectFile, baseHeader)) {
            log.info("Unchanged project index file: " + projectFile);
            return 0;
        }

        documentCodec.write(projectFile, new AiMdDocument(baseHeader, body));
        log.info("Wrote project index file: " + projectFile + " (" + entries.size() + " packages)");
        return 1;
    }

    /**
     * Returns {@code true} when {@code path}'s file name is the package index file name.
     *
     * @param path candidate path encountered during the output-tree walk
     * @return {@code true} if {@code path} is a {@code package.ai.md} file
     */
    private boolean isPackageAiMdFile(final Path path) {
        final Path fileName = path.getFileName();
        return fileName != null && AiMdHeaderCodec.PACKAGE_AI_MD_FILENAME.equals(fileName.toString());
    }

    /**
     * Renders the project index body: a deterministic blockquote lead followed by one listing line
     * per package ({@code - <display> — <lead>}; the lead and its separator are omitted when the
     * package has no lead). The clickable links live in the header {@code F} list, not the body, so
     * the body stays compact at hundreds of packages and the path doubles as the header-link anchor.
     *
     * @param entries package entries, already sorted by link
     * @return the rendered markdown body
     */
    private String buildBody(final List<PackageEntry> entries) {
        final StringBuilder builder = new StringBuilder();
        final String leadLine = AiMdLeadExtractor.BLOCKQUOTE_MARKER + " Project index of " + projectTitle
                + ": one line per package; leads here, clickable links in the header F list.";
        builder.append(leadLine).append('\n').append('\n');
        builder.append(PACKAGES_HEADING).append('\n');
        for (final PackageEntry entry : entries) {
            builder.append("- ").append(entry.displayPath());
            if (!compatibilityHelper.isBlank(entry.lead())) {
                builder.append(LEAD_SEPARATOR).append(entry.lead());
            }
            builder.append('\n');
        }
        return builder.toString();
    }

    /**
     * Formats a markdown link {@code [label](target)} for the header {@code F} child-link list.
     *
     * @param label  link label (the package display path)
     * @param target link target (the relative path to the package's {@code package.ai.md})
     * @return the markdown link string
     */
    private String markdownLink(final String label, final String target) {
        return "[" + label + "](" + target + ")";
    }

    /**
     * Returns the display name for the package owning {@code packageFile}: its directory relativised
     * against {@code rootDirectory} with forward slashes, or {@value #ROOT_DISPLAY} for the
     * output-root package whose relativised path is empty.
     *
     * @param rootDirectory output root directory
     * @param packageFile   a {@code package.ai.md} file
     * @return the display path for the package
     */
    private String displayPath(final Path rootDirectory, final Path packageFile) {
        final Path packageDir = packageFile.getParent();
        if (packageDir == null) {
            return ROOT_DISPLAY;
        }
        final String relative = rootDirectory.relativize(packageDir).toString().replace('\\', '/');
        return relative.isEmpty() ? ROOT_DISPLAY : relative;
    }

    /**
     * Returns the relative link from the project index (written in {@code rootDirectory}) to
     * {@code packageFile}, using forward slashes.
     *
     * @param rootDirectory output root directory
     * @param packageFile   a {@code package.ai.md} file
     * @return the relative link string
     */
    private String linkPath(final Path rootDirectory, final Path packageFile) {
        return rootDirectory.relativize(packageFile).toString().replace('\\', '/');
    }

    /**
     * Returns the lexicographically later of two ISO-8601 date strings, i.e. the more-recent
     * creation date.
     *
     * @param current   the currently known latest date
     * @param candidate a date from a package node to compare against {@code current}
     * @return {@code candidate} if it is strictly later than {@code current}, otherwise {@code current}
     */
    private String laterDate(final String current, final String candidate) {
        return candidate.compareTo(current) > 0 ? candidate : current;
    }

    /** Immutable carrier for one package's display path, relative link, and harvested lead. */
    private static final class PackageEntry {
        private final String displayPath;
        private final String link;
        private final String lead;

        PackageEntry(final String displayPath, final String link, final String lead) {
            this.displayPath = displayPath;
            this.link = link;
            this.lead = lead;
        }

        String displayPath() {
            return displayPath;
        }

        String link() {
            return link;
        }

        String lead() {
            return lead;
        }
    }
}
