// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.stream.Stream;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiCondition;
import net.ladenthin.maven.llamacpp.aiindex.config.AiConditionEvaluator;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationSelector;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFileContext;
import net.ladenthin.maven.llamacpp.aiindex.config.AiGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.config.AiOversizeStrategy;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocument;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocumentCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiChecksumSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiGenerationTimeEstimator;
import net.ladenthin.maven.llamacpp.aiindex.support.AiPathSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiSourceExcludeFilter;
import net.ladenthin.maven.llamacpp.aiindex.support.AiTimeSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.logging.Log;
import org.jspecify.annotations.Nullable;

/**
 * Walks the configured source subtrees and writes per-file {@code .ai.md} index files.
 *
 * <p>Split into three steps so the {@code generate} goal can plan the whole run before any inference,
 * show the model/prompt mapping up front, and load each model exactly once:</p>
 * <ol>
 *   <li>{@link #collectCandidates(Path)} — walk a source root applying the extension, subtree, exclude
 *       and goal-level size-band filters.</li>
 *   <li>{@link #classify(Collection, List)} — route each candidate to a rule (prompt + model), a skip,
 *       or unmatched, producing an {@link AiIndexPlan}.</li>
 *   <li>{@link #indexFile(Path, AiFieldGenerationConfig, AiFieldGenerationSupport)} — write one file's
 *       {@code .ai.md} with a given rule, using a provider-bearing support (one per model group).</li>
 * </ol>
 *
 * <p>{@code toString} is generated by Lombok over the configuration fields. The Maven {@link Log} is
 * excluded because its default {@code toString} prints implementation details that are noisy in
 * build-log diagnostics.</p>
 */
@ToString
public class SourceFileIndexer {

    /**
     * Context-type label passed to {@link AiFieldGenerationSupport} so that trim-warning
     * log messages read "Trimmed AI input for file field '…'".
     */
    private static final String CONTEXT_TYPE_FILE = "file";

    // Maven plugin Log — its default toString prints implementation details
    // (logger configuration, output stream state); excluded from the rendered output.
    @ToString.Exclude
    private final Log log;

    private final Path baseDirectory;
    private final Path outputRoot;
    private final List<String> fileExtensions;
    private final String pluginVersion;
    private final String aiVersion;
    private final List<Path> subtrees;
    private final AiSourceExcludeFilter excludeFilter;
    private final long minFileSizeBytes;
    private final long maxFileSizeBytes;
    private final boolean force;

    private final AiPathSupport pathSupport = new AiPathSupport();
    private final AiTimeSupport timeSupport = new AiTimeSupport();
    private final AiChecksumSupport checksumSupport = new AiChecksumSupport();
    private final AiMdHeaderSupport headerSupport = new AiMdHeaderSupport();
    private final AiMdDocumentCodec documentCodec = new AiMdDocumentCodec();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();
    private final AiFieldGenerationSelector fieldGenerationSelector = new AiFieldGenerationSelector();
    private final AiConditionEvaluator conditionEvaluator = new AiConditionEvaluator();
    private final AiGenerationTimeEstimator timeEstimator = new AiGenerationTimeEstimator();

    /**
     * Creates a new {@link SourceFileIndexer}. The AI provider and rules are supplied later
     * ({@link #classify(Collection, List)} / {@link #indexFile}) so a run can load a separate model per
     * routing group.
     *
     * @param log              Maven plugin logger
     * @param baseDirectory    project base directory
     * @param outputRoot       root directory in which {@code .ai.md} files are written
     * @param fileExtensions   file extensions to index; may be empty (matches no files)
     * @param pluginVersion    plugin version recorded in headers
     * @param aiVersion        AI summarisation logic version recorded in headers
     * @param subtrees         source subtrees in scope; may be empty
     * @param excludes         glob patterns (relative to {@code baseDirectory}, {@code /} separators)
     *                         for source files to skip; may be {@code null} or empty
     * @param minFileSizeBytes exclusive lower size bound in bytes ({@code <= 0} disables it)
     * @param maxFileSizeBytes inclusive upper size bound in bytes ({@code <= 0} = unlimited)
     * @param force            when {@code true}, regenerate even when fields are populated
     */
    public SourceFileIndexer(
            final Log log,
            final Path baseDirectory,
            final Path outputRoot,
            final Collection<String> fileExtensions,
            final String pluginVersion,
            final String aiVersion,
            final Collection<Path> subtrees,
            final @Nullable Collection<String> excludes,
            final long minFileSizeBytes,
            final long maxFileSizeBytes,
            final boolean force) {
        this.log = log;
        this.baseDirectory = baseDirectory;
        this.outputRoot = outputRoot;
        this.fileExtensions = new ArrayList<>(fileExtensions);
        this.pluginVersion = pluginVersion;
        this.aiVersion = aiVersion;
        this.subtrees = new ArrayList<>(subtrees);
        this.excludeFilter = new AiSourceExcludeFilter(excludes);
        this.minFileSizeBytes = minFileSizeBytes;
        this.maxFileSizeBytes = maxFileSizeBytes;
        this.force = force;
    }

    /**
     * Returns every file beneath {@code sourceRoot} that passes the extension, subtree, exclude and
     * size-band filters — the candidate set for routing.
     *
     * @param sourceRoot source root directory to walk
     * @return the matching candidate files, in walk order
     * @throws IOException if the tree cannot be walked or a file size cannot be read
     */
    public List<Path> collectCandidates(final Path sourceRoot) throws IOException {
        final List<Path> candidates = new ArrayList<>();
        try (Stream<Path> stream = Files.walk(sourceRoot)) {
            for (final Path path : compatibilityHelper.toList(stream.filter(Files::isRegularFile))) {
                if (!matchesExtension(path)) {
                    continue;
                }
                if (!matchesSubtree(path)) {
                    continue;
                }
                if (isExcluded(path)) {
                    log.debug("Excluded from indexing: " + path);
                    continue;
                }
                if (!matchesSize(path)) {
                    log.debug("Outside configured size band, skipped: " + path);
                    continue;
                }
                candidates.add(path);
            }
        }
        return candidates;
    }

    /**
     * Routes each candidate file to a rule, producing the {@link AiIndexPlan}.
     *
     * <p>For every file the selector picks the winning rule by extension/size/lines and priority; a
     * skip rule sends the file to {@link AiIndexPlan#skipped()}, no match (and no fallback) to
     * {@link AiIndexPlan#unmatched()}, otherwise the file is routed under the rule's
     * {@code aiDefinitionKey}. Line counts are only computed when some rule actually uses a line filter,
     * so the common size-only configuration does not read file contents during planning.</p>
     *
     * @param candidates the candidate files (typically from {@link #collectCandidates(Path)})
     * @param rules      the routing rules in declaration order
     * @return the routing plan
     * @throws IOException if a file size or content cannot be read
     */
    public AiIndexPlan classify(final Collection<Path> candidates, final List<AiFieldGenerationConfig> rules)
            throws IOException {
        return classify(candidates, rules, null, null);
    }

    /**
     * Plans the run as {@link #classify(Collection, List)} and, when both supports are provided, also
     * computes each routed file's <em>context-window fit</em>: it resolves the routed model's
     * {@code contextSize}/sampling config and the prompt template length, derives the source-character
     * budget via {@link AiInputWindowCalculator} (the same threshold the run uses to trim), and records
     * whether the file would be trimmed. This lets the plan flag over-window files up front (and the
     * goal fail fast) instead of silently trimming them at run time. Pass {@code null} supports to skip
     * the window check.
     *
     * @param candidates               the candidate files (typically from {@link #collectCandidates(Path)})
     * @param rules                    the routing rules in declaration order
     * @param modelDefinitionSupport   model-config lookup by key, or {@code null} to skip the window check
     * @param promptPreparationSupport prompt-template helper, or {@code null} to skip the window check
     * @return the routing plan
     * @throws IOException if a file size or content cannot be read
     */
    public AiIndexPlan classify(
            final Collection<Path> candidates,
            final List<AiFieldGenerationConfig> rules,
            final @Nullable AiModelDefinitionSupport modelDefinitionSupport,
            final @Nullable AiPromptPreparationSupport promptPreparationSupport)
            throws IOException {
        final boolean lineFiltersUsed = anyRuleUsesLines(rules);
        final AiIndexPlan plan = new AiIndexPlan();
        for (final Path file : candidates) {
            final Path fileNamePath = file.getFileName();
            final String fileName = fileNamePath != null ? fileNamePath.toString() : file.toString();
            final long fileSizeBytes = Files.size(file);
            final int lineCount = lineFiltersUsed ? countLines(compatibilityHelper.readString(file)) : 0;
            final String relativePath =
                    baseDirectory.relativize(file).toString().replace('\\', '/');
            final long lastModified = Files.getLastModifiedTime(file).toMillis();
            final AiFileContext context =
                    new AiFileContext(fileName, relativePath, fileSizeBytes, lineCount, lastModified);

            final AiFieldGenerationConfig rule = fieldGenerationSelector.select(rules, context);
            if (rule == null) {
                plan.addUnmatched(file);
            } else if (rule.isSkip()) {
                plan.addSkipped(file);
            } else if (modelDefinitionSupport != null && promptPreparationSupport != null) {
                final AiGenerationConfig modelConfig = modelDefinitionSupport.getConfig(rule.getAiDefinitionKey());
                final int basePromptLength = promptPreparationSupport.getBasePromptLength(rule.getPromptKey(), file);
                final long availableSourceChars =
                        AiInputWindowCalculator.availableSourceChars(modelConfig, basePromptLength);
                final long sourceChars = compatibilityHelper.readString(file).length();
                final long routeSeconds = estimateRouteSeconds(rule, fileSizeBytes, sourceChars, availableSourceChars);
                plan.addRoute(rule.getAiDefinitionKey(), file, rule, routeSeconds, sourceChars, availableSourceChars);
            } else {
                final long estimatedSeconds =
                        timeEstimator.estimateSeconds((int) Math.min(fileSizeBytes, Integer.MAX_VALUE));
                plan.addRoute(rule.getAiDefinitionKey(), file, rule, estimatedSeconds);
            }
        }
        return plan;
    }

    /**
     * Estimates the generation time for one routed file, accounting for the rule's oversize strategy so
     * the plan ETA stays realistic for huge files (the per-call cost is bounded by the model window, not
     * the raw file size). A file that fits the window uses the normal size-based estimate; an over-window
     * file is estimated per strategy: {@code deterministic} is free, {@code sample}/{@code fail} cost one
     * window pass, and {@code mapReduce} costs (chunks + reduce) window passes (capped by {@code maxChunks}).
     *
     * @param rule                 the routing rule
     * @param fileSizeBytes        the file size in bytes
     * @param sourceChars          the source length in characters
     * @param availableSourceChars the per-call source-character budget of the routed model+prompt
     * @return the estimated seconds
     */
    private long estimateRouteSeconds(
            final AiFieldGenerationConfig rule,
            final long fileSizeBytes,
            final long sourceChars,
            final long availableSourceChars) {
        if (sourceChars <= availableSourceChars) {
            return timeEstimator.estimateSeconds((int) Math.min(fileSizeBytes, Integer.MAX_VALUE));
        }
        final long windowSeconds =
                timeEstimator.estimateSeconds((int) Math.min(availableSourceChars, Integer.MAX_VALUE));
        final AiOversizeStrategy strategy = rule.getOversizeStrategy();
        if (strategy == AiOversizeStrategy.DETERMINISTIC) {
            return 0L;
        }
        if (strategy == AiOversizeStrategy.MAP_REDUCE) {
            final long denom = Math.max(1L, availableSourceChars);
            final long naturalChunks = Math.max(1L, (sourceChars + denom - 1) / denom);
            final long chunks = rule.getMaxChunks() > 0 ? Math.min(rule.getMaxChunks(), naturalChunks) : naturalChunks;
            return (chunks + 1) * windowSeconds;
        }
        return windowSeconds;
    }

    /**
     * Writes the {@code .ai.md} for one source file using the given rule and a provider-bearing
     * support. Honours the incremental-skip rule: an up-to-date target (matching source checksum, no
     * {@code force}) is left untouched.
     *
     * @param sourceFile the source file
     * @param rule       the routing rule selected for it (supplies the prompt key)
     * @param support    the field-generation support holding the model group's provider
     * @return {@code true} if the file was (re)written, {@code false} if it was already up to date
     * @throws IOException if the file cannot be read or written
     */
    public boolean indexFile(
            final Path sourceFile, final AiFieldGenerationConfig rule, final AiFieldGenerationSupport support)
            throws IOException {
        final Path relativeToBase = pathSupport.relativizeFromSrc(baseDirectory, sourceFile);
        final Path targetFile = outputRoot
                .resolve(relativeToBase.toString() + AiMdHeaderCodec.AI_MD_EXTENSION)
                .normalize();

        final Path parent = targetFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        final Path sourceFileNamePath = sourceFile.getFileName();
        final String fileName = sourceFileNamePath != null ? sourceFileNamePath.toString() : sourceFile.toString();
        final String checksum = checksumSupport.calculateCrc32Hex(sourceFile);
        final String sourceModified =
                timeSupport.formatInstant(Files.getLastModifiedTime(sourceFile).toInstant());
        final String generatedAt = timeSupport.formatInstant(java.time.Instant.now());

        final AiMdHeader baseHeader = new AiMdHeader(
                fileName,
                AiMdHeaderCodec.HEADER_VERSION_1_0,
                checksum,
                sourceModified,
                generatedAt,
                pluginVersion,
                aiVersion,
                AiMdHeaderCodec.NODE_TYPE_FILE);

        if (!headerSupport.shouldWrite(force, targetFile, baseHeader)) {
            log.info("Unchanged AI index file: " + targetFile);
            return false;
        }

        final String sourceText = compatibilityHelper.readString(sourceFile);

        final AiGenerationResult result = support.processFieldGenerations(
                Collections.singletonList(rule), sourceFile, CONTEXT_TYPE_FILE, sourceText, baseHeader);

        final AiMdDocument document = new AiMdDocument(baseHeader, result.body());
        documentCodec.write(targetFile, document);

        log.info("Wrote AI index file: " + targetFile);
        return true;
    }

    /**
     * Returns {@code true} when at least one rule's condition uses a {@code lines} leaf, so planning
     * knows whether it must read file contents to count lines.
     *
     * @param rules the routing rules
     * @return {@code true} if any rule's condition uses a line count
     */
    private boolean anyRuleUsesLines(final List<AiFieldGenerationConfig> rules) {
        for (final AiFieldGenerationConfig rule : rules) {
            if (rule == null) {
                continue;
            }
            final AiCondition condition = rule.getCondition();
            if (condition != null && conditionEvaluator.usesLines(condition)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns {@code true} when {@code path} matches a configured exclude glob. The path is
     * relativised against {@link #baseDirectory} and normalised to {@code /} separators before matching.
     *
     * @param path absolute source file path encountered during the walk
     * @return {@code true} if the file should be skipped
     */
    private boolean isExcluded(final Path path) {
        final String relative = baseDirectory.relativize(path).toString().replace('\\', '/');
        return excludeFilter.isExcluded(relative);
    }

    /**
     * Returns {@code true} when {@code path}'s size on disk falls within the goal-level size band
     * (exclusive lower {@link #minFileSizeBytes}, inclusive upper {@link #maxFileSizeBytes}; each
     * disabled when {@code <= 0}).
     *
     * @param path absolute source file path encountered during the walk
     * @return {@code true} if the file is within the band
     * @throws IOException if the file size cannot be read
     */
    private boolean matchesSize(final Path path) throws IOException {
        final long size = Files.size(path);
        if (minFileSizeBytes > 0 && size <= minFileSizeBytes) {
            return false;
        }
        if (maxFileSizeBytes > 0 && size > maxFileSizeBytes) {
            return false;
        }
        return true;
    }

    /**
     * Counts the lines in {@code text} for the line-based prompt selector: the number of newline
     * characters, plus one when the text is non-empty and does not end with a newline (so a trailing
     * newline does not add a phantom empty line). An empty file counts as zero lines.
     *
     * @param text the source text
     * @return the line count
     */
    private int countLines(final String text) {
        if (text.isEmpty()) {
            return 0;
        }
        int newlines = 0;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '\n') {
                newlines++;
            }
        }
        return text.charAt(text.length() - 1) == '\n' ? newlines : newlines + 1;
    }

    private boolean matchesExtension(final Path path) {
        final Path fileNamePath = path.getFileName();
        if (fileNamePath == null) {
            return false;
        }
        final String fileName = fileNamePath.toString();
        for (final String extension : fileExtensions) {
            if (fileName.endsWith(extension)) {
                return true;
            }
        }
        return false;
    }

    private boolean matchesSubtree(final Path path) {
        if (subtrees == null || subtrees.isEmpty()) {
            return true;
        }
        for (final Path subtree : subtrees) {
            if (path.startsWith(subtree)) {
                return true;
            }
        }
        return false;
    }
}
