// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.indexer;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.stream.Stream;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationConfig;
import net.ladenthin.maven.llamacpp.aiindex.config.AiFieldGenerationSelector;
import net.ladenthin.maven.llamacpp.aiindex.config.AiModelDefinitionSupport;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationResult;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocument;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdDocumentCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeader;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderCodec;
import net.ladenthin.maven.llamacpp.aiindex.document.AiMdHeaderSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptPreparationSupport;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptSupport;
import net.ladenthin.maven.llamacpp.aiindex.provider.AiGenerationProvider;
import net.ladenthin.maven.llamacpp.aiindex.support.AiChecksumSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiPathSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.AiTimeSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.logging.Log;
import org.jspecify.annotations.Nullable;

/**
 * Walks the configured source subtrees, creates per-file {@code .ai.md} index files,
 * and fills in their AI-generated summary and keyword fields.
 *
 * <p>{@code toString} is generated by Lombok over the configuration and collaborator
 * fields. The Maven {@link Log} is excluded because its default {@code toString} prints
 * implementation details (logger configuration, output stream state) that are noisy
 * and not useful for build-log diagnostics.
 */
@ToString
public class SourceFileIndexer {

    /**
     * Context-type label passed to {@link AiFieldGenerationSupport} so that trim-warning
     * log messages read "Trimmed AI input for file field '…'".
     */
    private static final String CONTEXT_TYPE_FILE = "file";

    // Maven plugin Log — its default toString prints implementation details
    // (logger configuration, output stream state); excluded from the rendered output.
    @ToString.Exclude
    private final Log log;

    private final Path baseDirectory;
    private final Path outputRoot;
    private final List<String> fileExtensions;
    private final String pluginVersion;
    private final String aiVersion;
    private final List<Path> subtrees;
    private final boolean force;

    private final @Nullable List<AiFieldGenerationConfig> fieldGenerations;

    private final AiPathSupport pathSupport = new AiPathSupport();
    private final AiTimeSupport timeSupport = new AiTimeSupport();
    private final AiChecksumSupport checksumSupport = new AiChecksumSupport();
    private final AiMdHeaderSupport headerSupport = new AiMdHeaderSupport();
    private final AiMdDocumentCodec documentCodec = new AiMdDocumentCodec();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();
    private final AiFieldGenerationSelector fieldGenerationSelector = new AiFieldGenerationSelector();

    private final AiFieldGenerationSupport fieldGenerationSupport;

    /**
     * Creates a new {@link SourceFileIndexer}.
     *
     * @param log                    Maven plugin logger
     * @param baseDirectory          project base directory
     * @param outputRoot             root directory in which {@code .ai.md} files are written
     * @param fileExtensions         file extensions to index; may be empty (matches no files)
     * @param pluginVersion          plugin version recorded in headers
     * @param aiVersion              AI summarisation logic version recorded in headers
     * @param subtrees               source subtrees in scope; may be empty
     * @param force                  when {@code true}, regenerate even when fields are populated
     * @param generationProvider     AI provider used to generate fields
     * @param fieldGenerations       field generation configurations; may be {@code null}
     * @param promptSupport          prompt lookup
     * @param modelDefinitionSupport AI model definition lookup
     */
    public SourceFileIndexer(
            final Log log,
            final Path baseDirectory,
            final Path outputRoot,
            final Collection<String> fileExtensions,
            final String pluginVersion,
            final String aiVersion,
            final Collection<Path> subtrees,
            final boolean force,
            final AiGenerationProvider generationProvider,
            final @Nullable Collection<AiFieldGenerationConfig> fieldGenerations,
            final AiPromptSupport promptSupport,
            final AiModelDefinitionSupport modelDefinitionSupport) {
        this.log = log;
        this.baseDirectory = baseDirectory;
        this.outputRoot = outputRoot;
        this.fileExtensions = new ArrayList<>(fileExtensions);
        this.pluginVersion = pluginVersion;
        this.aiVersion = aiVersion;
        this.subtrees = new ArrayList<>(subtrees);
        this.force = force;
        this.fieldGenerations = fieldGenerations != null ? new ArrayList<>(fieldGenerations) : null;
        this.fieldGenerationSupport = new AiFieldGenerationSupport(
                log, generationProvider, new AiPromptPreparationSupport(promptSupport), modelDefinitionSupport);
    }

    /**
     * Indexes every matching file beneath {@code sourceRoot}.
     *
     * @param sourceRoot source root directory to walk
     * @return number of source-file index files written or refreshed
     * @throws IOException if a file cannot be read or written
     */
    public int indexSourceRoot(final Path sourceRoot) throws IOException {
        int count = 0;

        try (Stream<Path> stream = Files.walk(sourceRoot)) {
            for (Path path : compatibilityHelper.toList(stream.filter(Files::isRegularFile))) {
                if (!matchesExtension(path)) {
                    continue;
                }

                if (!matchesSubtree(path)) {
                    continue;
                }

                writeAiFile(path);
                count++;
            }
        }

        return count;
    }

    private boolean matchesExtension(final Path path) {
        final Path fileNamePath = path.getFileName();
        if (fileNamePath == null) {
            return false;
        }
        final String fileName = fileNamePath.toString();
        for (String extension : fileExtensions) {
            if (fileName.endsWith(extension)) {
                return true;
            }
        }
        return false;
    }

    private void writeAiFile(final Path sourceFile) throws IOException {
        if (fieldGenerations == null || fieldGenerations.isEmpty()) {
            throw new IllegalArgumentException(
                    "No field generations configured for source file indexing of " + sourceFile);
        }

        final Path relativeToBase = pathSupport.relativizeFromSrc(baseDirectory, sourceFile);
        final Path targetFile = outputRoot
                .resolve(relativeToBase.toString() + AiMdHeaderCodec.AI_MD_EXTENSION)
                .normalize();

        final Path parent = targetFile.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        final Path sourceFileNamePath = sourceFile.getFileName();
        final String fileName = sourceFileNamePath != null ? sourceFileNamePath.toString() : sourceFile.toString();
        final String checksum = checksumSupport.calculateCrc32Hex(sourceFile);
        final String sourceModified =
                timeSupport.formatInstant(Files.getLastModifiedTime(sourceFile).toInstant());
        final String generatedAt = timeSupport.formatInstant(java.time.Instant.now());

        final AiMdHeader baseHeader = new AiMdHeader(
                fileName,
                AiMdHeaderCodec.HEADER_VERSION_1_0,
                checksum,
                sourceModified,
                generatedAt,
                pluginVersion,
                aiVersion,
                AiMdHeaderCodec.NODE_TYPE_FILE);

        if (!headerSupport.shouldWrite(force, targetFile, baseHeader)) {
            log.info("Unchanged AI index file: " + targetFile);
            return;
        }

        final String sourceText = compatibilityHelper.readString(sourceFile);

        final AiFieldGenerationConfig selected = fieldGenerationSelector.selectForFileName(fieldGenerations, fileName);
        if (selected == null) {
            throw new IllegalArgumentException("No field generation matches file '" + fileName
                    + "' and no extension-agnostic fallback is configured: " + sourceFile);
        }

        final AiGenerationResult result = fieldGenerationSupport.processFieldGenerations(
                Collections.singletonList(selected), sourceFile, CONTEXT_TYPE_FILE, sourceText, baseHeader);

        final AiMdDocument document = new AiMdDocument(baseHeader, result.body());
        documentCodec.write(targetFile, document);

        log.info("Wrote AI index file: " + targetFile);
    }

    private boolean matchesSubtree(final Path path) {
        if (subtrees == null || subtrees.isEmpty()) {
            return true;
        }

        for (Path subtree : subtrees) {
            if (path.startsWith(subtree)) {
                return true;
            }
        }

        return false;
    }
}
