// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.config;

import lombok.ToString;

/**
 * One deterministic "fact" counter for an oversize routing rule: a human-readable {@link #label} paired
 * with a {@link #pattern} (a Java regular expression). The number of non-overlapping matches of
 * {@code pattern} across the <em>whole</em> source is reported next to {@code label} in the generated
 * body, giving exact counts the AI cannot reliably produce (it never sees the whole file when the source
 * is chunked/sampled).
 *
 * <p>Language-agnostic by design: the meaning is entirely in the regex the operator writes, so the same
 * mechanism counts {@code (?m)^\s*INSERT\b} rows in a SQL dump, {@code \bboolean\b} occurrences in Java,
 * or {@code (?m)^\s*def\b} functions in Python. Multi-line matching is opt-in via the inline flag
 * {@code (?m)} in the pattern; no flags are applied implicitly.</p>
 *
 * <p><strong>Note:</strong> this class must remain a mutable JavaBean with setters because the Maven
 * plugin framework populates it via reflection from the {@code <facts>} configuration list.</p>
 *
 * <p>{@code toString} is generated by Lombok for build-log diagnostics; {@code equals}/{@code hashCode}
 * are intentionally NOT generated (instances are configuration data managed by position in a list, and
 * the mutable JavaBean shape makes value semantics unsafe).</p>
 *
 * @see AiFactExtractor
 */
@SuppressWarnings({"NullAway.Init", "initialization.fields.uninitialized"})
@ToString
public class AiFactCounter {

    /** Creates a new {@link AiFactCounter}. */
    public AiFactCounter() {
        // no-op
    }

    /** Human-readable label shown next to the count (e.g. {@code "INSERT rows"}). */
    private String label;

    /** Java regular expression whose non-overlapping match count over the whole source is reported. */
    private String pattern;

    /**
     * Returns the human-readable label.
     *
     * @return the label
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the human-readable label.
     *
     * @param label the label
     */
    public void setLabel(final String label) {
        this.label = label;
    }

    /**
     * Returns the counting regular expression.
     *
     * @return the pattern
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the counting regular expression.
     *
     * @param pattern the pattern
     */
    public void setPattern(final String pattern) {
        this.pattern = pattern;
    }
}
