// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.config;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.ToString;
import org.jspecify.annotations.Nullable;

/**
 * Mutable configuration object that carries all parameters for a single AI generation
 * step (model path, sampling parameters, retry policy, input trimming limits, stop
 * strings) between the Maven configuration layer and the AI provider implementations.
 *
 * <p>{@code toString} is generated by Lombok over the instance fields for build-log
 * diagnostics. {@code equals}/{@code hashCode} are intentionally NOT generated:
 * instances are mutable JavaBeans populated through setters by the Maven plugin
 * framework and managed by identity.
 */
@SuppressWarnings({"NullAway.Init", "initialization.fields.uninitialized"})
@ToString
public class AiGenerationConfig {

    /** Creates a new {@link AiGenerationConfig} with all defaults applied. */
    public AiGenerationConfig() {
        // no-op
    }

    /** Default context window size (in tokens) used when no explicit context size is configured. */
    public static final int DEFAULT_CONTEXT_SIZE = 32768;

    /** Default maximum number of output tokens to generate in a single inference call. */
    public static final int DEFAULT_MAX_OUTPUT_TOKENS = 128;

    /**
     * Default sampling temperature. Lower values make output more deterministic;
     * {@code 0.0} is fully greedy.
     */
    public static final float DEFAULT_TEMPERATURE = 0.15f;

    /** Default number of CPU threads used for llama.cpp inference. */
    public static final int DEFAULT_THREADS = 8;

    /**
     * Default maximum number of characters of source text fed into the prompt.
     * Used as a fallback when {@link #charsPerToken} is zero (e.g. in mock-based tests).
     * When {@link #charsPerToken} is greater than zero, {@code maxInputChars} is calculated
     * automatically from context size, output tokens, prompt overhead, and safety margin.
     */
    public static final int DEFAULT_MAX_INPUT_CHARS = 120000;

    /**
     * Default number of characters per token used in the automatic {@code maxInputChars}
     * calculation. A value of {@code 4} is a conventional conservative estimate that works
     * well across most Latin-script source code.
     *
     * <p>Set to {@code 0} to disable automatic calculation and fall back to
     * {@link #DEFAULT_MAX_INPUT_CHARS}.</p>
     */
    public static final int DEFAULT_CHARS_PER_TOKEN = 4;

    /**
     * Default safety margin in characters subtracted from the total available budget
     * during automatic {@code maxInputChars} calculation. Provides headroom for
     * tokenisation overhead and minor prompt expansions.
     */
    public static final int DEFAULT_SAFETY_MARGIN_CHARS = 500;

    /**
     * Default setting for whether to emit a warning when the prompt source text is trimmed
     * to fit within {@link #DEFAULT_MAX_INPUT_CHARS}.
     */
    public static final boolean DEFAULT_WARN_ON_TRIM = true;

    /**
     * Default nucleus-sampling probability threshold.
     * Matches the {@code net.ladenthin:llama} {@code InferenceParameters} library default so
     * that models which do not declare an explicit value retain the same output distribution
     * as before this field was introduced.
     */
    public static final float DEFAULT_TOP_P = 0.9f;

    /**
     * Default top-k sampling limit.
     * Matches the {@code net.ladenthin:llama} {@code InferenceParameters} library default so
     * that models which do not declare an explicit value retain the same output distribution
     * as before this field was introduced.
     */
    public static final int DEFAULT_TOP_K = 40;

    /**
     * Default min-p sampling threshold. A value of {@code 0.0} disables min-p truncation and
     * preserves existing behaviour for models that do not specify it. min-p keeps only tokens whose
     * probability is at least this fraction of the top token's probability; it is the recommended
     * primary truncation for gpt-oss at a non-greedy temperature (scales the cut-off to the model's
     * confidence — see {@code docs/ai-index-benchmark/gpt-oss-tuning.md} D1).
     */
    public static final float DEFAULT_MIN_P = 0.0f;

    /**
     * Default top-n-sigma sampling threshold. A value of {@code -1.0} disables it and preserves
     * existing behaviour. top-n-sigma keeps tokens within n standard deviations of the max logit;
     * unlike top-p/min-p its candidate set is temperature-invariant, which can make structured
     * extraction more reproducible (see {@code docs/ai-index-benchmark/gpt-oss-tuning.md} E6).
     */
    public static final float DEFAULT_TOP_N_SIGMA = -1.0f;

    /**
     * Default repetition penalty. A value of {@code 1.0} means no penalty and preserves
     * existing behaviour for models that do not specify it.
     */
    public static final float DEFAULT_REPEAT_PENALTY = 1.0f;

    /**
     * Default setting for whether the model's chat-template thinking mode is enabled.
     *
     * <p>When enabled, the model uses its own chat-template default for chain-of-thought
     * reasoning.  When disabled, {@link net.ladenthin.llama.parameters.ModelParameters#setChatTemplateKwargs}
     * is called with {@code {"enable_thinking": "false"}} to suppress the thinking block at the
     * Jinja template level — set to {@code false} for Gemma 4 definitions to prevent
     * {@code <|channel>thought} tokens from leaking into stored output.</p>
     */
    public static final boolean DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING = true;

    /**
     * Default for whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * <p>When {@code true}, the provider keeps the shared prompt-template prefix in the KV cache and
     * reuses it across files — only the differing source text is re-prefilled per file. This is a
     * pure speed optimisation: prefix reuse is exact, so the generated output is unchanged.</p>
     */
    public static final boolean DEFAULT_CACHE_PROMPT = true;

    /**
     * Default gpt-oss reasoning-effort level ({@code "low"} / {@code "medium"} / {@code "high"}).
     *
     * <p>{@code "low"} keeps the discarded chain-of-thought minimal for the short, structured
     * summaries this plugin produces (the gpt-oss model default would be {@code "medium"}). It is
     * passed as the {@code reasoning_effort} chat-template kwarg; non-gpt-oss chat templates ignore
     * it. An empty value omits the kwarg entirely so the model's own template default applies.</p>
     */
    public static final String DEFAULT_REASONING_EFFORT = "low";

    /**
     * Default reasoning/think-token budget ({@code thinking_budget_tokens} / {@code --reasoning-budget}).
     * {@code -1} = unrestricted (llama.cpp default). A value {@code >= 0} caps the harmony analysis
     * (reasoning) tokens so a runaway chain-of-thought cannot starve the final answer of output budget;
     * see {@code docs/ai-index-benchmark/gpt-oss-tuning.md} E2.
     */
    public static final int DEFAULT_REASONING_BUDGET_TOKENS = -1;

    /**
     * Default for whether the full-size sliding-window-attention (SWA) KV cache is kept
     * ({@code --swa-full}). {@code true} = keep the full SWA KV so the shared prompt prefix is reusable
     * across files (the llama.cpp default of window-sized SWA KV uses ~half the RAM but is not reusable
     * across requests). Adopted as the shipped default (pairs with {@link #DEFAULT_CACHE_REUSE}) because
     * project indexing is a multi-file batch sharing one prompt prefix, where E4 measured ~21% less
     * prefill / ~12% less wall time; cost is ~2× SWA-layer KV RAM (acceptable for the typical overnight
     * full-project run). Set {@code false} for RAM-constrained single-file use.
     */
    public static final boolean DEFAULT_SWA_FULL = true;

    /**
     * Default minimum chunk size (tokens) for cross-request KV prefix reuse ({@code --cache-reuse}).
     * {@code 256} = the value E4 measured; lets the server reuse a matching prompt prefix from a previous
     * request instead of re-prefilling it (exact-prefix match, so output is unchanged). Pairs with
     * {@link #DEFAULT_SWA_FULL}; set {@code 0} to disable (the llama.cpp default).
     */
    public static final int DEFAULT_CACHE_REUSE = 256;

    /**
     * Default number of model layers to offload to the GPU ({@code --gpu-layers}). {@code -1} (default)
     * means "do not set it" — the binding/native build decides (a CPU build stays on CPU; a GPU build
     * uses its own default). {@code 0} forces CPU even on a GPU build; a positive value offloads that
     * many layers (use partial offload when the model does not fit in VRAM). Only effective with a GPU
     * native (e.g. the {@code cuda13-windows-x86-64} / {@code vulkan-windows-x86-64} classifier).
     */
    public static final int DEFAULT_GPU_LAYERS = -1;

    /**
     * Default primary GPU index ({@code --main-gpu}). {@code -1} (default) means "do not set it" — the
     * binding/native build decides (llama.cpp's own default is device {@code 0}). Set a non-negative
     * index to pick a specific device. This matters on machines with more than one GPU visible to the
     * backend: a Vulkan build enumerates <em>all</em> GPUs (e.g. an integrated GPU as device {@code 0}
     * and a discrete GPU as device {@code 1}), so the default may select the slower one; a CUDA build
     * only enumerates NVIDIA devices. Only effective with a GPU native. See also {@link #DEFAULT_DEVICES}.
     */
    public static final int DEFAULT_MAIN_GPU = -1;

    /**
     * Default device selection ({@code --device}). Empty (default) means "do not set it" — the
     * binding/native build decides. A non-empty value is a comma-separated list of backend device
     * names to use (e.g. {@code Vulkan1} or {@code CUDA0}); it takes precedence over a single
     * {@link #DEFAULT_MAIN_GPU} index when finer control across multiple devices is needed. Only
     * effective with a GPU native.
     */
    public static final String DEFAULT_DEVICES = "";

    /**
     * Default DRY (Don't Repeat Yourself) sampling multiplier ({@code --dry-multiplier}).
     * {@code 0.0} = disabled (llama.cpp default). A positive value penalises verbatim n-gram
     * repetition, which can break runaway repetition loops; the other {@code dry*} knobs only take
     * effect when this is non-zero. Opt-in safety knob for repetition-prone models/configs.
     */
    public static final float DEFAULT_DRY_MULTIPLIER = 0.0f;

    /**
     * Default DRY base ({@code --dry-base}); the exponential growth base of the repetition penalty.
     * {@code 1.75} = llama.cpp default. Only takes effect when {@link #DEFAULT_DRY_MULTIPLIER} is non-zero.
     */
    public static final float DEFAULT_DRY_BASE = 1.75f;

    /**
     * Default DRY allowed length ({@code --dry-allowed-length}); the longest n-gram that may repeat
     * without penalty. {@code 2} = llama.cpp default. Only takes effect when DRY is enabled.
     */
    public static final int DEFAULT_DRY_ALLOWED_LENGTH = 2;

    /**
     * Default DRY penalty look-back window in tokens ({@code --dry-penalty-last-n}).
     * {@code -1} = whole context (llama.cpp default), {@code 0} = disabled. Only takes effect when DRY
     * is enabled.
     */
    public static final int DEFAULT_DRY_PENALTY_LAST_N = -1;

    private String modelPath;
    private int contextSize = DEFAULT_CONTEXT_SIZE;
    private int maxOutputTokens = DEFAULT_MAX_OUTPUT_TOKENS;
    private float temperature = DEFAULT_TEMPERATURE;
    private int threads = DEFAULT_THREADS;
    private int charsPerToken = DEFAULT_CHARS_PER_TOKEN;
    private int maxInputChars = DEFAULT_MAX_INPUT_CHARS;
    private boolean warnOnTrim = DEFAULT_WARN_ON_TRIM;
    private float topP = DEFAULT_TOP_P;
    private int topK = DEFAULT_TOP_K;
    private float minP = DEFAULT_MIN_P;
    private float topNSigma = DEFAULT_TOP_N_SIGMA;
    private float repeatPenalty = DEFAULT_REPEAT_PENALTY;
    private boolean chatTemplateEnableThinking = DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING;
    private boolean cachePrompt = DEFAULT_CACHE_PROMPT;
    private boolean swaFull = DEFAULT_SWA_FULL;
    private int cacheReuse = DEFAULT_CACHE_REUSE;
    private int gpuLayers = DEFAULT_GPU_LAYERS;
    private int mainGpu = DEFAULT_MAIN_GPU;
    private String devices = DEFAULT_DEVICES;
    private String reasoningEffort = DEFAULT_REASONING_EFFORT;
    private int reasoningBudgetTokens = DEFAULT_REASONING_BUDGET_TOKENS;
    private float dryMultiplier = DEFAULT_DRY_MULTIPLIER;
    private float dryBase = DEFAULT_DRY_BASE;
    private int dryAllowedLength = DEFAULT_DRY_ALLOWED_LENGTH;
    private int dryPenaltyLastN = DEFAULT_DRY_PENALTY_LAST_N;
    private List<String> drySequenceBreakers = new ArrayList<>();
    private List<String> stopStrings = new ArrayList<>();

    /** Optional per-machine timing calibration; {@code null} = use the estimator's built-in model. */
    private @Nullable AiCalibration calibration;

    /**
     * Returns the GGUF model file path.
     *
     * @return model file path, or {@code null} if not set
     */
    public String getModelPath() {
        return modelPath;
    }

    /**
     * Sets the GGUF model file path.
     *
     * @param modelPath absolute or relative path to the model file
     */
    public void setModelPath(final String modelPath) {
        this.modelPath = modelPath;
    }

    /**
     * Returns the context window size in tokens.
     *
     * @return context window size in tokens
     */
    public int getContextSize() {
        return contextSize;
    }

    /**
     * Sets the context window size in tokens.
     *
     * @param contextSize context window size in tokens
     */
    public void setContextSize(final int contextSize) {
        this.contextSize = contextSize;
    }

    /**
     * Returns the maximum number of output tokens per inference call.
     *
     * @return maximum output tokens
     */
    public int getMaxOutputTokens() {
        return maxOutputTokens;
    }

    /**
     * Sets the maximum number of output tokens per inference call.
     *
     * @param maxOutputTokens maximum output tokens
     */
    public void setMaxOutputTokens(final int maxOutputTokens) {
        this.maxOutputTokens = maxOutputTokens;
    }

    /**
     * Returns the sampling temperature.
     *
     * @return sampling temperature
     */
    public float getTemperature() {
        return temperature;
    }

    /**
     * Sets the sampling temperature.
     *
     * @param temperature sampling temperature; lower is more deterministic
     */
    public void setTemperature(final float temperature) {
        this.temperature = temperature;
    }

    /**
     * Returns the number of CPU threads used for inference.
     *
     * @return number of CPU threads
     */
    public int getThreads() {
        return threads;
    }

    /**
     * Sets the number of CPU threads used for inference.
     *
     * @param threads number of CPU threads
     */
    public void setThreads(final int threads) {
        this.threads = threads;
    }

    /**
     * Returns the number of characters per token used in automatic {@code maxInputChars}
     * calculation.
     *
     * @return chars-per-token ratio; {@code 0} disables automatic calculation
     */
    public int getCharsPerToken() {
        return charsPerToken;
    }

    /**
     * Sets the number of characters per token.
     *
     * @param charsPerToken approximate characters per token; use {@code 0} to disable
     *                      automatic calculation and fall back to {@link #getMaxInputChars()}
     */
    public void setCharsPerToken(final int charsPerToken) {
        this.charsPerToken = charsPerToken;
    }

    /**
     * Returns the maximum number of input characters fed to the prompt.
     *
     * @return maximum input characters
     */
    public int getMaxInputChars() {
        return maxInputChars;
    }

    /**
     * Sets the maximum number of input characters fed to the prompt.
     *
     * @param maxInputChars maximum input characters
     */
    public void setMaxInputChars(final int maxInputChars) {
        this.maxInputChars = maxInputChars;
    }

    /**
     * Returns whether a warning is emitted when the prompt source text is trimmed.
     *
     * @return {@code true} if trim warnings are enabled
     */
    public boolean isWarnOnTrim() {
        return warnOnTrim;
    }

    /**
     * Sets whether a warning is emitted when the prompt source text is trimmed.
     *
     * @param warnOnTrim {@code true} to enable trim warnings
     */
    public void setWarnOnTrim(final boolean warnOnTrim) {
        this.warnOnTrim = warnOnTrim;
    }

    /**
     * Returns the nucleus-sampling probability threshold.
     *
     * @return top-p value
     */
    public float getTopP() {
        return topP;
    }

    /**
     * Sets the nucleus-sampling probability threshold.
     *
     * @param topP top-p value
     */
    public void setTopP(final float topP) {
        this.topP = topP;
    }

    /**
     * Returns the top-k sampling limit.
     *
     * @return top-k value
     */
    public int getTopK() {
        return topK;
    }

    /**
     * Sets the top-k sampling limit.
     *
     * @param topK top-k value
     */
    public void setTopK(final int topK) {
        this.topK = topK;
    }

    /**
     * Returns the repetition penalty.
     *
     * @return repeat penalty
     */
    public float getRepeatPenalty() {
        return repeatPenalty;
    }

    /**
     * Sets the repetition penalty.
     *
     * @param repeatPenalty repeat penalty
     */
    public void setRepeatPenalty(final float repeatPenalty) {
        this.repeatPenalty = repeatPenalty;
    }

    /**
     * Returns the min-p sampling threshold.
     *
     * @return min-p threshold ({@code 0.0} = disabled)
     */
    public float getMinP() {
        return minP;
    }

    /**
     * Sets the min-p sampling threshold.
     *
     * @param minP min-p threshold ({@code 0.0} = disabled)
     */
    public void setMinP(final float minP) {
        this.minP = minP;
    }

    /**
     * Returns the top-n-sigma sampling threshold.
     *
     * @return top-n-sigma threshold ({@code -1.0} = disabled)
     */
    public float getTopNSigma() {
        return topNSigma;
    }

    /**
     * Sets the top-n-sigma sampling threshold.
     *
     * @param topNSigma top-n-sigma threshold ({@code -1.0} = disabled)
     */
    public void setTopNSigma(final float topNSigma) {
        this.topNSigma = topNSigma;
    }

    /**
     * Returns whether the model's chat-template thinking mode is enabled.
     *
     * @return {@code true} if chat-template thinking mode is enabled
     */
    public boolean isChatTemplateEnableThinking() {
        return chatTemplateEnableThinking;
    }

    /**
     * Sets whether the model's chat-template thinking mode is enabled.
     *
     * @param chatTemplateEnableThinking {@code true} to enable chat-template thinking mode
     */
    public void setChatTemplateEnableThinking(final boolean chatTemplateEnableThinking) {
        this.chatTemplateEnableThinking = chatTemplateEnableThinking;
    }

    /**
     * Returns whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * @return {@code true} when prompt-prefix KV reuse across files is enabled
     */
    public boolean isCachePrompt() {
        return cachePrompt;
    }

    /**
     * Returns whether the full-size SWA KV cache is kept ({@code --swa-full}).
     *
     * @return {@code true} when full SWA KV is kept
     */
    public boolean isSwaFull() {
        return swaFull;
    }

    /**
     * Sets whether the full-size SWA KV cache is kept ({@code --swa-full}).
     *
     * @param swaFull {@code true} to keep full SWA KV (enables cross-request prefix reuse, more RAM)
     */
    public void setSwaFull(final boolean swaFull) {
        this.swaFull = swaFull;
    }

    /**
     * Returns the KV prefix-reuse minimum chunk size ({@code --cache-reuse}).
     *
     * @return cache-reuse chunk size ({@code 0} = disabled)
     */
    public int getCacheReuse() {
        return cacheReuse;
    }

    /**
     * Sets the KV prefix-reuse minimum chunk size ({@code --cache-reuse}).
     *
     * @param cacheReuse chunk size in tokens ({@code 0} = disabled)
     */
    public void setCacheReuse(final int cacheReuse) {
        this.cacheReuse = cacheReuse;
    }

    /**
     * Returns the number of model layers to offload to the GPU ({@code --gpu-layers}).
     *
     * @return GPU layers ({@code -1} = leave the binding/build default)
     */
    public int getGpuLayers() {
        return gpuLayers;
    }

    /**
     * Sets the number of model layers to offload to the GPU ({@code --gpu-layers}).
     *
     * @param gpuLayers GPU layers ({@code -1} = leave default, {@code 0} = force CPU, {@code >0} = offload)
     */
    public void setGpuLayers(final int gpuLayers) {
        this.gpuLayers = gpuLayers;
    }

    /**
     * Returns the primary GPU index ({@code --main-gpu}).
     *
     * @return the GPU index, or {@code -1} to leave the binding/build default
     */
    public int getMainGpu() {
        return mainGpu;
    }

    /**
     * Sets the primary GPU index ({@code --main-gpu}).
     *
     * @param mainGpu the GPU index ({@code -1} = leave default; a non-negative value selects that device)
     */
    public void setMainGpu(final int mainGpu) {
        this.mainGpu = mainGpu;
    }

    /**
     * Returns the device selection ({@code --device}).
     *
     * @return the comma-separated device list, or an empty string to leave the binding/build default
     */
    public String getDevices() {
        return devices;
    }

    /**
     * Sets the device selection ({@code --device}). A {@code null} argument resets to the empty default.
     *
     * @param devices the comma-separated backend device names (e.g. {@code Vulkan1}), or {@code null}/empty to leave default
     */
    public void setDevices(final String devices) {
        this.devices = devices == null ? DEFAULT_DEVICES : devices;
    }

    /**
     * Sets whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * @param cachePrompt {@code true} to reuse the shared prompt-prefix KV across calls
     */
    public void setCachePrompt(final boolean cachePrompt) {
        this.cachePrompt = cachePrompt;
    }

    /**
     * Returns the gpt-oss reasoning-effort level passed as the {@code reasoning_effort} kwarg.
     *
     * @return reasoning effort ({@code "low"}/{@code "medium"}/{@code "high"}), or empty to omit it
     */
    public String getReasoningEffort() {
        return reasoningEffort;
    }

    /**
     * Sets the gpt-oss reasoning-effort level.
     *
     * @param reasoningEffort {@code "low"}/{@code "medium"}/{@code "high"}, or empty/blank to omit
     *                        the kwarg (the model's own chat-template default then applies)
     */
    public void setReasoningEffort(final String reasoningEffort) {
        this.reasoningEffort = reasoningEffort;
    }

    /**
     * Returns the reasoning/think-token budget.
     *
     * @return reasoning budget tokens ({@code -1} = unrestricted)
     */
    public int getReasoningBudgetTokens() {
        return reasoningBudgetTokens;
    }

    /**
     * Sets the reasoning/think-token budget (caps harmony analysis tokens).
     *
     * @param reasoningBudgetTokens budget in tokens ({@code -1} = unrestricted, {@code 0} = no thinking)
     */
    public void setReasoningBudgetTokens(final int reasoningBudgetTokens) {
        this.reasoningBudgetTokens = reasoningBudgetTokens;
    }

    /**
     * Returns the DRY sampling multiplier.
     *
     * @return DRY multiplier ({@code 0.0} = disabled)
     */
    public float getDryMultiplier() {
        return dryMultiplier;
    }

    /**
     * Sets the DRY sampling multiplier.
     *
     * @param dryMultiplier DRY multiplier ({@code 0.0} = disabled)
     */
    public void setDryMultiplier(final float dryMultiplier) {
        this.dryMultiplier = dryMultiplier;
    }

    /**
     * Returns the DRY base.
     *
     * @return DRY base
     */
    public float getDryBase() {
        return dryBase;
    }

    /**
     * Sets the DRY base.
     *
     * @param dryBase DRY base
     */
    public void setDryBase(final float dryBase) {
        this.dryBase = dryBase;
    }

    /**
     * Returns the DRY allowed length (longest unpenalised repeating n-gram).
     *
     * @return DRY allowed length
     */
    public int getDryAllowedLength() {
        return dryAllowedLength;
    }

    /**
     * Sets the DRY allowed length.
     *
     * @param dryAllowedLength DRY allowed length
     */
    public void setDryAllowedLength(final int dryAllowedLength) {
        this.dryAllowedLength = dryAllowedLength;
    }

    /**
     * Returns the DRY penalty look-back window in tokens.
     *
     * @return DRY penalty last-n ({@code -1} = whole context, {@code 0} = disabled)
     */
    public int getDryPenaltyLastN() {
        return dryPenaltyLastN;
    }

    /**
     * Sets the DRY penalty look-back window in tokens.
     *
     * @param dryPenaltyLastN DRY penalty last-n ({@code -1} = whole context, {@code 0} = disabled)
     */
    public void setDryPenaltyLastN(final int dryPenaltyLastN) {
        this.dryPenaltyLastN = dryPenaltyLastN;
    }

    /**
     * Returns an unmodifiable view of the configured DRY sequence breakers.
     *
     * @return unmodifiable list of DRY sequence breakers (empty = use the model/binding default)
     */
    public List<String> getDrySequenceBreakers() {
        return Collections.unmodifiableList(drySequenceBreakers);
    }

    /**
     * Sets the DRY sequence breakers (tokens that reset n-gram matching).
     *
     * @param drySequenceBreakers sequence breakers, or {@code null} to reset to empty
     */
    public void setDrySequenceBreakers(final @Nullable List<String> drySequenceBreakers) {
        this.drySequenceBreakers = drySequenceBreakers != null ? drySequenceBreakers : new ArrayList<>();
    }

    /**
     * Returns an unmodifiable view of the configured stop strings.
     *
     * @return unmodifiable list of stop strings, or {@code null} if not set
     */
    public @Nullable List<String> getStopStrings() {
        return stopStrings != null ? Collections.unmodifiableList(stopStrings) : null;
    }

    /**
     * Sets the list of stop strings; a {@code null} value resets to an empty list.
     *
     * @param stopStrings stop strings, or {@code null} to clear
     */
    public void setStopStrings(final @Nullable List<String> stopStrings) {
        this.stopStrings = stopStrings != null ? stopStrings : new ArrayList<>();
    }

    /**
     * Returns the per-machine timing calibration, or {@code null} when not calibrated.
     *
     * @return the calibration, or {@code null}
     */
    public @Nullable AiCalibration getCalibration() {
        return calibration;
    }

    /**
     * Sets the per-machine timing calibration.
     *
     * @param calibration the calibration
     */
    public void setCalibration(final @Nullable AiCalibration calibration) {
        this.calibration = calibration;
    }
}
