// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.config;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import lombok.ToString;
import org.jspecify.annotations.Nullable;

/**
 * Mutable configuration object that carries all parameters for a single AI generation
 * step (model path, sampling parameters, retry policy, input trimming limits, stop
 * strings) between the Maven configuration layer and the AI provider implementations.
 *
 * <p>{@code toString} is generated by Lombok over the instance fields for build-log
 * diagnostics. {@code equals}/{@code hashCode} are intentionally NOT generated:
 * instances are mutable JavaBeans populated through setters by the Maven plugin
 * framework and managed by identity.
 */
@SuppressWarnings({"NullAway.Init", "initialization.fields.uninitialized"})
@ToString
public class AiGenerationConfig {

    /** Creates a new {@link AiGenerationConfig} with all defaults applied. */
    public AiGenerationConfig() {
        // no-op
    }

    /** Default context window size (in tokens) used when no explicit context size is configured. */
    public static final int DEFAULT_CONTEXT_SIZE = 32768;

    /** Default maximum number of output tokens to generate in a single inference call. */
    public static final int DEFAULT_MAX_OUTPUT_TOKENS = 128;

    /**
     * Default sampling temperature. Lower values make output more deterministic;
     * {@code 0.0} is fully greedy.
     */
    public static final float DEFAULT_TEMPERATURE = 0.15f;

    /** Default number of CPU threads used for llama.cpp inference. */
    public static final int DEFAULT_THREADS = 8;

    /**
     * Default maximum number of characters of source text fed into the prompt.
     * Used as a fallback when {@link #charsPerToken} is zero (e.g. in mock-based tests).
     * When {@link #charsPerToken} is greater than zero, {@code maxInputChars} is calculated
     * automatically from context size, output tokens, prompt overhead, and safety margin.
     */
    public static final int DEFAULT_MAX_INPUT_CHARS = 120000;

    /**
     * Default number of characters per token used in the automatic {@code maxInputChars}
     * calculation. A value of {@code 4} is a conventional conservative estimate that works
     * well across most Latin-script source code.
     *
     * <p>Set to {@code 0} to disable automatic calculation and fall back to
     * {@link #DEFAULT_MAX_INPUT_CHARS}.</p>
     */
    public static final int DEFAULT_CHARS_PER_TOKEN = 4;

    /**
     * Default safety margin in characters subtracted from the total available budget
     * during automatic {@code maxInputChars} calculation. Provides headroom for
     * tokenisation overhead and minor prompt expansions.
     */
    public static final int DEFAULT_SAFETY_MARGIN_CHARS = 500;

    /**
     * Default setting for whether to emit a warning when the prompt source text is trimmed
     * to fit within {@link #DEFAULT_MAX_INPUT_CHARS}.
     */
    public static final boolean DEFAULT_WARN_ON_TRIM = true;

    /**
     * Default maximum number of retry attempts when the AI provider returns an empty body.
     * A value of {@code 0} disables retries entirely.
     * Each retry uses a temperature incremented by {@link #DEFAULT_RETRY_TEMPERATURE_INCREMENT}.
     */
    public static final int DEFAULT_MAX_RETRIES = 3;

    /**
     * Default temperature increment applied on each successive retry attempt.
     * Added to {@link #temperature} per attempt: attempt 1 uses
     * {@code temperature + retryTemperatureIncrement}, attempt 2 uses
     * {@code temperature + 2 * retryTemperatureIncrement}, and so on.
     * Higher temperatures make the model less deterministic and can break out of
     * EOS-early failure modes.
     */
    public static final float DEFAULT_RETRY_TEMPERATURE_INCREMENT = 0.1f;

    /**
     * Default nucleus-sampling probability threshold.
     * Matches the {@code net.ladenthin:llama} {@code InferenceParameters} library default so
     * that models which do not declare an explicit value retain the same output distribution
     * as before this field was introduced.
     */
    public static final float DEFAULT_TOP_P = 0.9f;

    /**
     * Default top-k sampling limit.
     * Matches the {@code net.ladenthin:llama} {@code InferenceParameters} library default so
     * that models which do not declare an explicit value retain the same output distribution
     * as before this field was introduced.
     */
    public static final int DEFAULT_TOP_K = 40;

    /**
     * Default repetition penalty. A value of {@code 1.0} means no penalty and preserves
     * existing behaviour for models that do not specify it.
     */
    public static final float DEFAULT_REPEAT_PENALTY = 1.0f;

    /**
     * Default setting for whether the model's chat-template thinking mode is enabled.
     *
     * <p>When enabled, the model uses its own chat-template default for chain-of-thought
     * reasoning.  When disabled, {@link net.ladenthin.llama.parameters.ModelParameters#setChatTemplateKwargs}
     * is called with {@code {"enable_thinking": "false"}} to suppress the thinking block at the
     * Jinja template level — set to {@code false} for Gemma 4 definitions to prevent
     * {@code <|channel>thought} tokens from leaking into stored output.</p>
     */
    public static final boolean DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING = true;

    /**
     * Default for whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * <p>When {@code true}, the provider keeps the shared prompt-template prefix in the KV cache and
     * reuses it across files — only the differing source text is re-prefilled per file. This is a
     * pure speed optimisation: prefix reuse is exact, so the generated output is unchanged.</p>
     */
    public static final boolean DEFAULT_CACHE_PROMPT = true;

    private String modelPath;
    private int contextSize = DEFAULT_CONTEXT_SIZE;
    private int maxOutputTokens = DEFAULT_MAX_OUTPUT_TOKENS;
    private float temperature = DEFAULT_TEMPERATURE;
    private int threads = DEFAULT_THREADS;
    private int charsPerToken = DEFAULT_CHARS_PER_TOKEN;
    private int maxInputChars = DEFAULT_MAX_INPUT_CHARS;
    private boolean warnOnTrim = DEFAULT_WARN_ON_TRIM;
    private int maxRetries = DEFAULT_MAX_RETRIES;
    private float retryTemperatureIncrement = DEFAULT_RETRY_TEMPERATURE_INCREMENT;
    private float topP = DEFAULT_TOP_P;
    private int topK = DEFAULT_TOP_K;
    private float repeatPenalty = DEFAULT_REPEAT_PENALTY;
    private boolean chatTemplateEnableThinking = DEFAULT_CHAT_TEMPLATE_ENABLE_THINKING;
    private boolean cachePrompt = DEFAULT_CACHE_PROMPT;
    private List<String> stopStrings = new ArrayList<>();

    /**
     * Returns the GGUF model file path.
     *
     * @return model file path, or {@code null} if not set
     */
    public String getModelPath() {
        return modelPath;
    }

    /**
     * Sets the GGUF model file path.
     *
     * @param modelPath absolute or relative path to the model file
     */
    public void setModelPath(final String modelPath) {
        this.modelPath = modelPath;
    }

    /**
     * Returns the context window size in tokens.
     *
     * @return context window size in tokens
     */
    public int getContextSize() {
        return contextSize;
    }

    /**
     * Sets the context window size in tokens.
     *
     * @param contextSize context window size in tokens
     */
    public void setContextSize(final int contextSize) {
        this.contextSize = contextSize;
    }

    /**
     * Returns the maximum number of output tokens per inference call.
     *
     * @return maximum output tokens
     */
    public int getMaxOutputTokens() {
        return maxOutputTokens;
    }

    /**
     * Sets the maximum number of output tokens per inference call.
     *
     * @param maxOutputTokens maximum output tokens
     */
    public void setMaxOutputTokens(final int maxOutputTokens) {
        this.maxOutputTokens = maxOutputTokens;
    }

    /**
     * Returns the sampling temperature.
     *
     * @return sampling temperature
     */
    public float getTemperature() {
        return temperature;
    }

    /**
     * Sets the sampling temperature.
     *
     * @param temperature sampling temperature; lower is more deterministic
     */
    public void setTemperature(final float temperature) {
        this.temperature = temperature;
    }

    /**
     * Returns the number of CPU threads used for inference.
     *
     * @return number of CPU threads
     */
    public int getThreads() {
        return threads;
    }

    /**
     * Sets the number of CPU threads used for inference.
     *
     * @param threads number of CPU threads
     */
    public void setThreads(final int threads) {
        this.threads = threads;
    }

    /**
     * Returns the number of characters per token used in automatic {@code maxInputChars}
     * calculation.
     *
     * @return chars-per-token ratio; {@code 0} disables automatic calculation
     */
    public int getCharsPerToken() {
        return charsPerToken;
    }

    /**
     * Sets the number of characters per token.
     *
     * @param charsPerToken approximate characters per token; use {@code 0} to disable
     *                      automatic calculation and fall back to {@link #getMaxInputChars()}
     */
    public void setCharsPerToken(final int charsPerToken) {
        this.charsPerToken = charsPerToken;
    }

    /**
     * Returns the maximum number of input characters fed to the prompt.
     *
     * @return maximum input characters
     */
    public int getMaxInputChars() {
        return maxInputChars;
    }

    /**
     * Sets the maximum number of input characters fed to the prompt.
     *
     * @param maxInputChars maximum input characters
     */
    public void setMaxInputChars(final int maxInputChars) {
        this.maxInputChars = maxInputChars;
    }

    /**
     * Returns whether a warning is emitted when the prompt source text is trimmed.
     *
     * @return {@code true} if trim warnings are enabled
     */
    public boolean isWarnOnTrim() {
        return warnOnTrim;
    }

    /**
     * Sets whether a warning is emitted when the prompt source text is trimmed.
     *
     * @param warnOnTrim {@code true} to enable trim warnings
     */
    public void setWarnOnTrim(final boolean warnOnTrim) {
        this.warnOnTrim = warnOnTrim;
    }

    /**
     * Returns the maximum number of retry attempts on empty-body responses.
     *
     * @return maximum retry attempts
     */
    public int getMaxRetries() {
        return maxRetries;
    }

    /**
     * Sets the maximum number of retry attempts on empty-body responses.
     *
     * @param maxRetries maximum retry attempts
     */
    public void setMaxRetries(final int maxRetries) {
        this.maxRetries = maxRetries;
    }

    /**
     * Returns the temperature increment added on each retry attempt.
     *
     * @return temperature increment per retry
     */
    public float getRetryTemperatureIncrement() {
        return retryTemperatureIncrement;
    }

    /**
     * Sets the temperature increment added on each retry attempt.
     *
     * @param retryTemperatureIncrement temperature increment per retry
     */
    public void setRetryTemperatureIncrement(final float retryTemperatureIncrement) {
        this.retryTemperatureIncrement = retryTemperatureIncrement;
    }

    /**
     * Returns the nucleus-sampling probability threshold.
     *
     * @return top-p value
     */
    public float getTopP() {
        return topP;
    }

    /**
     * Sets the nucleus-sampling probability threshold.
     *
     * @param topP top-p value
     */
    public void setTopP(final float topP) {
        this.topP = topP;
    }

    /**
     * Returns the top-k sampling limit.
     *
     * @return top-k value
     */
    public int getTopK() {
        return topK;
    }

    /**
     * Sets the top-k sampling limit.
     *
     * @param topK top-k value
     */
    public void setTopK(final int topK) {
        this.topK = topK;
    }

    /**
     * Returns the repetition penalty.
     *
     * @return repeat penalty
     */
    public float getRepeatPenalty() {
        return repeatPenalty;
    }

    /**
     * Sets the repetition penalty.
     *
     * @param repeatPenalty repeat penalty
     */
    public void setRepeatPenalty(final float repeatPenalty) {
        this.repeatPenalty = repeatPenalty;
    }

    /**
     * Returns whether the model's chat-template thinking mode is enabled.
     *
     * @return {@code true} if chat-template thinking mode is enabled
     */
    public boolean isChatTemplateEnableThinking() {
        return chatTemplateEnableThinking;
    }

    /**
     * Sets whether the model's chat-template thinking mode is enabled.
     *
     * @param chatTemplateEnableThinking {@code true} to enable chat-template thinking mode
     */
    public void setChatTemplateEnableThinking(final boolean chatTemplateEnableThinking) {
        this.chatTemplateEnableThinking = chatTemplateEnableThinking;
    }

    /**
     * Returns whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * @return {@code true} when prompt-prefix KV reuse across files is enabled
     */
    public boolean isCachePrompt() {
        return cachePrompt;
    }

    /**
     * Sets whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * @param cachePrompt {@code true} to reuse the shared prompt-prefix KV across calls
     */
    public void setCachePrompt(final boolean cachePrompt) {
        this.cachePrompt = cachePrompt;
    }

    /**
     * Returns an unmodifiable view of the configured stop strings.
     *
     * @return unmodifiable list of stop strings, or {@code null} if not set
     */
    public @Nullable List<String> getStopStrings() {
        return stopStrings != null ? Collections.unmodifiableList(stopStrings) : null;
    }

    /**
     * Sets the list of stop strings; a {@code null} value resets to an empty list.
     *
     * @param stopStrings stop strings, or {@code null} to clear
     */
    public void setStopStrings(final @Nullable List<String> stopStrings) {
        this.stopStrings = stopStrings != null ? stopStrings : new ArrayList<>();
    }
}
