// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex;

import java.nio.file.Path;
import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Immutable request object passed to an {@link AiGenerationProvider}: identifies the
 * prompt template, the source file being processed, its current text, and the existing
 * header (if any).
 *
 * <p>Record-shaped value type marked {@link ConvertToRecord} for the future Java&nbsp;17+
 * migration. Accessors are record-style. {@code equals}, {@code hashCode} and
 * {@code toString} are generated by Lombok over all four fields; full value semantics
 * apply.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public class AiGenerationRequest {
    private final String promptKey;
    private final Path sourceFile;
    private final String sourceText;
    private final AiMdHeader currentHeader;

    /**
     * Creates a new {@link AiGenerationRequest}.
     *
     * @param promptKey     key of the prompt template to use
     * @param sourceFile    path to the source file being processed
     * @param sourceText    contents of the source file
     * @param currentHeader current header of the corresponding {@code .ai.md} file
     */
    public AiGenerationRequest(String promptKey, Path sourceFile, String sourceText, AiMdHeader currentHeader) {
        Objects.requireNonNull(promptKey, "promptKey");
        Objects.requireNonNull(sourceFile, "sourceFile");
        Objects.requireNonNull(sourceText, "sourceText");
        Objects.requireNonNull(currentHeader, "currentHeader");
        this.promptKey = promptKey;
        this.sourceFile = sourceFile;
        this.sourceText = sourceText;
        this.currentHeader = currentHeader;
    }

    /**
     * Returns the prompt template key.
     *
     * @return prompt template key
     */
    public String promptKey() {
        return promptKey;
    }

    /**
     * Returns the path to the source file.
     *
     * @return source file path
     */
    public Path sourceFile() {
        return sourceFile;
    }

    /**
     * Returns the source file contents.
     *
     * @return source file contents
     */
    public String sourceText() {
        return sourceText;
    }

    /**
     * Returns the current header of the corresponding {@code .ai.md} file.
     *
     * @return current header
     */
    public AiMdHeader currentHeader() {
        return currentHeader;
    }
}
