// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.mojo;

import java.io.File;
import java.util.List;
import lombok.ToString;
import net.ladenthin.srcmorph.config.AiFieldGenerationConfig;
import net.ladenthin.srcmorph.config.AiModelDefinition;
import net.ladenthin.srcmorph.config.SrcMorphConfiguration;
import net.ladenthin.srcmorph.engine.SrcMorphException;
import net.ladenthin.srcmorph.prompt.AiPromptDefinition;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugins.annotations.Parameter;

/**
 * Base class for all AI index mojos. Centralises the parameters shared by every goal
 * ({@code generate}, {@code aggregate-packages}, {@code aggregate-project}, {@code calibrate}) and
 * provides {@link #buildConfiguration()}, which maps the shared {@code @Parameter} fields onto a
 * {@link net.ladenthin.srcmorph.config.SrcMorphConfiguration} for the matching
 * {@code net.ladenthin.srcmorph.engine} engine to execute.
 *
 * <p>Concrete subclasses must implement {@link #getLlamaContextSize()} and
 * {@link #getLlamaThreads()} so that each goal can declare its own
 * {@code @Parameter}-annotated field with the appropriate default value.</p>
 *
 * <p>{@code toString} is generated by Lombok over the {@code @Parameter} fields so
 * Maven debug logs ({@code -X}) print a useful dump of the goal's resolved
 * configuration. {@code equals}/{@code hashCode} are intentionally NOT generated:
 * Maven instantiates mojos per execution and manages them by identity.
 */
// @Parameter fields are populated by the Maven plugin framework via reflection after
// construction. NullAway is configured via ExcludedFieldAnnotations to skip them; Checker
// Framework has no equivalent option for plugin-framework fields, so we suppress class-level.
@SuppressWarnings("initialization.fields.uninitialized")
@ToString(callSuper = true)
public abstract class AbstractAiIndexMojo extends AbstractMojo {

    /** Creates a new {@link AbstractAiIndexMojo}. */
    protected AbstractAiIndexMojo() {
        // no-op
    }

    /** The Maven project base directory, injected by Maven. */
    @Parameter(defaultValue = "${project.basedir}", readonly = true, required = true)
    protected File baseDirectory;

    /**
     * Directory into which all {@code .ai.md} files are written.
     * Defaults to {@code ${project.basedir}/src/site/ai}.
     */
    @Parameter(property = "aiIndex.outputDirectory", defaultValue = "${project.basedir}/src/site/ai")
    protected File outputDirectory;

    /**
     * Global skip switch: when {@code true}, <em>every</em> AI index goal (generate,
     * aggregate-packages, aggregate-project) skips and returns immediately. To toggle a single
     * phase instead, use that goal's own {@code skip<Phase>} flag (see {@link #isPhaseSkipped()}).
     */
    @Parameter(property = "aiIndex.skip", defaultValue = "false")
    protected boolean skip;

    /**
     * When {@code true}, regenerates AI fields even when they already have a value.
     * When {@code false}, only missing or changed entries are processed.
     */
    @Parameter(property = "aiIndex.force", defaultValue = "false")
    protected boolean force;

    /**
     * Source subdirectory paths (relative to {@code basedir}) to restrict processing.
     * When empty, all discovered source roots are used.
     */
    @Parameter(property = "aiIndex.subtrees")
    protected List<String> subtrees;

    /**
     * Name of the AI generation provider to use.
     * Supported values: {@code mock}, {@code llamacpp-jni}.
     *
     * @see net.ladenthin.srcmorph.provider.AiGenerationProviderFactory
     */
    @Parameter(property = "aiIndex.generationProvider", defaultValue = "mock")
    protected String generationProvider;

    /** Prompt template definitions referenced by field generation configurations. */
    @Parameter
    protected List<AiPromptDefinition> promptDefinitions;

    /**
     * AI model definitions that pair a lookup key with a complete set of model parameters.
     * Field-generation entries and the provider configuration reference these definitions
     * by key rather than embedding the full parameter set inline.
     *
     * @see net.ladenthin.srcmorph.config.AiModelDefinition
     * @see net.ladenthin.srcmorph.config.AiModelDefinitionSupport
     */
    @Parameter
    protected List<AiModelDefinition> aiDefinitions;

    /** Per-field AI generation configurations controlling which prompt and AI definition to use. */
    @Parameter
    protected List<AiFieldGenerationConfig> fieldGenerations;

    /**
     * Optional native library path passed to the llama.cpp JNI provider.
     * Leave unset to use the bundled native library.
     */
    @Parameter(property = "aiIndex.llama.libraryPath")
    protected String llamaLibraryPath;

    /** Path to the GGUF model file used by the llama.cpp JNI provider. */
    @Parameter(property = "aiIndex.llama.modelPath")
    protected String llamaModelPath;

    /** Maximum number of output tokens the model may generate per request. */
    @Parameter(property = "aiIndex.llama.maxOutputTokens", defaultValue = "128")
    protected int llamaMaxOutputTokens;

    /** Sampling temperature for the llama.cpp model (lower = more deterministic). */
    @Parameter(property = "aiIndex.llama.temperature", defaultValue = "0.15")
    protected float llamaTemperature;

    // -------------------------------------------------------------------------
    // Abstract methods — subclasses declare @Parameter fields with their defaults
    // -------------------------------------------------------------------------

    /**
     * Returns the llama.cpp context window size for this goal.
     * Each concrete mojo declares its own {@code @Parameter}-annotated field and
     * implements this method to return it.
     *
     * @return configured llama.cpp context window size
     */
    protected abstract int getLlamaContextSize();

    /**
     * Returns the number of CPU threads for llama.cpp inference for this goal.
     * Each concrete mojo declares its own {@code @Parameter}-annotated field and
     * implements this method to return it.
     *
     * @return configured number of CPU threads for llama.cpp inference
     */
    protected abstract int getLlamaThreads();

    /**
     * Returns whether this individual goal (phase) is disabled by its own phase-specific skip flag,
     * independent of the global {@link #skip}. Each concrete goal declares its own
     * {@code skip<Phase>} {@code @Parameter} and returns it here, so the three phases (generate,
     * aggregate-packages, aggregate-project) can be switched on and off independently.
     *
     * @return {@code true} if this phase's own skip flag is set
     */
    protected abstract boolean isPhaseSkipped();

    // -------------------------------------------------------------------------
    // Shared utility methods
    // -------------------------------------------------------------------------

    /**
     * Returns whether this goal should skip execution: either the global {@link #skip} (which skips
     * every phase) or this phase's own {@link #isPhaseSkipped()} flag. Centralised here so every goal
     * applies the same rule identically. Skip flags stay mojo-side (a Maven lifecycle concern); an
     * engine built from {@link #buildConfiguration()} always executes when asked.
     *
     * @return {@code true} if the goal must not run
     */
    protected boolean shouldSkip() {
        return skip || isPhaseSkipped();
    }

    /**
     * Maps the {@code @Parameter} fields shared by every goal onto a new
     * {@link net.ladenthin.srcmorph.config.SrcMorphConfiguration}. Concrete subclasses that need
     * additional fields (e.g. {@code pluginVersion}, {@code aiVersion}, {@code fileExtensions})
     * call this first and then set their own goal-specific fields on the returned instance.
     *
     * @return a configuration populated from every shared {@code @Parameter} field
     */
    protected SrcMorphConfiguration buildConfiguration() {
        final SrcMorphConfiguration config = new SrcMorphConfiguration();
        config.setBaseDirectory(baseDirectory);
        config.setOutputDirectory(outputDirectory);
        config.setForce(force);
        config.setSubtrees(subtrees);
        config.setGenerationProvider(generationProvider);
        config.setPromptDefinitions(promptDefinitions);
        config.setAiDefinitions(aiDefinitions);
        config.setFieldGenerations(fieldGenerations);
        config.setLlamaLibraryPath(llamaLibraryPath);
        config.setLlamaModelPath(llamaModelPath);
        config.setLlamaContextSize(getLlamaContextSize());
        config.setLlamaMaxOutputTokens(llamaMaxOutputTokens);
        config.setLlamaTemperature(llamaTemperature);
        config.setLlamaThreads(getLlamaThreads());
        return config;
    }

    /**
     * Returns {@code cause}'s message for wrapping into a
     * {@link org.apache.maven.plugin.MojoExecutionException}, falling back to {@link Throwable#toString()}
     * when the message is {@code null}. Every {@link SrcMorphException} constructor requires a non-null
     * message in practice, but {@link Throwable#getMessage()} is not statically non-null, so every mojo's
     * {@code catch (SrcMorphException e)} block goes through this helper rather than passing
     * {@code e.getMessage()} straight through.
     *
     * @param cause the caught engine exception
     * @return a non-null message suitable for {@code MojoExecutionException}'s constructor
     */
    protected static String messageOf(final SrcMorphException cause) {
        final String message = cause.getMessage();
        return message != null ? message : cause.toString();
    }
}
