// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.mojo;

import java.io.IOException;
import java.nio.file.Path;
import lombok.ToString;
import net.ladenthin.srcmorph.config.AiFieldGenerationConfig;
import net.ladenthin.srcmorph.config.AiModelDefinitionSupport;
import net.ladenthin.srcmorph.indexer.ProjectIndexer;
import net.ladenthin.srcmorph.prompt.AiPromptSupport;
import net.ladenthin.srcmorph.provider.AiGenerationProvider;
import net.ladenthin.srcmorph.provider.AiGenerationProviderFactory;
import net.ladenthin.srcmorph.support.Java8CompatibilityHelper;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

/**
 * Maven goal {@code ai-index:aggregate-project}: aggregates every per-package
 * {@code package.ai.md} into a single project-level {@code project.ai.md} — the top of the
 * three-level index.
 *
 * <p>By default this goal is fully deterministic: it harvests the one-line lead already present in
 * each package summary and writes a compact, navigable table of contents that links to every
 * package, calling no AI model. It then needs no provider, model, or prompt configuration — only
 * {@link #outputDirectory}, {@link #force}, and {@link #skip}.</p>
 *
 * <p><strong>Optional AI overview (opt-in).</strong> When a {@code <fieldGeneration>} is configured
 * (a {@code promptKey} + {@code aiDefinitionKey}), the goal additionally makes <em>one</em> AI call
 * to write a short project overview paragraph from the per-package leads (see {@link ProjectIndexer}).
 * Because the overview reuses the shared provider/prompt/model parameters, this mojo extends
 * {@code AbstractAiIndexMojo} (the provider-oriented base) — but it builds a provider only when a
 * field generation is present, so the deterministic default needs no model and pays no model cost.</p>
 *
 * <p>{@code toString} is generated by Lombok over the {@code @Parameter} fields so Maven debug logs
 * ({@code -X}) print a useful dump of the goal's resolved configuration. {@code equals}/{@code hashCode}
 * are intentionally NOT generated: Maven instantiates mojos per execution and manages them by identity.</p>
 */
// @Parameter fields are populated by the Maven plugin framework via reflection after
// construction. NullAway is configured via ExcludedFieldAnnotations to skip them; Checker
// Framework has no equivalent option for plugin-framework fields, so we suppress class-level.
@SuppressWarnings("initialization.fields.uninitialized")
@Mojo(name = "aggregate-project", threadSafe = true)
@ToString(callSuper = true)
public class AggregateProjectMojo extends AbstractAiIndexMojo {

    /** Creates a new {@link AggregateProjectMojo}. */
    public AggregateProjectMojo() {
        // no-op
    }

    /**
     * Title used for the project index when the Maven {@code ${project.name}} is absent or blank.
     */
    private static final String DEFAULT_PROJECT_TITLE = "project";

    /**
     * Phase switch for the <strong>project</strong> phase (the {@code aggregate-project} goal): when
     * {@code true}, only this phase is skipped. The global {@link #skip} still skips every phase.
     */
    @Parameter(property = "aiIndex.project.skip", defaultValue = "false")
    private boolean skipProject;

    /** Plugin version recorded in the project index header. */
    @Parameter(defaultValue = "${project.version}", readonly = true)
    private String pluginVersion;

    /** AI summarisation logic version recorded in the project index header. */
    @Parameter(property = "aiIndex.aiVersion", defaultValue = "0.0.0")
    private String aiVersion;

    /** Maven project name recorded as the project index title. */
    @Parameter(defaultValue = "${project.name}", readonly = true)
    private String projectName;

    /**
     * llama.cpp context window size used only as the fallback when no {@code <fieldGeneration>} is
     * configured; with an overview field generation present, the size comes from its AI definition.
     */
    @Parameter(property = "aiIndex.llama.contextSize", defaultValue = "4096")
    private int llamaContextSize;

    /** CPU threads for llama.cpp inference, used only on the no-field-generation fallback path. */
    @Parameter(property = "aiIndex.llama.threads", defaultValue = "2")
    private int llamaThreads;

    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    @Override
    protected int getLlamaContextSize() {
        return llamaContextSize;
    }

    @Override
    protected int getLlamaThreads() {
        return llamaThreads;
    }

    @Override
    protected boolean isPhaseSkipped() {
        return skipProject;
    }

    @Override
    public void execute() throws MojoExecutionException {
        if (shouldSkip()) {
            getLog().info("AI project index aggregation skipped.");
            return;
        }

        final Path outputPath = outputDirectory.toPath().toAbsolutePath().normalize();

        getLog().info("Starting AI project index aggregation");
        getLog().info("Output directory: " + outputPath);
        getLog().info("Force           : " + force);

        if (!outputPath.toFile().exists()) {
            getLog().info("AI output directory does not exist, skipping project index: " + outputPath);
            return;
        }

        final String title =
                projectName == null || compatibilityHelper.isBlank(projectName) ? DEFAULT_PROJECT_TITLE : projectName;

        try {
            final int written;
            if (fieldGenerations != null && !fieldGenerations.isEmpty()) {
                written = aggregateWithOverview(outputPath, title, fieldGenerations.get(0));
            } else {
                getLog().info("Project overview generation: disabled (no fieldGenerations configured)");
                final ProjectIndexer indexer = new ProjectIndexer(title, pluginVersion, aiVersion, force);
                written = indexer.aggregate(outputPath);
            }
            getLog().info("Project index files written: " + written);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to aggregate project AI index file under " + outputPath, e);
        }

        getLog().info("AI project index aggregation finished.");
    }

    /**
     * Aggregates the project index with the optional AI overview paragraph enabled, generated by the
     * given field generation. A provider is created (and closed) only on this path, so the
     * deterministic default never instantiates a model.
     *
     * @param outputPath the resolved output directory holding the {@code .ai.md} tree
     * @param title      the resolved project title
     * @param overview   the overview field generation (prompt + model)
     * @return {@code 1} if the project index was written or refreshed, {@code 0} otherwise
     * @throws MojoExecutionException if the provider or model definitions are misconfigured
     * @throws IOException            if the output tree cannot be read or the index cannot be written
     */
    private int aggregateWithOverview(final Path outputPath, final String title, final AiFieldGenerationConfig overview)
            throws MojoExecutionException, IOException {
        final AiPromptSupport promptSupport = buildPromptSupport();
        final AiModelDefinitionSupport modelDefinitionSupport = buildAiModelDefinitionSupport();
        getLog().info("Project overview generation: enabled (prompt '" + overview.getPromptKey() + "')");
        final AiGenerationProviderFactory providerFactory = new AiGenerationProviderFactory();
        try (AiGenerationProvider provider =
                providerFactory.create(generationProvider, buildLlamaCppJniConfig(), promptSupport)) {
            final ProjectIndexer indexer = new ProjectIndexer(
                    title, pluginVersion, aiVersion, force, provider, overview, promptSupport, modelDefinitionSupport);
            return indexer.aggregate(outputPath);
        }
    }
}
