// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.mojo;

import java.io.IOException;
import java.nio.file.Path;
import lombok.ToString;
import net.ladenthin.srcmorph.config.SrcMorphConfiguration;
import net.ladenthin.srcmorph.engine.AggregateProjectEngine;
import net.ladenthin.srcmorph.engine.SrcMorphException;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;

/**
 * Maven goal {@code ai-index:aggregate-project}: aggregates every per-package
 * {@code package.ai.md} into a single project-level {@code project.ai.md} — the top of the
 * three-level index.
 *
 * <p>By default this goal is fully deterministic: it harvests the one-line lead already present in
 * each package summary and writes a compact, navigable table of contents that links to every
 * package, calling no AI model. It then needs no provider, model, or prompt configuration — only
 * {@link #outputDirectory}, {@link #force}, and {@link #skip}.</p>
 *
 * <p><strong>Optional AI overview (opt-in).</strong> When a {@code <fieldGeneration>} is configured
 * (a {@code promptKey} + {@code aiDefinitionKey}), the goal additionally makes <em>one</em> AI call
 * to write a short project overview paragraph from the per-package leads — see
 * {@link net.ladenthin.srcmorph.indexer.ProjectIndexer}. Because the overview reuses the shared
 * provider/prompt/model parameters, this mojo extends {@code AbstractAiIndexMojo} (the
 * provider-oriented base) — but {@link net.ladenthin.srcmorph.engine.AggregateProjectEngine} builds a
 * provider only when a field generation is present, so the deterministic default needs no model and
 * pays no model cost.</p>
 *
 * <p>Thin wrapper: builds a {@link SrcMorphConfiguration} from its {@code @Parameter} fields and
 * delegates the whole run to {@link AggregateProjectEngine}.</p>
 *
 * <p>{@code toString} is generated by Lombok over the {@code @Parameter} fields so Maven debug logs
 * ({@code -X}) print a useful dump of the goal's resolved configuration. {@code equals}/{@code hashCode}
 * are intentionally NOT generated: Maven instantiates mojos per execution and manages them by identity.</p>
 */
// @Parameter fields are populated by the Maven plugin framework via reflection after
// construction. NullAway is configured via ExcludedFieldAnnotations to skip them; Checker
// Framework has no equivalent option for plugin-framework fields, so we suppress class-level.
@SuppressWarnings("initialization.fields.uninitialized")
@Mojo(name = "aggregate-project", threadSafe = true)
@ToString(callSuper = true)
public class AggregateProjectMojo extends AbstractAiIndexMojo {

    /** Creates a new {@link AggregateProjectMojo}. */
    public AggregateProjectMojo() {
        // no-op
    }

    /**
     * Phase switch for the <strong>project</strong> phase (the {@code aggregate-project} goal): when
     * {@code true}, only this phase is skipped. The global {@link #skip} still skips every phase.
     */
    @Parameter(property = "aiIndex.project.skip", defaultValue = "false")
    private boolean skipProject;

    /** Plugin version recorded in the project index header. */
    @Parameter(defaultValue = "${project.version}", readonly = true)
    private String pluginVersion;

    /** AI summarisation logic version recorded in the project index header. */
    @Parameter(property = "aiIndex.aiVersion", defaultValue = "0.0.0")
    private String aiVersion;

    /** Maven project name recorded as the project index title. */
    @Parameter(defaultValue = "${project.name}", readonly = true)
    private String projectName;

    /**
     * llama.cpp context window size used only as the fallback when no {@code <fieldGeneration>} is
     * configured; with an overview field generation present, the size comes from its AI definition.
     */
    @Parameter(property = "aiIndex.llama.contextSize", defaultValue = "4096")
    private int llamaContextSize;

    /** CPU threads for llama.cpp inference, used only on the no-field-generation fallback path. */
    @Parameter(property = "aiIndex.llama.threads", defaultValue = "2")
    private int llamaThreads;

    @Override
    protected int getLlamaContextSize() {
        return llamaContextSize;
    }

    @Override
    protected int getLlamaThreads() {
        return llamaThreads;
    }

    @Override
    protected boolean isPhaseSkipped() {
        return skipProject;
    }

    /**
     * Maps this goal's own {@code @Parameter} fields onto the shared configuration built by
     * {@link AbstractAiIndexMojo#buildConfiguration()}.
     *
     * @return the fully populated configuration for {@link AggregateProjectEngine}
     */
    private SrcMorphConfiguration buildAggregateProjectConfiguration() {
        final SrcMorphConfiguration config = buildConfiguration();
        config.setPluginVersion(pluginVersion);
        config.setAiVersion(aiVersion);
        config.setProjectName(projectName);
        return config;
    }

    @Override
    public void execute() throws MojoExecutionException {
        if (shouldSkip()) {
            getLog().info("AI project index aggregation skipped.");
            return;
        }

        final Path outputPath = outputDirectory.toPath().toAbsolutePath().normalize();
        try {
            new AggregateProjectEngine(buildAggregateProjectConfiguration()).execute();
        } catch (SrcMorphException e) {
            throw new MojoExecutionException(messageOf(e), e);
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to aggregate project AI index file under " + outputPath, e);
        }
    }
}
