// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.config;

import lombok.ToString;

/**
 * Per-model, per-machine timing calibration measured by the {@code ai-index:calibrate} goal and pasted
 * onto an {@code <aiDefinition>} via {@code <calibration>}. It makes the plan's time estimate reflect the
 * actual hardware (GPU/CPU, quant, context) instead of the built-in reference-CPU coefficients.
 *
 * <p>All values default to {@code 0}, which means "not calibrated": the estimator then falls back to its
 * built-in model. The calibration is used only when {@link #getPrefillTokensPerSecond()} and
 * {@link #getDecodeTokensPerSecond()} are both {@code > 0}.</p>
 *
 * <p><strong>Note:</strong> this class must remain a mutable JavaBean with setters because the Maven
 * plugin framework populates it via reflection. {@code toString} is generated by Lombok;
 * {@code equals}/{@code hashCode} are intentionally NOT generated (mutable configuration data).</p>
 */
@SuppressWarnings({"NullAway.Init", "initialization.fields.uninitialized"})
@ToString
public class AiCalibration {

    /** Creates a new {@link AiCalibration}. */
    public AiCalibration() {
        // no-op
    }

    /** Measured prefill (prompt-processing) throughput in tokens per second; {@code 0} = not calibrated. */
    private double prefillTokensPerSecond;

    /** Measured decode (answer-generation) throughput in tokens per second; {@code 0} = not calibrated. */
    private double decodeTokensPerSecond;

    /** Measured characters per token for this model on the sampled source; {@code 0} = use the default. */
    private double charsPerToken;

    /**
     * Returns the measured prefill throughput (tokens/second), or {@code 0} when not calibrated.
     *
     * @return the prefill tokens per second
     */
    public double getPrefillTokensPerSecond() {
        return prefillTokensPerSecond;
    }

    /**
     * Sets the measured prefill throughput (tokens/second).
     *
     * @param prefillTokensPerSecond the prefill tokens per second
     */
    public void setPrefillTokensPerSecond(final double prefillTokensPerSecond) {
        this.prefillTokensPerSecond = prefillTokensPerSecond;
    }

    /**
     * Returns the measured decode throughput (tokens/second), or {@code 0} when not calibrated.
     *
     * @return the decode tokens per second
     */
    public double getDecodeTokensPerSecond() {
        return decodeTokensPerSecond;
    }

    /**
     * Sets the measured decode throughput (tokens/second).
     *
     * @param decodeTokensPerSecond the decode tokens per second
     */
    public void setDecodeTokensPerSecond(final double decodeTokensPerSecond) {
        this.decodeTokensPerSecond = decodeTokensPerSecond;
    }

    /**
     * Returns the measured characters per token, or {@code 0} when not measured.
     *
     * @return the characters per token
     */
    public double getCharsPerToken() {
        return charsPerToken;
    }

    /**
     * Sets the measured characters per token.
     *
     * @param charsPerToken the characters per token
     */
    public void setCharsPerToken(final double charsPerToken) {
        this.charsPerToken = charsPerToken;
    }
}
