// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.srcmorph.config;

import java.util.List;
import lombok.ToString;
import org.jspecify.annotations.Nullable;

/**
 * A named, reusable group of {@link AiFactCounter}s, registered in the goal's {@code <factDefinitions>}
 * list and referenced from a routing rule by {@link AiFieldGenerationConfig#getFactsKey() factsKey}.
 *
 * <p>Mirrors {@code <promptDefinitions>}: define a fact set once (e.g. {@code java-facts},
 * {@code sql-facts}) and reference it from every rule that needs it, instead of repeating the same
 * {@code <facts>} block inline on each rule.</p>
 *
 * <p><strong>Note:</strong> this class must remain a mutable JavaBean with setters because the Maven
 * plugin framework populates it via reflection. {@code toString} is generated by Lombok;
 * {@code equals}/{@code hashCode} are intentionally NOT generated (instances are configuration data
 * managed by key in a lookup, and the mutable JavaBean shape makes value semantics unsafe).</p>
 *
 * @see AiFactDefinitionSupport
 * @see AiFactCounter
 */
@SuppressWarnings({"NullAway.Init", "initialization.fields.uninitialized"})
@ToString
public class AiFactDefinition {

    /** Creates a new {@link AiFactDefinition}. */
    public AiFactDefinition() {
        // no-op
    }

    /** Lookup key referenced by {@link AiFieldGenerationConfig#getFactsKey()}. */
    private String key;

    /** The fact counters this group contributes. */
    private @Nullable List<AiFactCounter> facts;

    /**
     * Returns the lookup key.
     *
     * @return the key
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the lookup key.
     *
     * @param key the key
     */
    public void setKey(final String key) {
        this.key = key;
    }

    /**
     * Returns the fact counters, or {@code null} when none are configured.
     *
     * @return the fact counters, or {@code null}
     */
    public @Nullable List<AiFactCounter> getFacts() {
        return facts;
    }

    /**
     * Sets the fact counters.
     *
     * @param facts the fact counters
     */
    public void setFacts(final @Nullable List<AiFactCounter> facts) {
        this.facts = facts;
    }
}
