// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.document;

import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord;

/**
 * Immutable result produced by {@link net.ladenthin.maven.llamacpp.aiindex.indexer.AiFieldGenerationSupport#processFieldGenerations}.
 *
 * <p>Carries the AI-generated document body text produced by a single processing pass.
 * Defaults to an empty string when no body target is present in the field generation
 * configuration.</p>
 *
 * <p>Record-shaped value type marked {@link net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord} for the future Java&nbsp;17+
 * migration. The accessor methods follow record-style ({@code body()}, not
 * {@code getBody()}) so the migration is mechanical. {@code equals}, {@code hashCode}
 * and {@code toString} are generated by Lombok over the single field; full value
 * semantics apply.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public class AiGenerationResult {
    private final String body;

    /**
     * Creates a new {@link AiGenerationResult}.
     *
     * <p>Empty body is allowed (and is the documented default when no body
     * field was generated); {@code null} is not, so callers cannot leak
     * a null body into downstream rendering.</p>
     *
     * @param body AI-generated body text destined for {@link AiMdDocument#body()};
     *             must not be {@code null} (pass {@code ""} for no-body)
     * @throws NullPointerException if {@code body} is {@code null}
     */
    public AiGenerationResult(String body) {
        this.body = Objects.requireNonNull(body, "body");
    }

    /**
     * Returns the AI-generated body text.
     *
     * @return body text, never {@code null}; may be empty if no body field was generated
     */
    public String body() {
        return body;
    }
}
