// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.document;

import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord;

/**
 * Immutable representation of an {@code .ai.md} document consisting of a header and a body.
 *
 * <p>Record-shaped value type marked {@link net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord} for the future Java&nbsp;17+
 * migration. Accessors are record-style ({@code header()}, {@code body()}). {@code equals},
 * {@code hashCode} and {@code toString} are generated by Lombok over both fields.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public class AiMdDocument {
    private final AiMdHeader header;
    private final String body;

    /**
     * Creates a new {@link AiMdDocument}.
     *
     * @param header metadata header
     * @param body   markdown body text
     */
    public AiMdDocument(AiMdHeader header, String body) {
        Objects.requireNonNull(header, "header");
        Objects.requireNonNull(body, "body");
        this.header = header;
        this.body = body;
    }

    /**
     * Returns the metadata header.
     *
     * @return metadata header
     */
    public AiMdHeader header() {
        return header;
    }

    /**
     * Returns the markdown body.
     *
     * @return markdown body
     */
    public String body() {
        return body;
    }
}
