// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.document;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord;

/**
 * Canonical header model for a single {@code .ai.md} document.
 *
 * <p>The header contains only deterministic metadata fields. All AI-generated content
 * is stored in the document body (after the {@code ---} separator), keeping the header
 * machine-parseable without AI involvement.</p>
 *
 * <p>Field semantics:</p>
 * <ul>
 *   <li><b>title</b>: Display title of the node, usually the file name or logical package path.</li>
 *   <li><b>h</b>: Header format version. Used to detect incompatible header schema changes.</li>
 *   <li><b>c</b>: Checksum of the represented node state.
 *     <ul>
 *       <li>For {@code file}: CRC32 of the source file content.</li>
 *       <li>For {@code package}: deterministic CRC32 derived from the direct child entries,
 *           ordered ascending by child name/path.</li>
 *     </ul>
 *   </li>
 *   <li><b>d</b>: Source date of the represented node state.
 *     <ul>
 *       <li>For {@code file}: last modification timestamp of the source file.</li>
 *       <li>For {@code package}: newest {@code d} value of the direct child entries.</li>
 *     </ul>
 *   </li>
 *   <li><b>t</b>: Timestamp when this {@code .ai.md} document was last generated.</li>
 *   <li><b>g</b>: Version of the template/generator implementation that produced this document.</li>
 *   <li><b>a</b>: Version of the AI summarization logic or AI output schema applied to this document.</li>
 *   <li><b>x</b>: Node type, for example {@code file}, {@code package}, or {@code project}.</li>
 *   <li><b>children</b>: Deterministic child links (markdown), carried in the header so navigation
 *       stays machine-parseable and the AI body stays free-form. For a {@code package}: one link per
 *       child {@code .ai.md} (files and sub-packages). For a {@code project}: one link per package.
 *       Empty for a leaf {@code file}.</li>
 * </ul>
 *
 * <p>Important invariants:</p>
 * <ul>
 *   <li>Header comparison for rewrite decisions is based on all structural fields:
 *       {@code h}, {@code c}, {@code d}, {@code g}, {@code a}, {@code x}, and {@code title}.</li>
 *   <li>Package aggregation must be deterministic. Child traversal order must therefore be stable,
 *       typically ascending by child file name or relative path.</li>
 *   <li>The generator should preserve the body when the structural state did not change.</li>
 * </ul>
 *
 * <p>Record-shaped value type marked {@link net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord} for the future Java&nbsp;17+
 * migration. Accessors are record-style ({@code title()}, {@code h()}, ...). {@code equals},
 * {@code hashCode} and {@code toString} are generated by Lombok across all fields (including
 * {@code children}); full value semantics apply.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public final class AiMdHeader {
    private final String title;
    private final String h;
    private final String c;
    private final String d;
    private final String t;
    private final String g;
    private final String a;
    private final String x;
    private final List<String> children;

    /**
     * Creates a new {@link AiMdHeader} with an explicit child-link list.
     *
     * @param title    display title (typically the file name or package path)
     * @param h        header format version
     * @param c        source-state checksum
     * @param d        source-state timestamp
     * @param t        generation timestamp of this {@code .ai.md}
     * @param g        generator/template version
     * @param a        AI summarisation logic / output schema version
     * @param x        node type, for example {@code file}, {@code package}, or {@code project}
     * @param children deterministic child links (markdown), e.g. {@code [Foo.java](Foo.java.ai.md)};
     *                 empty for leaf {@code file} nodes. Defensively copied; the stored list is unmodifiable.
     */
    public AiMdHeader(
            String title,
            String h,
            String c,
            String d,
            String t,
            String g,
            String a,
            String x,
            Collection<String> children) {
        Objects.requireNonNull(title, "title");
        Objects.requireNonNull(h, "h");
        Objects.requireNonNull(c, "c");
        Objects.requireNonNull(d, "d");
        Objects.requireNonNull(t, "t");
        Objects.requireNonNull(g, "g");
        Objects.requireNonNull(a, "a");
        Objects.requireNonNull(x, "x");
        this.title = title;
        this.h = h;
        this.c = c;
        this.d = d;
        this.t = t;
        this.g = g;
        this.a = a;
        this.x = x;
        // No separate requireNonNull(children): new ArrayList<>(children) already throws NPE on a
        // null list, so an explicit check would be a redundant, equivalent (un-killable) mutant.
        this.children = Collections.unmodifiableList(new ArrayList<>(children));
    }

    /**
     * Creates a new {@link AiMdHeader} with no child links (the common case for {@code file} nodes).
     *
     * @param title display title (typically the file name or package path)
     * @param h     header format version
     * @param c     source-state checksum
     * @param d     source-state timestamp
     * @param t     generation timestamp of this {@code .ai.md}
     * @param g     generator/template version
     * @param a     AI summarisation logic / output schema version
     * @param x     node type, for example {@code file}, {@code package}, or {@code project}
     */
    public AiMdHeader(String title, String h, String c, String d, String t, String g, String a, String x) {
        this(title, h, c, d, t, g, a, x, Collections.emptyList());
    }

    /**
     * Returns the display title.
     *
     * @return display title
     */
    public String title() {
        return title;
    }

    /**
     * Returns the header format version.
     *
     * @return header format version
     */
    public String h() {
        return h;
    }

    /**
     * Returns the source-state checksum.
     *
     * @return source-state checksum
     */
    public String c() {
        return c;
    }

    /**
     * Returns the source-state timestamp.
     *
     * @return source-state timestamp
     */
    public String d() {
        return d;
    }

    /**
     * Returns the generation timestamp of this {@code .ai.md}.
     *
     * @return generation timestamp
     */
    public String t() {
        return t;
    }

    /**
     * Returns the generator/template version.
     *
     * @return generator/template version
     */
    public String g() {
        return g;
    }

    /**
     * Returns the AI summarisation logic version.
     *
     * @return AI summarisation logic version
     */
    public String a() {
        return a;
    }

    /**
     * Returns the node type ({@code file}, {@code package}, or {@code project}).
     *
     * @return node type
     */
    public String x() {
        return x;
    }

    /**
     * Returns the deterministic child links carried in the header — markdown links to each child
     * {@code .ai.md} (files and sub-packages) for a {@code package} node, or to each package for a
     * {@code project} node. Empty for leaf {@code file} nodes. The returned list is unmodifiable.
     *
     * @return unmodifiable list of child-link markdown strings; never {@code null}, possibly empty
     */
    public List<String> children() {
        return children;
    }
}
