// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.provider;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord;

/**
 * Immutable configuration for the llama.cpp JNI provider.
 *
 * <p>Record-shaped value type marked {@link net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord} for the future Java&nbsp;17+
 * migration. Accessors are record-style. {@code equals}, {@code hashCode} and
 * {@code toString} are generated by Lombok over all fourteen fields; full value semantics
 * apply. Lombok emits the exact-bit float comparison
 * ({@code Float.floatToIntBits}) automatically.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public final class LlamaCppJniConfig {
    private final String libraryPath;
    private final String modelPath;
    private final int contextSize;
    private final int maxOutputTokens;
    private final float temperature;
    private final int threads;
    private final float topP;
    private final int topK;
    private final float minP;
    private final float repeatPenalty;
    private final boolean chatTemplateEnableThinking;
    private final boolean cachePrompt;
    private final String reasoningEffort;
    private final List<String> stopStrings;

    /**
     * Creates a new {@link LlamaCppJniConfig}.
     *
     * @param libraryPath                 native library path; may be {@code null}
     * @param modelPath                   path to the GGUF model file
     * @param contextSize                 context window size in tokens
     * @param maxOutputTokens             maximum number of output tokens per call
     * @param temperature                 sampling temperature
     * @param threads                     number of CPU threads
     * @param topP                        nucleus-sampling probability threshold
     * @param topK                        top-k sampling limit
     * @param minP                        min-p sampling threshold ({@code 0.0} = disabled)
     * @param repeatPenalty               repetition penalty
     * @param chatTemplateEnableThinking  whether chat-template thinking mode is enabled
     * @param cachePrompt                 whether llama.cpp prompt caching ({@code cache_prompt}) is enabled
     * @param reasoningEffort             gpt-oss reasoning-effort kwarg value ("low"/"medium"/"high"); empty omits it
     * @param stopStrings                 stop strings; may be {@code null} (treated as empty)
     */
    public LlamaCppJniConfig(
            String libraryPath,
            String modelPath,
            int contextSize,
            int maxOutputTokens,
            float temperature,
            int threads,
            float topP,
            int topK,
            float minP,
            float repeatPenalty,
            boolean chatTemplateEnableThinking,
            boolean cachePrompt,
            String reasoningEffort,
            List<String> stopStrings) {
        Objects.requireNonNull(modelPath, "modelPath");
        this.libraryPath = libraryPath;
        this.modelPath = modelPath;
        this.contextSize = contextSize;
        this.maxOutputTokens = maxOutputTokens;
        this.temperature = temperature;
        this.threads = threads;
        this.topP = topP;
        this.topK = topK;
        this.minP = minP;
        this.repeatPenalty = repeatPenalty;
        this.chatTemplateEnableThinking = chatTemplateEnableThinking;
        this.cachePrompt = cachePrompt;
        this.reasoningEffort = reasoningEffort;
        this.stopStrings = stopStrings != null ? stopStrings : Collections.emptyList();
    }

    /**
     * Returns the native library path.
     *
     * @return native library path, or {@code null} to use the bundled library
     */
    public String libraryPath() {
        return libraryPath;
    }

    /**
     * Returns the GGUF model file path.
     *
     * @return model file path
     */
    public String modelPath() {
        return modelPath;
    }

    /**
     * Returns the context window size in tokens.
     *
     * @return context window size
     */
    public int contextSize() {
        return contextSize;
    }

    /**
     * Returns the maximum number of output tokens per call.
     *
     * @return maximum output tokens
     */
    public int maxOutputTokens() {
        return maxOutputTokens;
    }

    /**
     * Returns the sampling temperature.
     *
     * @return sampling temperature
     */
    public float temperature() {
        return temperature;
    }

    /**
     * Returns the number of CPU threads.
     *
     * @return number of CPU threads
     */
    public int threads() {
        return threads;
    }

    /**
     * Returns the nucleus-sampling probability threshold.
     *
     * @return top-p value
     */
    public float topP() {
        return topP;
    }

    /**
     * Returns the top-k sampling limit.
     *
     * @return top-k value
     */
    public int topK() {
        return topK;
    }

    /**
     * Returns the min-p sampling threshold.
     *
     * @return min-p threshold ({@code 0.0} = disabled)
     */
    public float minP() {
        return minP;
    }

    /**
     * Returns the repetition penalty.
     *
     * @return repeat penalty
     */
    public float repeatPenalty() {
        return repeatPenalty;
    }

    /**
     * Returns whether chat-template thinking mode is enabled.
     *
     * @return {@code true} when chat-template thinking mode is enabled
     */
    public boolean chatTemplateEnableThinking() {
        return chatTemplateEnableThinking;
    }

    /**
     * Returns whether llama.cpp prompt caching ({@code cache_prompt}) is enabled.
     *
     * @return {@code true} when prompt-prefix KV reuse across files is enabled
     */
    public boolean cachePrompt() {
        return cachePrompt;
    }

    /**
     * Returns the gpt-oss reasoning-effort kwarg value.
     *
     * @return reasoning effort ("low"/"medium"/"high"), or empty to omit the kwarg
     */
    public String reasoningEffort() {
        return reasoningEffort;
    }

    /**
     * Returns an unmodifiable view of the configured stop strings.
     *
     * @return unmodifiable list of stop strings
     */
    public List<String> stopStrings() {
        return Collections.unmodifiableList(stopStrings);
    }
}
