// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.provider;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import lombok.ToString;
import net.ladenthin.llama.LlamaModel;
import net.ladenthin.llama.args.ReasoningFormat;
import net.ladenthin.llama.parameters.InferenceParameters;
import net.ladenthin.llama.parameters.ModelParameters;
import net.ladenthin.llama.value.Pair;
import net.ladenthin.maven.llamacpp.aiindex.document.AiGenerationRequest;
import net.ladenthin.maven.llamacpp.aiindex.prompt.AiPromptSupport;
import net.ladenthin.maven.llamacpp.aiindex.support.Java8CompatibilityHelper;
import org.jspecify.annotations.Nullable;

/**
 * {@link AiGenerationProvider} implementation backed by the {@code net.ladenthin:llama}
 * JNI binding, running GGUF models locally via llama.cpp.
 *
 * <p>{@code toString} is generated by Lombok over the configuration and prompt-support
 * fields for build-log diagnostics. The native {@link LlamaModel} handle is excluded
 * from the rendered output because its default {@code toString} prints implementation
 * details (native pointer, internal state) that are noisy and not useful for
 * Maven-side debugging.
 */
@ToString
public final class LlamaCppJniAiGenerationProvider implements AiGenerationProvider, AutoCloseable {

    private final LlamaCppJniConfig config;

    // Native llama.cpp model handle — its toString prints native pointer / internal
    // state details; excluded from the rendered output. Lazily initialised on first
    // generate() so constructing the provider (via the factory, or when every file is
    // already cached) is cheap and native-free; the ~90 MB GGUF + native context are
    // only loaded when generation actually happens.
    @ToString.Exclude
    private @Nullable LlamaModel model;

    private final AiPromptSupport promptSupport;
    private final AiCompletionParser completionParser = new AiCompletionParser();
    private final Java8CompatibilityHelper compatibilityHelper = new Java8CompatibilityHelper();

    /**
     * Fixed llama.cpp server slot every request is pinned to. The model is loaded once and reused
     * for all files; pinning each request to the same slot lets the prompt cache
     * ({@code cache_prompt}) reuse the shared prompt-template prefix's KV across files instead of
     * re-prefilling it for every file. Reuse is exact, so generated output is unchanged.
     */
    private static final int REUSE_SLOT_ID = 0;

    /** Chat-template kwarg controlling Qwen-style thinking (ignored by non-Qwen templates). */
    private static final String ENABLE_THINKING_KWARG = "enable_thinking";

    /** Chat-template kwarg for the gpt-oss reasoning-effort level (ignored by non-gpt-oss templates). */
    private static final String REASONING_EFFORT_KWARG = "reasoning_effort";

    /** Number of chat-template kwargs put into the map (used for presizing). */
    private static final int CHAT_TEMPLATE_KWARG_COUNT = 2;

    /**
     * Creates a new {@link LlamaCppJniAiGenerationProvider}; the GGUF model is loaded lazily on the first generate(...) call.
     *
     * @param config        llama.cpp configuration
     * @param promptSupport prompt lookup used to render request prompts
     */
    public LlamaCppJniAiGenerationProvider(final LlamaCppJniConfig config, final AiPromptSupport promptSupport) {
        this.config = Objects.requireNonNull(config, "config");
        this.promptSupport = Objects.requireNonNull(promptSupport, "promptSupport");
    }

    /** Loads the GGUF model on first use and caches it for subsequent calls. */
    private LlamaModel model() {
        LlamaModel current = model;
        if (current == null) {
            final Map<String, String> chatTemplateKwargs =
                    new HashMap<>(compatibilityHelper.hashMapCapacityFor(CHAT_TEMPLATE_KWARG_COUNT));
            chatTemplateKwargs.put(ENABLE_THINKING_KWARG, String.valueOf(config.chatTemplateEnableThinking()));
            // gpt-oss honors reasoning_effort; non-gpt-oss chat templates ignore it. An empty
            // configured value omits the kwarg so the model's own template default applies.
            if (!compatibilityHelper.isBlank(config.reasoningEffort())) {
                chatTemplateKwargs.put(REASONING_EFFORT_KWARG, config.reasoningEffort());
            }
            final ModelParameters modelParameters = new ModelParameters()
                    .setModel(config.modelPath())
                    .setCtxSize(config.contextSize())
                    .setThreads(config.threads())
                    // Parse reasoning channels (Qwen <think>, gpt-oss harmony analysis) into
                    // reasoning_content so message content stays clean (final channel only).
                    .setReasoningFormat(ReasoningFormat.AUTO)
                    .setChatTemplateKwargs(chatTemplateKwargs);
            current = new LlamaModel(modelParameters);
            model = current;
        }
        return current;
    }

    @Override
    public String generate(final AiGenerationRequest request) throws IOException {
        return generate(request, config.temperature());
    }

    @Override
    public String generate(final AiGenerationRequest request, final float temperatureOverride) throws IOException {
        // Static instructions go in the SYSTEM message (byte-identical across files, so its KV
        // prefix is reused by cache_prompt); the variable file name + source go in the USER message.
        final String systemPrompt = promptSupport.systemPrompt(request.promptKey());
        final String userMessage = promptSupport.userMessage(request.sourceFile(), request.sourceText());

        final List<Pair<String, String>> messages = new ArrayList<>();
        messages.add(new Pair<>("user", userMessage));

        // InferenceParameters uses immutable withers: each with* returns a new instance, so the
        // whole request is built as a single chain.
        final InferenceParameters inferenceParameters = new InferenceParameters("")
                .withMessages(systemPrompt, messages)
                .withUseChatTemplate(true)
                .withTemperature(temperatureOverride)
                .withNPredict(config.maxOutputTokens())
                .withTopP(config.topP())
                .withTopK(config.topK())
                .withMinP(config.minP())
                .withTopNSigma(config.topNSigma())
                .withRepeatPenalty(config.repeatPenalty())
                .withStopStrings(config.stopStrings().toArray(new String[0]))
                // Keep the shared prompt-template prefix warm in the KV cache and reuse it across
                // files (pinned to one slot); only the differing source is re-prefilled.
                // Reuse is exact -> output unchanged.
                .withCachePrompt(config.cachePrompt())
                .withSlotId(REUSE_SLOT_ID);

        return completionParser.parseCompletion(model().chatCompleteText(inferenceParameters));
    }

    @Override
    public void close() {
        final LlamaModel current = model;
        if (current != null) {
            current.close();
        }
    }
}
