// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0
package net.ladenthin.maven.llamacpp.aiindex.prompt;

import java.util.Objects;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord;

/**
 * Immutable result of preparing a prompt: the substituted prompt text, the source text
 * actually included, and metrics describing how the source was trimmed (if at all).
 *
 * <p>Record-shaped value type marked {@link net.ladenthin.maven.llamacpp.aiindex.support.ConvertToRecord} for the future Java&nbsp;17+
 * migration. Accessors are record-style ({@code prompt()}, {@code sourceText()}, ...).
 * {@code equals}, {@code hashCode} and {@code toString} are generated by Lombok over all
 * six fields; full value semantics apply.</p>
 */
@ConvertToRecord
@ToString
@EqualsAndHashCode
public class AiPreparedPrompt {
    private final String prompt;
    private final String sourceText;
    private final boolean trimmed;
    private final int originalSourceLength;
    private final int trimmedSourceLength;
    private final int availableSourceChars;

    /**
     * Creates a new {@link AiPreparedPrompt}.
     *
     * @param prompt              fully prepared prompt text
     * @param sourceText          source text that was substituted into the prompt
     * @param trimmed             {@code true} when {@code sourceText} was shorter than the original input
     * @param originalSourceLength original number of characters in the source text before trimming
     * @param trimmedSourceLength  number of characters retained after trimming
     * @param availableSourceChars character budget that was available for substitution
     */
    public AiPreparedPrompt(
            String prompt,
            String sourceText,
            boolean trimmed,
            int originalSourceLength,
            int trimmedSourceLength,
            int availableSourceChars) {
        Objects.requireNonNull(prompt, "prompt");
        Objects.requireNonNull(sourceText, "sourceText");
        this.prompt = prompt;
        this.sourceText = sourceText;
        this.trimmed = trimmed;
        this.originalSourceLength = originalSourceLength;
        this.trimmedSourceLength = trimmedSourceLength;
        this.availableSourceChars = availableSourceChars;
    }

    /**
     * Returns the prepared prompt text.
     *
     * @return prepared prompt text
     */
    public String prompt() {
        return prompt;
    }

    /**
     * Returns the source text that was substituted into the prompt.
     *
     * @return source text used for substitution
     */
    public String sourceText() {
        return sourceText;
    }

    /**
     * Returns whether the source text was trimmed to fit within the available budget.
     *
     * @return {@code true} when trimming occurred
     */
    public boolean trimmed() {
        return trimmed;
    }

    /**
     * Returns the original source text length before trimming.
     *
     * @return original source text length in characters
     */
    public int originalSourceLength() {
        return originalSourceLength;
    }

    /**
     * Returns the source text length after trimming.
     *
     * @return retained source text length in characters
     */
    public int trimmedSourceLength() {
        return trimmedSourceLength;
    }

    /**
     * Returns the character budget that was available for source substitution.
     *
     * @return available character budget
     */
    public int availableSourceChars() {
        return availableSourceChars;
    }
}
